use super::PracticeDefinition;
use super::callouts::*;

// 11. Hypertech (p. 579)
pub const HYPERTECH: PracticeDefinition = PracticeDefinition {
    id: "hypertech",
    name: "Hypertech",
    name_pt: "Hipertecnologia",
    aliases: &["Hipertecnologia", "Enlightened Science", "Applied Technological Magick"],
    page_ref: "M20, p. 579",
    quote: "Hypertech is about potential… finding it, recognizing it, expanding upon it to create something even better.",
    quote_pt: "A hipertecnologia trata de potencial… encontrá-lo, reconhecê-lo e expandi-lo para criar algo superior.",
    paradigm_affinity: &[
        "A Mechanistic Cosmos",
        "A World of Gods and Monsters",
        "Divine Order and Earthly Chaos",
        "Everything is Chaos",
        "Everything is Data",
        "Might is Right",
        "Tech Holds All Answers",
    ],
    paradigm_affinity_pt: &[
        "Um Cosmos Mecanicista",
        "Um Mundo de Deuses e Monstros",
        "Ordem Divina e Caos Terreno",
        "Tudo é Caos",
        "Tudo é Informação",
        "O Poder Faz o Direito",
        "A Tecnologia Tem Todas as Respostas",
    ],
    description: "A catch-all term for the hundreds of methods used to unite advanced technology with visionary ideas, hypertech represents a dynamic approach to science. Despite the rumblings of disgruntled old-school mystics, this approach has transformed the world we live in. Computers, obviously, reflect the most obvious aspects of this Art and Science, but the brute force of metallurgy, the explosive powers of internal combustion, the harnessed lightning of electronic technologies, and the heady physics behind it all drive hypertech and humanity to new and exciting frontiers. “Oh, THAT’S not magick,” sniff the critics… but actually, it is. It’s not Hermetic wizardry, after all, that gave us cars, phones, computers, and electronic power… all those things, and more, began as hypertech.\n\nThe hypertech practice reflects the genius of the human condition – that restless striving to perfect and understand. In earlier forms (like those employed by the Order of Reason), such “godless” Arts were reflections of deep reverence. Men and women of God sought the keys to His Creations, seeing divine glory in every twig or flower.\n\nAt the core of this practice – in its many applications, from cloning and biotech to astrophysics, mechanical engineering, chemistry, theoretical physics, and far more – hypertech is about potential… finding it, recognizing it, expanding upon it to create something even better than what we had before. A scientist understands that she doesn’t have all the answers and so constantly seeks them out. She’ll spend endless hours in the lab or reading journals – not so that she can turn humanity into drones, but so that she can bring something better into being. Despite its apparent sterility, hypertech retains a visionary optimism.\n\nAlthough the scientist might believe in some Creator, she’s not shackled to blind faith. Instead, she employs rigorous tests, complicated data, consistent verification, and an Art founded not on chance or outside whims but upon tested principles and concrete achievements. She’s the Progenitor, the Adept, the technomancer whose tools reflect the precision of her Arts. Unlike her deluded counterparts who practice their weird science, this visionary employs solid protocols for dependable results. In a way, she’s the High Ritual Magus of our age, making wonders with vigorous Science.",
    description_pt: "Um termo abrangente para as centenas de métodos usados para unir tecnologia avançada a ideias visionárias, a hipertecnologia representa uma abordagem dinâmica da ciência. Apesar dos resmungos de místicos tradicionalistas descontentes, essa abordagem transformou o mundo em que vivemos. Os computadores, obviamente, refletem os aspectos mais evidentes desta Arte e Ciência, mas a força bruta da metalurgia, os poderes explosivos da combustão interna, o relâmpago domado das tecnologias eletrônicas e a física inebriante por trás de tudo isso impulsionam a hipertecnologia e a humanidade para fronteiras novas e empolgantes. 'Ah, ISSO não é magia', desdenham os críticos… mas, na verdade, é. Afinal de contas, não foi a feitiçaria hermética que nos deu carros, telefones, computadores e energia elétrica… todas essas coisas, e muito mais, começaram como hipertecnologia.\n\nA prática da hipertecnologia reflete a genialidade da condição humana — essa busca incansável por aperfeiçoar e compreender. Em formas anteriores (como as empregadas pela Ordem da Razão), tais Artes 'sem Deus' eram reflexos de profunda reverência. Homens e mulheres de Deus buscavam as chaves para Suas Criações, enxergando a glória divina em cada ramo ou flor.\n\nNo cerne desta prática — em suas inúmeras aplicações, da clonagem e biotecnologia à astrofísica, engenharia mecânica, química, física teórica e muito mais —, a hipertecnologia trata de potencial… encontrá-lo, reconhecê-lo e expandi-lo para criar algo ainda melhor do que tínhamos antes. Uma cientista compreende que não possui todas as respostas e, por isso, busca-as constantemente. Ela passa horas intermináveis no laboratório ou lendo periódicos científicos — não para que possa transformar a humanidade em drones, mas para que possa trazer algo melhor à existência. Apesar de sua aparente esterilidade, a hipertecnologia retém um otimismo visionário.\n\nEmbora a cientista possa acreditar em algum Criador, ela não está acorrentada à fé cega. Em vez disso, ela emprega testes rigorosos, dados complicados, verificação consistente e uma Arte fundada não no acaso ou em caprichos externos, mas sobre princípios testados e realizações concretas. Ela é a Progenitora, o Adepto, a tecnomante cujas ferramentas refletem a precisão de suas Artes. Ao contrário de seus equivalentes iludidos que praticam sua ciência bizarra, esta visionária emprega protocolos sólidos para resultados confiáveis. De certa forma, ela é o Alto Mago Ritual da nossa era, operando maravilhas através de uma Ciência vigorosa.",
    common_instruments: &[
        "Books & Technical Journals",
        "Brain/Computer Interface",
        "Computers & Terminals",
        "Devices and Machines",
        "Household Tools",
        "Inventions & Prototypes",
        "Laboratories",
        "Nanotech",
        "Writing & Code",
        "Tools of Technological Achievement",
    ],
    common_instruments_pt: &[
        "Livros e Periódicos Científicos",
        "Interface Cérebro/Computador",
        "Computadores e Terminais",
        "Dispositivos e Máquinas Avançadas",
        "Ferramentas de Engenharia",
        "Protótipos e Invenções",
        "Laboratórios e Salas Limpas",
        "Nanotecnologia",
        "Código-Fonte e Algoritmos",
        "Instrumentos Tecnológicos de Precisão",
    ],
    associated_abilities: &[
        "Academics",
        "Computer",
        "Crafts",
        "Hypertech",
        "Investigation",
        "Medicine",
        "Research",
        "Science",
        "Technology",
    ],
    associated_abilities_pt: &[
        "Acadêmicos",
        "Computador",
        "Ofícios",
        "Hipertecnologia",
        "Investigação",
        "Medicina",
        "Pesquisa",
        "Ciência",
        "Tecnologia",
    ],
    callouts: &[],
};

// 12. Maleficia (pp. 579-580)
pub const MALEFICIA: PracticeDefinition = PracticeDefinition {
    id: "maleficia",
    name: "Maleficia",
    name_pt: "Malefício",
    aliases: &["Malefício", "Black Magic", "Infernalism", "Sinister Sorcery", "Curses of Desecration"],
    page_ref: "M20, pp. 579-580",
    quote: "Deliberately crafted toward malignant aims. That combination of sick deeds and ugly intentions poisons everything it touches.",
    quote_pt: "Conjurado com propósitos deliberadamente malignos. Essa combinação de atos vis e intenções perversas envenena tudo ao redor.",
    paradigm_affinity: &[
        "A World of Gods and Monsters",
        "Bring Back the Golden Age",
        "Divine Order and Earthly Chaos",
        "Everything is Chaos",
        "Everything’s an Illusion, Prison, or Mistake",
        "Might is Right",
        "One-Way Trip to Oblivion",
    ],
    paradigm_affinity_pt: &[
        "Um Mundo de Deuses e Monstros",
        "Trazer de Volta a Idade de Ouro",
        "Ordem Divina e Caos Terreno",
        "Tudo é Caos",
        "Tudo é uma Ilusão, Prisão ou Erro",
        "O Poder Faz o Direito",
        "Viagem Sem Volta para o Esquecimento",
    ],
    description: "Certain magicks are deliberately cruel. Cast with malicious intentions, they’re intended to cause harm and distress. Medieval law called such Arts maleficia – “evil-doing” – and that’s appropriate. For though most conceptions of witchcraft are mistaken, there are people who use bad magick for bad ends. When folks think of black magic, they’re referring to this deliberately obscene practice… although any form of magick can be hurtful, maleficia is intentionally crafted toward malignant aims. Curses; possessions; damnations; invocations to malevolent powers; infernal pacts, inhuman abilities; violations of body, mind, and spirit… such is the realm of maleficia.\n\nAlthough the Nephandi seem to be the obvious offenders in this regard, anyone with a sufficiently bent motivation can employ a form of maleficia. The evangelist who calls upon his congregation to pray for the death of some hated figure is invoking maleficia; the forbidden Hermetic rites for summoning demons employ it too. The Black Masses present pretty obvious examples; what’s less obvious, though, is that the Catholic Church itself has a history of Requiem Masses, performed to kill living people, and Amatory Masses, intended to compel affections upon unwilling people. The Grimoire of Honorius – attributed to a Pope – features Masses to be performed for evil purposes. Just as any mystic practice can inflict harm, so too can any mystic practice become twisted into maleficia.\n\nAs a practice, maleficia features deliberate cruelty and perversion. Sex, for example, is a sacrament in certain traditions, but malefic practices use sex in its most tortured and nonconsensual forms. Sacrifices become as brutal and horrific as possible; prayers are spoken backwards; sacred symbols and objects are deliberately defiled through acts of defiant malevolence.\n\nFor obvious reasons, maleficia tends to leave nasty Resonance behind. That combination of sick deeds and ugly intentions poisons everything it touches. Rooms, tools, and people feel tainted after a malefic rite; even Sleepers can sense that something’s not right about such things.\n\nThe mage can clean up every physical trace of the crime, but a metaphysical essence lingers… often attracting corrupt entities that pick up where the malefactor left off…",
    description_pt: "Certas formas de magia são deliberadamente cruéis. Conjuradas com intenções maliciosas, destinam-se a causar dano e aflição. O direito medieval chamava tais Artes de maleficia — 'atos malignos' — e isso é apropriado. Pois, embora a maioria das concepções sobre bruxaria seja equivocada, existem pessoas que usam magia ruim para fins ruins. Quando as pessoas pensam em magia negra, é a essa prática deliberadamente obscena que se referem… embora qualquer forma de magia possa ser prejudicial, o malefício é intencionalmente forjado para propósitos malignos. Maldições; possessões; condenações; invocações a poderes malévolos; pactos infernais; faculdades desumanas; violações do corpo, mente e espírito… esse é o domínio do malefício.\n\nEmbora os Nefandi pareçam ser os culpados mais óbvios a esse respeito, qualquer pessoa com uma motivação suficientemente deturpada pode empregar uma forma de malefício. O pregador que convoca sua congregação a orar pela morte de uma figura odiada está invocando o malefício; os ritos herméticos proibidos para invocar demônios também o empregam. As Missas Negras apresentam exemplos bastante óbvios; o que é menos óbvio, contudo, é que a própria Igreja Católica tem um histórico de Missas de Réquiem rezadas para matar pessoas vivas e Missas Amatórias destinadas a forçar afeições sobre pessoas relutantes. O Grimório de Honório — atribuído a um Papa — traz Missas a serem rezadas para propósitos malignos. Assim como qualquer prática mística pode infligir dano, da mesma forma qualquer prática mística pode ser deturpada em malefício.\n\nComo prática, o malefício apresenta crueldade deliberada e perversão. O sexo, por exemplo, é um sacramento em certas tradições, mas as práticas maléficas usam o sexo em suas formas mais tortuosas e não-consensuais. Os sacrifícios tornam-se tão brutais e hediondos quanto possível; orações são proferidas ao contrário; símbolos e objetos sagrados são deliberadamente profanados através de atos de malevolência insolente.\n\nPor razões óbvias, o malefício tende a deixar uma Ressonância asquerosa para trás. Essa combinação de atos vis e intenções perversas envenena tudo o que toca. Salas, instrumentos e pessoas parecem maculados após um rito maléfico; até mesmo os Adormecidos conseguem sentir que há algo de errado em tais coisas.\n\nO mago pode limpar cada vestígio físico do crime, mas uma essência metafísica permanece… atraindo com frequência entidades corruptas que continuam de onde o malfeitor parou…",
    common_instruments: &[
        "Artwork",
        "Blood and Fluids",
        "Bodywork",
        "Bones and Remains (Often Fresh)",
        "Circles and Designs (Inverted)",
        "Cups and Vessels",
        "Curses",
        "Elements",
        "Eye Contact",
        "Drugs and Poisons",
        "Gems and Valuables",
        "Group Rites (Black Masses)",
        "Music",
        "Offerings and Sacrifice",
        "Prayers and Invocations (Reversed)",
        "Sex (Typically Nonconsensual)",
        "Voice",
        "Weapons",
    ],
    common_instruments_pt: &[
        "Obras de Arte Profanadas",
        "Sangue e Fluidos Malditos",
        "Manipulação Corporal Dolorosa",
        "Ossos e Restos Mortais Frescos",
        "Círculos e Desenhos Invertidos",
        "Cálices Profanados",
        "Maldições e Pragas",
        "Elementos Corrompidos",
        "Olhar Malevolente",
        "Drogas e Venenos Letais",
        "Bens Ricos e Moedas Maculadas",
        "Ritos em Grupo e Missas Negras",
        "Música Macabra e Dissonante",
        "Oferendas Sangrentas e Sacrifícios",
        "Orações e Salmos Reversos",
        "Sexo Tortuoso",
        "Voz e Blasfêmias",
        "Armas de Tortura e Lâminas Negras",
    ],
    associated_abilities: &[
        "Cosmology",
        "Enigmas",
        "Esoterica",
        "Expression",
        "Intimidation",
        "Melee",
        "Occult",
        "Pharmacopeia",
        "Seduction",
        "Torture",
    ],
    associated_abilities_pt: &[
        "Cosmologia (Mundo Infernal)",
        "Enigmas",
        "Esotérica Proibida",
        "Expressão",
        "Intimidação",
        "Armas Brancas",
        "Ocultismo",
        "Farmacopeia e Venenos",
        "Sedução Tóxica",
        "Tortura",
    ],
    callouts: &[BOX_LEFT_AND_RIGHT_HAND_PATHS],
};

// 13. Martial Arts (pp. 580-581)
pub const MARTIAL_ARTS: PracticeDefinition = PracticeDefinition {
    id: "martial_arts",
    name: "Martial Arts",
    name_pt: "Artes Marciais",
    aliases: &["Artes Marciais", "Do", "Gung Fu", "Combat Discipline", "Physical Transcendence"],
    page_ref: "M20, pp. 580-581",
    quote: "The artist manifests her will through clarity, energy, and activity, using the body as a mystic focus.",
    quote_pt: "A artista marcial manifesta sua Vontade através da clareza, energia e movimento, usando o corpo como foco místico.",
    paradigm_affinity: &[
        "A World of Gods and Monsters",
        "Bring Back the Golden Age",
        "Creation’s Divine and Alive",
        "Divine Order and Earthly Chaos",
        "Everything is Chaos",
        "Everything’s an Illusion, Prison, or Mistake",
        "Might is Right",
        "Tech Holds All Answers",
    ],
    paradigm_affinity_pt: &[
        "Um Mundo de Deuses e Monstros",
        "Trazer de Volta a Idade de Ouro",
        "A Criação é Divina e Viva",
        "Ordem Divina e Caos Terreno",
        "Tudo é Caos",
        "Tudo é uma Ilusão, Prisão ou Erro",
        "O Poder Faz o Direito",
        "A Tecnologia Tem Todas as Respostas",
    ],
    description: "The human machine is a miracle whose vast potential is hampered by undisciplined habits and acquired behaviors. Martial arts expand upon that potential, unlocking the deeper physical and metaphysical abilities of body, mind, and spirit. Although such arts, at the basic levels, simply help a person strike or move more effectively in a fight, the higher reaches of martial-arts discipline go far beyond physical combat, into the realm of mental focus and spiritual refinement.\n\nAlthough the obvious example of self-perfection through martial arts is kung fu (roughly translated as “hard work” or “auspicious effort art”), most martial arts have esoteric elements. Renaissance fencing features philosophy, psychology, and mathematics as well as physical skill; Greek pankration emphasizes being “all powerful” in all respects; capoeira relies upon the essence of freedom as well as on the acrobatic maneuvers for which it’s famous. Advanced martial arts, therefore, nurture the spirit, hone the mind, and turn the body into a focus for the powers of each.\n\nAt their most metaphysical levels, advanced martial arts attune a practitioner into the Quintessential life force, channel it through refined motions, and grant incredible – some would say inhuman – powers through the focus of an art. The Akashic practice Do is probably the most obvious example of this practice on a metaphysical level, but any martial art – even dirty fighting – can become a magickal practice with the proper mindset and devotion.\n\nBeyond their mystic elements, martial arts are also technologies: refinements of knowledge that can be studied, repeated, and employed with practical effect. Thus, Technocrats and other technomancers can employ martial arts as a focus too. Regarding all that mystic nonsense as metaphors and mental techniques, a technomancer can divorce her martial arts training from mysticism and still retain its metaphysical potency.\n\nWith such powers, she can direct Forces, alter Life, rearrange Matter, perceive Entropy, channel Prime, enhance Time, and – perhaps most of all – refine her Mind to sublime capacity. Although she couldn’t fly through the air or skip along tree branches by manipulating chi (“That’s just mythology!”), she can still rework conventional physics and biology through her understanding of the fighting arts.",
    description_pt: "A máquina humana é um prodígio cujo vasto potencial é limitado por hábitos indisciplinados e comportamentos adquiridos. As artes marciais expandem esse potencial, desbloqueando faculdades físicas e metafísicas mais profundas de corpo, mente e espírito. Embora tais artes, em níveis básicos, simplesmente ajudem a golpear ou se mover com mais eficácia em uma luta, os patamares elevados da disciplina marcial vão muito além do combate físico, adentrando o reino do foco mental e do refinamento espiritual.\n\nEmbora o exemplo mais evidente de autoaperfeiçoamento seja o kung fu ('trabalho árduo' ou 'arte do esforço meritório'), a maioria das artes marciais possui elementos esotéricos. A esgrima renascentista envolve filosofia, psicologia e matemática além da destreza física; o pancrácio grego enfatiza ser 'todo-poderoso' em todos os aspectos; a capoeira apoia-se na essência da liberdade tanto quanto nas manobras acrobáticas pelas quais é famosa. Artes marciais avançadas, portanto, nutrem o espírito, aguçam a mente e transformam o corpo em um foco para os poderes de ambos.\n\nEm seus níveis metafísicos mais profundos, as artes marciais sintonizam o praticante com a força vital da Quintessência, canalizando-a através de movimentos refinados e concedendo poderes formidáveis — alguns diriam desumanos. A prática Akáshica do Dô é provavelmente o exemplo mais límpido disso, mas qualquer arte marcial — até mesmo a briga de rua suja — pode se tornar uma prática mágica com a mentalidade e devoção adequadas.\n\nAlém de seus elementos místicos, as artes marciais são também tecnologias: refinamentos de conhecimento que podem ser estudados, repetidos e empregados com efeito prático. Assim, Tecnocratas e outros tecnomantes também podem empregar artes marciais como foco. Encarando todo aquele misticismo como metáforas e técnicas mentais de biofeedback, a tecnomante pode dissociar seu treinamento marcial do misticismo e ainda reter sua potência metafísica.\n\nCom tais poderes, ela pode direcionar Forças, alterar a Vida, rearranjar a Matéria, perceber a Entropia, canalizar o Primórdio, acelerar o Tempo e — talvez acima de tudo — refinar sua Mente até uma capacidade sublime. Embora ela não vá sair voando pelos ares ou saltitando sobre galhos de árvores manipulando o chi ('Isso é só mitologia!'), ela ainda é capaz de reconfigurar a física e a biologia convencionais através de sua compreensão magistral das artes de combate.",
    common_instruments: &[
        "Bodywork",
        "Dance and Movement",
        "Energy (Chi/Prana)",
        "Herbs",
        "Meditation",
        "Ordeals and Exertions",
        "Symbols",
        "Wands and Staves",
        "Weapons",
        "Voice (Kiai)",
    ],
    common_instruments_pt: &[
        "Trabalho Corporal e Golpes",
        "Dança e Movimento Fluido",
        "Energia Vital (Chi / Prana)",
        "Ervas e Bálsamos Tradicionais",
        "Meditação e Centramento",
        "Ordálias e Esforço Físico Rigoroso",
        "Símbolos e Ideogramas",
        "Bastões, Bo e Varas",
        "Armas Marciais (Espadas, Nunchakus)",
        "Voz e Grito de Foco (Kiai)",
    ],
    associated_abilities: &[
        "Acrobatics",
        "Alertness",
        "Athletics",
        "Awareness",
        "Esoterica (Martial Philosophies)",
        "Etiquette",
        "Intimidation",
        "Martial Arts",
        "Medicine",
        "Meditation",
        "Melee",
    ],
    associated_abilities_pt: &[
        "Acrobacia",
        "Prontidão",
        "Esportes",
        "Consciência",
        "Esotérica (Filosofias Marciais)",
        "Etiqueta e Respeito",
        "Intimidação",
        "Artes Marciais (Dô)",
        "Medicina Tradicional",
        "Meditação",
        "Armas Brancas",
    ],
    callouts: &[],
};

// 14. Medicine Work (p. 581)
pub const MEDICINE_WORK: PracticeDefinition = PracticeDefinition {
    id: "medicine_work",
    name: "Medicine Work",
    name_pt: "Medicina Sagrada",
    aliases: &["Medicina Sagrada", "Healing Arts", "Curandeirismo", "Restoration"],
    page_ref: "M20, p. 581",
    quote: "Medicine work refers to the intent to heal and the choice of techniques that enhance healing.",
    quote_pt: "O trabalho da medicina refere-se à intenção sagrada de curar e à escolha de técnicas que promovem a restauração.",
    paradigm_affinity: &[
        "A Mechanistic Cosmos",
        "A World of Gods and Monsters",
        "Bring Back the Golden Age",
        "Creation’s Divine and Alive",
        "Divine Order and Earthly Chaos",
        "Everything is Chaos",
        "Everything’s an Illusion, Prison, or Mistake",
        "It’s All Good – Have Faith",
        "Tech Holds All Answers",
    ],
    paradigm_affinity_pt: &[
        "Um Cosmos Mecanicista",
        "Um Mundo de Deuses e Monstros",
        "Trazer de Volta a Idade de Ouro",
        "A Criação é Divina e Viva",
        "Ordem Divina e Caos Terreno",
        "Tudo é Caos",
        "Tudo é uma Ilusão, Prisão ou Erro",
        "Tudo é Bom — Tenha Fé",
        "A Tecnologia Tem Todas as Respostas",
    ],
    description: "Next to parenting, healing might be the highest human vocation. Many mages – mystics and technomancers alike – view their Enlightenment as an obligation to heal. To heal the planet, heal the people, heal the spirits, heal the Earth… perhaps all of them at once, if that’s at all possible. And so one of the oldest and most sacred Paths an Awakened person can pursue involves the practice of medicine work.\n\nSimply put, a medicine-person directs his skills and energies toward a healing practice. He might be the Progenitor physician, the Verbena root-witch, the Bata’a houngan, the Templar medic… it’s not the group that matters, or even the medical practice, when it comes to the abilities of a skillful mage. A shaman with Life 3 can fix a broken leg as well as a Progenitor with the same level of Spheres. For the purposes of magickal practice, the term medicine work refers to the intent to heal and the choice of techniques that enhance healing, not to the specific method a mage uses when healing injuries or disease.\n\nHuman medicine is an ever-evolving technology. Things we take for granted as medical facts were unknown half a century ago, whereas certain proven truths of conventional Western medicine ignore equally proven truths of alternative, non-industrialized medicines. Thanks to magick (especially the Life, Entropy, Mind, and Prime Spheres), any form of medicine can work for an Awakened healer who employs that medicine as a focus, so long as that mage BELIEVES in that form of medicine.\n\nIt’s worth mentioning that traditional Native American and African mages often abhor the idea of using magic. In many cultures, “magick” is either trickery or the influence of malignant spirits. Medicine is a more accurate and respectful term for what such people do than magick is… hence, the phrase medicine man. Many “shamans” actually consider themselves to be medicine people, using their Arts to nurture and restore the world, not to make it dance to their whims.",
    description_pt: "Ao lado da criação dos filhos, curar pode ser a mais elevada vocação humana. Muitos magos — místicos e tecnomantes da mesma forma — veem sua Iluminação como uma obrigação de curar. Curar o planeta, curar as pessoas, curar os espíritos, curar a Terra… talvez todos eles de uma vez só, se isso for minimamente possível. E assim, um dos Caminhos mais antigos e sagrados que uma pessoa Desperta pode trilhar envolve a prática do trabalho medicinal.\n\nEm termos simples, um praticante da medicina direciona suas habilidades e energias rumo a uma prática de cura. Ele pode ser o médico Progenitor, a bruxa de raízes Verbena, o houngan Bata'a, o médico socorrista Templário… não é o grupo que importa, nem mesmo a prática médica em si, quando se trata das capacidades de um mago habilidoso. Um xamã com Vida 3 pode consertar uma perna quebrada tão bem quanto um Progenitor com o mesmo nível de Esferas. Para os propósitos da prática mágica, o termo trabalho medicinal refere-se à intenção de curar e à escolha de técnicas que aprimoram a cura, e não ao método específico que um mago emprega ao tratar ferimentos ou enfermidades.\n\nA medicina humana é uma tecnologia em constante evolução. Coisas que hoje consideramos fatos médicos indiscutíveis eram desconhecidas há meio século, enquanto certas verdades comprovadas da medicina ocidental convencional ignoram verdades igualmente comprovadas de medicinas alternativas e não industrializadas. Graças à magia (especialmente as Esferas de Vida, Entropia, Mente e Primórdio), qualquer forma de medicina pode funcionar para um curador Desperto que empregue essa medicina como foco, desde que esse mago ACREDITE nessa forma de medicina.\n\nVale a pena mencionar que magos tradicionais nativos americanos e africanos frequentemente abominam a ideia de usar 'mágica'. Em muitas culturas, 'magia' é ou trapaça ou a influência de espíritos malignos. 'Medicina' é um termo muito mais preciso e respeitoso para o que essas pessoas realizam do que 'magia'… daí a expressão homem-medicina. Muitos 'xamãs' na verdade consideram a si mesmos como curandeiros e pessoas da medicina, usando suas Artes para nutrir e restaurar o mundo, e não para fazê-lo dançar conforme seus caprichos.",
    common_instruments: &[
        "Artwork & Masks",
        "Blessings and Curses",
        "Blood and Fluids",
        "Bodywork",
        "Bones and Remains",
        "Books",
        "Brews and Concoctions",
        "Computers",
        "Cups and Vessels",
        "Dance and Movement",
        "Devices and Machines",
        "Drugs and Poisons",
        "Group Rites (Operations)",
        "Herbs & Poultices",
        "Laboratories",
        "Languages (Latin & Medical Jargon)",
        "Meditation",
        "Music",
        "Offerings and Sacrifices",
        "Prayers and Invocations",
        "Social Domination",
        "Voice",
        "Weapons (Surgical Instruments)",
    ],
    common_instruments_pt: &[
        "Máscaras Rituais e Arte Sacra",
        "Bênçãos de Cura",
        "Sangue e Fluidos Vitais",
        "Massagens e Quiropraxia",
        "Ossos e Relíquias",
        "Tratados Médicos e Herbários",
        "Chás, Emplastos e Tinturas",
        "Monitores e Computadores",
        "Cálices e Bacias de Assepsia",
        "Dança Restauradora",
        "Dispositivos Médicos",
        "Remédios, Analgésicos e Soros",
        "Cirurgias e Procedimentos em Equipe",
        "Ervas Medicinais",
        "Laboratórios e Salas Cirúrgicas",
        "Latim e Terminologia Médica",
        "Meditação Terapêutica",
        "Música Suave e Sons Curativos",
        "Oferendas de Agradecimento",
        "Preces pela Saúde",
        "Autoridade Médica",
        "Voz Tranquilizadora",
        "Bisturis e Instrumentos Cirúrgicos",
    ],
    associated_abilities: &[
        "Academics (Healing Practices)",
        "Art (Masks, Dance, Music)",
        "Awareness",
        "Empathy",
        "Esoterica (Herbalism, Energy Work)",
        "Medicine",
        "Meditation",
        "Pharmacopeia",
        "Science",
        "Technology",
    ],
    associated_abilities_pt: &[
        "Acadêmicos (História da Medicina)",
        "Arte (Máscaras de Cura, Dança)",
        "Consciência / Prontidão",
        "Empatia",
        "Esotérica (Fitoterapia, Reiki, Bioenergia)",
        "Medicina",
        "Meditação",
        "Farmacopeia",
        "Ciência",
        "Tecnologia",
    ],
    callouts: &[],
};

// 15. Reality Hacking (pp. 581-582)
pub const REALITY_HACKING: PracticeDefinition = PracticeDefinition {
    id: "reality_hacking",
    name: "Reality Hacking",
    name_pt: "Hacking da Realidade",
    aliases: &["Hacking da Realidade", "System Subversion", "Meme Engineering", "Virtual Reality Arts"],
    page_ref: "M20, pp. 581-582",
    quote: "Reality is flexible. Re-contextualize reality as the Masses understand it, then take advantage of those new perceptions.",
    quote_pt: "A realidade é maleável. Recontextualize a realidade como as Massas a compreendem e tire proveito dessas novas percepções.",
    paradigm_affinity: &[
        "A Mechanistic Cosmos",
        "A World of Gods and Monsters",
        "Bring Back the Golden Age",
        "Creation’s Divine and Alive",
        "Divine Order and Earthly Chaos",
        "Everything is Chaos",
        "Everything is Data",
        "Everything’s an Illusion, Prison, or Mistake",
        "Might is Right",
        "One-Way Trip to Oblivion",
        "Tech Holds All Answers",
    ],
    paradigm_affinity_pt: &[
        "Um Cosmos Mecanicista",
        "Um Mundo de Deuses e Monstros",
        "Trazer de Volta a Idade de Ouro",
        "A Criação é Divina e Viva",
        "Ordem Divina e Caos Terreno",
        "Tudo é Caos",
        "Tudo é Informação",
        "Tudo é uma Ilusão, Prisão ou Erro",
        "O Poder Faz o Direito",
        "Viagem Sem Volta para o Esquecimento",
        "A Tecnologia Tem Todas as Respostas",
    ],
    description: "Imaginative people can do imaginative things with supposedly static structures. Hacking them apart to reconfigure those structures, these people use various tools – technology, philosophy, art, politics, and, occasionally, magick – to remake what was into what can be. With the correct gear and the right ideas, you don’t even need to be a mage in order to hack the dominant paradigm… just ask Osama bin Laden’s ghost. When you are a mage, however, you can employ those tools to remake Reality on a grand scale.\n\nTypically associated with the Virtual Adepts (and, to a lesser extent, the Cult of Ecstasy), the reality-hacking practice can be used by any mage with the proper mindset and expertise. The core idea – reality is flexible – seems familiar enough these days. As a practice, reality hacking uses an array of technologies to rework the systems that govern our world: its commerce, politics, media, memes, connections, faiths, physics, and so forth. By concentrating on specific systems and ideas, the mage can start remixing expectations into some new and interesting shape.\n\nSound like anarchy? Sometimes it is. Many of this practice’s oldest adherents and principles, however, come from the Order of Reason and Technocratic Order. After all, it was early Technocrats who hacked the human concepts of the universe, God, governments, and other technologies. Technocrats shaped fencing (a sword-fighting hack), the physical sciences (an elemental hack), exploration (a geographic hack), mass media (a consciousness hack), and the space program (a planetary hack). It’s no accident that the Virtual Adepts and Society of Ether began as Technocratic Conventions. And despite their unruly applications of technology, they’re just keeping that old hacker ethic alive.\n\nThe postmodern reality hacker tends to employ information technologies – not simply computers, but also memes, media, and other forms of mass intellectual access. Channeling her ideas and energies through computer code, social media, videos, slogans, pranks, guerilla theatre, graphic novels, music, fashions, and the clever manipulation of vibrant symbols, that mage can re-contextualize reality as the Masses understand it. It’s not as quick or gratifying as a thunderbolt, but it tends to be a hell of a lot more powerful… and more coincidental, too.\n\nLike cybernetics, dominion, and the Art of Desire (all related practices), reality hacking aims more toward influence than raw force. The reality hacker strives to modify the system to her advantage, rather than blast it apart. Even so, certain tools – like terrorism and atrocity – can be incredibly violent in both implementation and results. Even then, however, that violence serves as an extension and instrument of the hack; the power of terrorism, for example, comes more from the atmosphere of dread and fury than from the casualties themselves. Spherewise, reality hacking favors Correspondence (for drawing and exploiting connections), Entropy (for spotting flaws and arranging probabilities), Forces (directing or destroying electrical systems), Mind (influencing ideas and the folks who have them), Life (rewiring the human animal), Prime (drawing, raising, and directing energy), and Time (re-contextualizing the perceptions of time), and uses instruments that express and subvert those principles in the modern world.",
    description_pt: "Mentes inventivas conseguem realizar proezas extraordinárias sobre estruturas tidas como estáticas. Desmontando sistemas para reconfigurá-los, essas pessoas utilizam diversas ferramentas — tecnologia, filosofia, arte, política e, ocasionalmente, magia — para transformar o que era no que pode vir a ser. Com o equipamento correto e as ideias certas, você nem precisa ser um mago para hackear o paradigma dominante… basta perguntar ao fantasma de Osama bin Laden. Quando você é um mago, contudo, pode empregar essas ferramentas para reconstruir a Realidade em escala cósmica.\n\nTipicamente associada aos Adeptos da Virtualidade (e, em menor grau, ao Culto do Êxtase), a prática do hacking da realidade pode ser adotada por qualquer mago com a mentalidade e perícia adequadas. A premissa central — a realidade é flexível — soa bastante familiar nos dias de hoje. Como prática, o hacking da realidade emprega um arsenal de tecnologias para retrabalhar os sistemas que governam o nosso mundo: seu comércio, política, mídia, memes, conexões, crenças, física e assim por diante. Ao se concentrar em sistemas e ideias específicas, o mago pode começar a remixar expectativas em algum formato novo e interessante.\n\nSoa como anarquia? Às vezes é. Muitos dos adeptos e princípios mais antigos desta prática, no entanto, vêm da Ordem da Razão e da Ordem Tecnocrática. Afinal de contas, foram os primeiros Tecnocratas que hackearam as concepções humanas sobre o universo, Deus, governos e outras tecnologias. Os Tecnocratas moldaram a esgrima (um hack de combate de espadas), as ciências físicas (um hack elemental), as navegações (um hack geográfico), a mídia de massa (um hack de consciência) e o programa espacial (um hack planetário). Não é por acaso que os Adeptos da Virtualidade e os Filhos do Éter nasceram como Convenções Tecnocráticas. E, apesar de suas aplicações rebeldes da tecnologia, eles estão apenas mantendo viva aquela velha ética hacker.\n\nO hacker da realidade pós-moderno tende a empregar tecnologias de informação — não apenas computadores, mas também memes, mídia e outras formas de acesso intelectual massivo. Canalizando suas ideias e energias através de linhas de código, redes sociais, vídeos, slogans, pegadinhas, teatro de guerrilha, romances gráficos, música, moda e manipulação inteligente de símbolos vibrantes, essa maga pode recontextualizar a realidade conforme compreendida pelas Massas. Não é algo tão rápido ou gratificante quanto um raio, mas tende a ser muito mais poderoso… e mais coincidente também.\n\nAssim como a cibernética, o domínio e a Arte do Desejo (todas práticas aparentadas), o hacking da realidade visa muito mais a influência do que a força bruta. O hacker da realidade empenha-se em modificar o sistema a seu favor, em vez de simplesmente explodi-lo em pedaços. Ainda assim, certos instrumentos — como o terrorismo e a atrocidade — podem ser incrivelmente violentos tanto na execução quanto nos resultados. Mesmo nesses casos, contudo, essa violência atua como uma extensão e um instrumento do hack; o poder do terrorismo, por exemplo, provém muito mais da atmosfera de pavor e fúria do que das baixas em si. Em termos de Esferas, o hacking da realidade favorece Correspondência (para traçar e explorar conexões), Entropia (para identificar brechas e manipular probabilidades), Forças (para direcionar ou destruir sistemas elétricos), Mente (para influenciar ideias e aqueles que as têm), Vida (para religar os circuitos do animal humano), Primórdio (para extrair, elevar e direcionar energia) e Tempo (para recontextualizar percepções do tempo), e utiliza instrumentos que expressam e subvertem esses princípios no mundo moderno.",
    common_instruments: &[
        "Artwork",
        "Books",
        "Brain/Computer Interface",
        "Computers and IT Gear",
        "Devices and Machines",
        "Drugs",
        "Eye Contact",
        "Group Rites",
        "Language & Memes",
        "Mass Media",
        "Money and Wealth",
        "Music",
        "Nanotech",
        "Sex",
        "Social Domination",
        "Symbols",
        "Thought Forms",
        "Tricks and Illusions",
        "Voice",
        "Weapons",
    ],
    common_instruments_pt: &[
        "Obras de Arte e Design",
        "Livros e Manifestos",
        "Interface Cérebro/Computador",
        "Computadores e Aparelhos de TI",
        "Dispositivos Conectados",
        "Substâncias Químicas",
        "Contato Visual",
        "Flash Mobs e Ações Coletivas",
        "Linguagem de Programação e Memes",
        "Mídia de Massa e Redes Sociais",
        "Criptomoedas e Dinheiro",
        "Música Eletrônica",
        "Nanotecnologia",
        "Sexo",
        "Engenharia Social",
        "Logos e Símbolos Visuais",
        "Formas de Pensamento",
        "Pegadinhas e Hacktivismo",
        "Voz e Podcasts",
        "Armas Digitais",
    ],
    associated_abilities: &[
        "Academics (History, Philosophy, Social Sciences)",
        "Art",
        "Belief Systems",
        "Computer",
        "Expression",
        "Government",
        "Media",
        "Politics",
        "Science (Psychology & Physical)",
        "Subterfuge",
        "Technology",
    ],
    associated_abilities_pt: &[
        "Acadêmicos (História, Filosofia, Sociologia)",
        "Arte e Design Gráfico",
        "Sistemas de Crença",
        "Computador e Redes",
        "Expressão",
        "Administração Pública",
        "Mídia e Propaganda",
        "Ciência Política",
        "Ciência (Psicologia Social)",
        "Subterfúgio",
        "Tecnologia",
    ],
    callouts: &[],
};

// 16. Shamanism (pp. 582-583)
pub const SHAMANISM: PracticeDefinition = PracticeDefinition {
    id: "shamanism",
    name: "Shamanism",
    name_pt: "Xamanismo",
    aliases: &["Xamanismo", "Spirit Walking", "Animistic Arts", "Technoshamanism"],
    page_ref: "M20, pp. 582-583",
    quote: "A soul guide, a prophet, a medicine bringer and spirit warrior walking between the worlds.",
    quote_pt: "Um guia de almas, profeta, curandeiro e guerreiro espiritual que caminha entre os mundos.",
    paradigm_affinity: &[
        "A World of Gods and Monsters",
        "Bring Back the Golden Age",
        "Creation’s Divine and Alive",
        "Divine Order and Earthly Chaos",
        "Everything’s an Illusion, Prison, or Mistake",
        "It’s All Good – Have Faith!",
    ],
    paradigm_affinity_pt: &[
        "Um Mundo de Deuses e Monstros",
        "Trazer de Volta a Idade de Ouro",
        "A Criação é Divina e Viva",
        "Ordem Divina e Caos Terreno",
        "Tudo é uma Ilusão, Prisão ou Erro",
        "Tudo é Bom — Tenha Fé!",
    ],
    description: "We occupy a living world whose essence is greater and more intelligent than we recognize. Whereas common people stumble through material illusions, a shaman transcends both humanity and illusion. Moving through a world of layers and traps, he exists outside the everyday realm. And yet, through his guidance, the Sleeping People slumber more comfortably and the Awakened Ones remain more aware.\n\nPerhaps the most abused word in magic, shamanism technically refers to a specific type of Siberian spirit-worker. Over time, however, it’s come to define anyone who employs old-culture traditions to walk between the sublime world and its often ridiculous material counterpart. Dying – sometimes literally – to the life he led before he felt Called by the spirits, the shaman is reborn in a half-outcast state… mad by the standards of his previous society, yet aware of (if not always clear about) the true nature of Reality.\n\nBecause the shaman traditionally lives between the worlds of flesh and spirit, human and animal, matter and essence, sanity and dementia, conventionality and chaos, he embodies a living crossroads in which those qualities intersect. In many cases, he suffers from physical and/or psychological ailments, a wounded healer whose infirmities render him more sympathetic to other wounded souls. A shaman often depends upon other people and spiritual allies whose aid and guidance help him survive his strange existence.\n\nThanks to noble-savage nonsense, shamanism has a trippy popular image that’s deeply at odds with the earthy and often bizarre nature of the shaman himself. In reality, shamanism is a gritty, anti-orthodox vocation, filled with deliberate contradictions and slippery concepts of sanity. A shaman often inverts ideas of propriety; cross-dressing, speaking in riddles, or acting in deliberately crude or obnoxious ways in order to shake up or demolish preconceptions.\n\nAlthough shamanism favors a naturalistic viewpoint, technoshamanic practices exist in the current era. Connecting with urbanized spirits (city-souls, electronic entities, machine-spirits, and so on) – frequently through computers, fast-food offerings, consumerism cast-offs, and other postmodernist talismans – the technoshaman blends ancient awareness with current technology, acting as a vessel to distill the essence of eternity into the power of today.",
    description_pt: "Habitamos um mundo vivo cuja essência é maior e mais inteligente do que reconhecemos. Enquanto as pessoas comuns tropeçam em ilusões materiais, um xamã transcende tanto a humanidade quanto a ilusão. Movendo-se por um mundo de camadas e armadilhas, ele existe fora do reino cotidiano. E ainda assim, através de sua orientação, o Povo Adormecido descansa com mais conforto e os Despertos permanecem mais conscientes.\n\nTalvez a palavra mais deturpada na magia, xamanismo refere-se tecnicamente a um tipo específico de operador de espíritos siberiano. Com o tempo, contudo, passou a definir qualquer pessoa que empregue tradições de culturas antigas para caminhar entre o mundo sublime e sua contraparte material frequentemente absurda. Morrendo — às vezes literalmente — para a vida que levava antes de se sentir Chamado pelos espíritos, o xamã renasce em um estado semimarginal… louco para os padrões de sua sociedade anterior, mas consciente da verdadeira natureza da Realidade.\n\nComo o xamã tradicionalmente habita entre os mundos da carne e do espírito, do humano e do animal, da matéria e da essência, da sanidade e da demência, da convencionalidade e do caos, ele encarna uma encruzilhada viva onde essas qualidades se cruzam. Em muitos casos, ele sofre de enfermidades físicas e/ou psicológicas — um curador ferido cujas dores o tornam mais empático para com outras almas feridas. Um xamã frequentemente depende de outras pessoas e de aliados espirituais cujo auxílio e orientação o ajudam a sobreviver à sua estranha existência.\n\nGraças ao mito do 'bom selvagem', o xamanismo ganhou uma imagem popular romantizada que destoa profundamente da natureza crua e muitas vezes bizarra do próprio xamã. Na realidade, o xamanismo é uma vocação visceral e antiortodoxa, repleta de contradições deliberadas e conceitos escorregadios de sanidade. O xamã frequentemente inverte noções de decoro: travestindo-se de roupas do sexo oposto, falando por enigmas ou agindo de maneira intencionalmente grosseira e desagradável a fim de abalar ou demolir preconceitos.\n\nEmbora o xamanismo favoreça um ponto de vista naturalista, práticas tecnoxamânicas existem na era atual. Conectando-se com espíritos urbanos (almas de cidades, entidades eletrônicas, espíritos de máquinas e assim por diante) — frequentemente através de computadores, oferendas de fast-food, descartes do consumismo e outros talismãs pós-modernistas —, o tecnoxamã combina a percepção ancestral com a tecnologia contemporânea, atuando como um receptáculo para destilar a essência da eternidade no poder do hoje.",
    common_instruments: &[
        "Blood and Fluids",
        "Bones and Remains",
        "Computers (Technoshamanism)",
        "Dance & Trance",
        "Drugs and Concoctions",
        "Elements",
        "Herbs",
        "Household Tools",
        "Offerings and Sacrifice",
        "Ordeals",
        "Sex and Sensuality",
        "Thought Forms",
        "Toys",
        "True Names",
        "Voice (Chants & Rattles)",
        "Weapons",
    ],
    common_instruments_pt: &[
        "Sangue e Fluidos",
        "Ossos e Restos Animais",
        "Computadores (Tecnoxamanismo)",
        "Dança de Transe e Percussão",
        "Ervas Sagradas e Bebidas Xamânicas",
        "Elementos da Natureza",
        "Ervas e Defumações",
        "Ferramentas de Trabalho",
        "Oferendas e Tabaco",
        "Ordálias e Provações Físicas",
        "Sexo e Sensualidade",
        "Formas de Pensamento",
        "Chocalhos e Brinquedos Místicos",
        "Nomes Verdadeiros de Espíritos",
        "Cânticos Guturais e Voz",
        "Armas Rituais e Facas de Osso",
    ],
    associated_abilities: &[
        "Alertness",
        "Art",
        "Cosmology",
        "Enigmas",
        "Esoterica",
        "Expression",
        "Lucid Dreaming",
        "Medicine",
        "Pharmacopeia",
        "Streetwise",
        "Survival",
    ],
    associated_abilities_pt: &[
        "Prontidão",
        "Arte Tribal e Máscaras",
        "Cosmologia Espiritual",
        "Enigmas",
        "Esotérica Xamânica",
        "Expressão",
        "Sonho Lúcido",
        "Medicina Espiritual",
        "Farmacopeia Natural",
        "Manha",
        "Sobrevivência Selvagem",
    ],
    callouts: &[],
};

// 17. Voudoun (p. 583)
pub const VOUDOUN: PracticeDefinition = PracticeDefinition {
    id: "voudoun",
    name: "Voudoun",
    name_pt: "Vodu",
    aliases: &["Vodu", "Vodun", "Candomblé", "Santería", "Hoodoo", "Obeah", "Macumba"],
    page_ref: "M20, p. 583",
    quote: "Far from being distant, sublime godheads, his Loa patrons are powerful yet accessible cousins whose touch is a prayer or offering away.",
    quote_pt: "Longe de serem divindades distantes, os Loa são primos poderosos e acessíveis cujo toque está a uma prece de distância.",
    paradigm_affinity: &[
        "A World of Gods and Monsters",
        "Bring Back the Golden Age",
        "Creation’s Divine and Alive",
        "Divine Order and Earthly Chaos",
        "Everything’s an Illusion, Prison, or Mistake",
        "Might is Right",
        "One-Way Trip to Oblivion",
    ],
    paradigm_affinity_pt: &[
        "Um Mundo de Deuses e Monstros",
        "Trazer de Volta a Idade de Ouro",
        "A Criação é Divina e Viva",
        "Ordem Divina e Caos Terreno",
        "Tudo é uma Ilusão, Prisão ou Erro",
        "O Poder Faz o Direito",
        "Viagem Sem Volta para o Esquecimento",
    ],
    description: "If “shamanism” is the most abused word in magick, then Voudoun might be the most abused practice. Drawn from a fusion of Central African faiths, Native American practices, European iconography, and the humid atrocity of American slave culture, the collection of “voodoo” creeds – Macumba, Obeah, Candomblé, Voudoun, Santería, Delta and Lower Appalachian Hoodoo, the various flavors of Urban-American Voodoo, and their many offshoots – continues to command uncanny fascination in the modern world. Distorted by a combination of secrecy, poverty, racism, psychological warfare, cultural marginalization, and certain unnerving elements that actually do exist within those practices, the popular image of Voudoun magick reflects its distinctly American character.\n\nCharacterized by prayers, offerings, shrines, designs, blessings and maledictions, physical prowess, psychic awareness, bright colors, and sudden violence, Voudoun practices reflect their eclectic origins. Whereas elaborate Arts like High Ritual Magick favor wealth and perfection, Voudoun remains eminently practical. Sure, certain devotees are rich, especially these days; the practice itself, however, employs whatever resources a person has to work with. Faith and trust outweigh arcane rituals and ostentatious displays. Loyalty means more than titles or gold.\n\nBeyond those masks and secrets, our Voudoun practitioner nurtures passionate connection. Priestesses become “Mama,” and priests become “Papa.” Far from being distant, sublime godheads, his Loa patrons are powerful yet accessible cousins whose touch is a prayer or offering away. Anyone who needs a favor can come asking for it… and although the price of that favor might not be as pleasant or easy as he might have wished, it does tend to be granted in one form or another…\n\nDespite its shared roots with faith, shamanism and witchcraft, Voudoun has a distinct culture whose methods and doctrines don’t always play well with others. The Loa and related spirits certainly manifest through their human devotees, but those relationships are more familial than the ones often shared (and endured) between shamans and their spirit allies. That element of family is an essential, and typically neglected, element of the Voudoun mage’s Arts.\n\nGiven that the practice originated with family-oriented people who were severed from everything and everyone they’d known before, it’s not surprising that blood – figurative and otherwise – holds such a vital place in Voudoun lore and practice.",
    description_pt: "Se 'xamanismo' é a palavra mais deturpada na magia, então o Vodu pode muito bem ser a prática mais injustiçada. Nascido da fusão entre as fés da África Central e Ocidental, tradições indígenas americanas, a iconografia europeia e a atrocidade úmida da escravidão nas Américas, o conjunto de credos do 'vodu' — Macumba, Obeah, Candomblé, Vodun, Santería, Hoodoo do Delta e dos Montes Apalaches, e suas inúmeras ramificações urbanas — continua a exercer um fascínio desconcertante no mundo moderno. Distorcida por uma combinação de segredo, pobreza, racismo, guerra psicológica, marginalização cultural e certos elementos inquietantes que de fato existem nessas práticas, a imagem popular da magia do Vodu reflete seu caráter distintamente americano.\n\nMarcado por orações, oferendas, altares, traçados de vévés, bênçãos e maldições, vigor físico, prontidão psíquica, cores vibrantes e violência repentina, o Vodu reflete suas origens ecléticas. Enquanto Artes elaboradas como a Alta Magia Ritual favorecem a riqueza e a perfeição estética, o Vodu permanece eminentemente prático. É verdade que certos devotos são abastados, especialmente hoje em dia; a prática em si, contudo, opera com quaisquer recursos que a pessoa tenha à mão. Fé e confiança mútua superam rituais arcanos e exibições ostensivas. Lealdade vale mais do que títulos ou ouro.\n\nPara além de máscaras e segredos, o praticante de Vodu cultiva uma conexão apaixonada. Sacerdotisas tornam-se 'Mambo' ou 'Mama', e sacerdotes tornam-se 'Houngan' ou 'Papa'. Longe de serem divindades sublimes e distantes, seus patronos Loa são primos poderosos e acessíveis, cujo toque está a uma prece ou oferenda de distância. Quem precisa de um favor pode buscá-lo… e embora o preço possa não ser tão suave quanto se desejaria, ele tende a ser concedido de uma forma ou de outra.\n\nApesar de suas raízes compartilhadas com a fé, o xamanismo e a bruxaria, o Vodu possui uma cultura própria cujos métodos e doutrinas nem sempre convivem facilmente com outras práticas. Os Loa certamente se manifestam através de seus devotos humanos, mas essas relações são muito mais familiares do que as partilhadas entre xamãs e seus espíritos aliados. Esse elemento familiar é crucial e frequentemente negligenciado.\n\nDado que a prática se originou de povos profundamente voltados aos laços familiares que foram arrancados violentamente de tudo e de todos que conheciam anteriormente, não é surpreendente que o sangue — de forma figurada e literal — ocupe um lugar tão vital nas tradições e na práxis do Vodu.",
    common_instruments: &[
        "Artwork (Vévés)",
        "Blessings and Curses",
        "Blood",
        "Bones and Remains",
        "Cards and Dice",
        "Cups and Vessels",
        "Crossroads",
        "Dance and Movement",
        "Drugs and Poisons",
        "Elements",
        "Eye Contact",
        "Fashion & Colors",
        "Group Rites",
        "Herbs",
        "Household Tools",
        "Knots and Rope",
        "Languages",
        "Meditation",
        "Music & Drums",
        "Offerings and Sacrifices",
        "Prayers and Invocations",
        "Sex and Sensuality",
        "Symbols",
        "True Names",
        "Voice",
        "Wands and Staves",
        "Weapons",
        "Writing",
    ],
    common_instruments_pt: &[
        "Pontos Riscados e Vévés",
        "Bênçãos e Maledicências",
        "Sangue de Sacrifício",
        "Ossos e Relíquias",
        "Cartas e Dados",
        "Cálices e Cabaças",
        "Encruzilhadas e Limiares",
        "Dança de Roda e Transe",
        "Bebidas Rituais (Rum, Cachaça)",
        "Elementos da Natureza",
        "Olhar Firme e Conexão Espiritual",
        "Roupas Festivas e Cores dos Guias",
        "Giras e Ritos Coletivos",
        "Ervas e Banhos de Descarrego",
        "Ferramentas Cotidianas",
        "Fios de Conta e Cordas",
        "Línguas Ancestrais (Iorubá, Fon)",
        "Meditação e Transe Mediúnico",
        "Atabaques e Tambores Sagrados",
        "Oferendas e Pratos Votivos",
        "Pontos Cantados e Preces",
        "Energia Vital e Sensualidade",
        "Símbolos Sagrados",
        "Nomes Secretos dos Guias",
        "Voz e Cantigas",
        "Cajados e Guias",
        "Facas e Facões Rituais",
        "Inscrições Rituais",
    ],
    associated_abilities: &[
        "Art",
        "Athletics",
        "Awareness",
        "Belief Systems",
        "Carousing",
        "Crafts",
        "Empathy",
        "Intimidation",
        "Lucid Dreaming",
        "Medicine",
        "Meditation",
        "Streetwise",
    ],
    associated_abilities_pt: &[
        "Arte (Pontos Riscados)",
        "Esportes e Resistência",
        "Consciência Espiritual",
        "Sistemas de Crença",
        "Farra e Celebrações",
        "Ofícios Manuais",
        "Empatia",
        "Intimidação",
        "Sonho Lúcido",
        "Medicina Tradicional",
        "Meditação e Transe",
        "Manha",
    ],
    callouts: &[],
};

// 18. Weird Science (pp. 583-584)
pub const WEIRD_SCIENCE: PracticeDefinition = PracticeDefinition {
    id: "weird_science",
    name: "Weird Science",
    name_pt: "Ciência Estranha",
    aliases: &["Ciência Estranha", "Mad Science", "Inspired Science", "Etheric Engineering"],
    page_ref: "M20, pp. 583-584",
    quote: "True Science is indeed miraculous, but it’s not some kind of magic. No, not at all…",
    quote_pt: "A Verdadeira Ciência é de fato miraculosa, mas não é nenhum tipo de magia. De jeito nenhum…",
    paradigm_affinity: &[
        "A Mechanistic Cosmos",
        "Bring Back the Golden Age",
        "Divine Order and Earthly Chaos",
        "Everything is Data",
        "It’s All Good – Have Faith",
        "Might is Right",
        "Tech Holds All Answers",
    ],
    paradigm_affinity_pt: &[
        "Um Cosmos Mecanicista",
        "Trazer de Volta a Idade de Ouro",
        "Ordem Divina e Caos Terreno",
        "Tudo é Informação",
        "Tudo é Bom — Tenha Fé",
        "O Poder Faz o Direito",
        "A Tecnologia Tem Todas as Respostas",
    ],
    description: "Folks who think that “science is boring” know nothing about science. Underneath the lab coats and brain-cracking equations run currents of curious wonder. And though cold-eyed Technocrats favor a controlled approach to the Scientific Arts, certain visionaries refuse to be so confined. Would you call them mad? Perhaps… but their dedication keeps the hope of Science alive!\n\nUnlike most other technomagickal Arts, weird science isn’t based upon repeatable results. Oh, sure, the mad scientist wants to be able to craft armies of robotic servitors or fleets of dirigible warships… and he may well be able to create them too, once a favorable prototype has emerged from his laboratory. However, that Inspired Scientist (don’t call him a “mage” – that’s ridiculous!) is more engaged by the spirit of inquiry and potential than by the devotion to repeatable craftsmanship. As a consequence, his creations often feature glaring flaws and Paradoxes that will be smoothed out, of course, in later iterations… if he ever gets around to making them, that is.\n\nWeird science, by definition, defies the bounds of possibility. Its crazy ideas fuel crazy creativity. Theories that no rational scientist would entertain guide the creation of devices and creatures whose very existence violates the Consensus: jetpacks, death rays, quirky robots, outlandish vehicles, Atlantean sonic technologies, spacecraft, mechanical appendages, psychic enhancement gear, lab-grown allies, devastating war machines, and whatever other strange gadgetry a mad scientist can imagine. And yet, this isn’t some sort of “magic” – heavens, no! Every piece of odd technology depends upon theories so unconventional yet sublime that they MUST be true, if only for the sake of an imaginative universe.\n\nAs with other tech-based practices, weird science requires serious work in the lab before working results appear. An Enlightened Scientist might spend months or years honing his creation before revealing it to the world. Yet once that innovation has been achieved, he can often replicate it quickly, often with the help of skilled (if dispirited) minions. Weird science also allows the Scientist to alter tech with sudden bursts of inspiration, MacGyvering rickety inventions that last just long enough to accomplish a single task.\n\nAnd so – because he’s no sort of wizard, you imbecile! – the mad scientist needs tools and materials close at hand in order to work his wonders. True Science is indeed miraculous, but it’s not some kind of magic. No, not at all…",
    description_pt: "Quem pensa que 'ciência é tediosa' não entende absolutamente nada de ciência. Por baixo dos jalecos de laboratório e das equações de rachar o crânio correm correntes de curiosidade e assombro. E embora os Tecnocratas de olhar frio favoreçam uma abordagem estritamente controlada das Artes Científicas, certos visionários recusam-se a ser confinados dessa maneira. Você os chamaria de loucos? Talvez… mas a dedicação inabalável deles mantém viva a esperança da Ciência!\n\nAo contrário da maioria das outras Artes tecnomágicas, a ciência bizarra não se baseia em resultados repetíveis. Ah, com certeza, o cientista louco deseja ser capaz de produzir exércitos de autômatos servos ou frotas de navios de guerra dirigíveis… e ele pode muito bem ser capaz de criá-los também, assim que um protótipo favorável surgir de seu laboratório. No entanto, esse Cientista Inspirado (não o chame de 'mago' — isso é ridículo!) é muito mais motivado pelo espírito de investigação e potencial do que pela devoção ao trabalho artesanal repetível. Como consequência, suas criações frequentemente apresentam falhas gritantes e Paradoxos que serão corrigidos, é claro, em iterações futuras… se ele algum dia tiver tempo para produzi-las, claro.\n\nA ciência bizarra, por definição, desafia os limites do possível. Suas ideias malucas alimentam uma criatividade enlouquecida. Teorias que nenhum cientista racional levaria em consideração guiam a criação de aparelhos e criaturas cuja própria existência viola o Consenso: mochilas a jato, raios da morte, robôs excêntricos, veículos bizarros, tecnologias sônicas atlantes, espaçonaves, membros mecânicos, equipamentos de aprimoramento psíquico, aliados cultivados em provetas de laboratório, máquinas de guerra devastadoras e qualquer outro aparato estranho que um cientista louco consiga conceber. E, no entanto, isso não é algum tipo de 'magia' — céus, não! Cada peça dessa tecnologia singular depende de teorias tão heterodoxas e ao mesmo tempo sublimes que elas DEVEM ser verdadeiras, nem que seja apenas em benefício de um universo imaginativo.\n\nAssim como em outras práticas de base tecnológica, a ciência bizarra exige trabalho pesado no laboratório antes que resultados práticos apareçam. Um Cientista Iluminado pode passar meses ou anos refinando sua criação antes de revelá-la ao mundo. Contudo, uma vez que essa inovação foi alcançada, ele frequentemente consegue replicá-la com rapidez, muitas vezes com a ajuda de servos habilidosos (embora desanimados). A ciência bizarra também permite ao Cientista alterar a tecnologia com lampejos repentinos de inspiração, improvisando no estilo MacGyver invenções cambaleantes que duram apenas o suficiente para realizar uma única tarefa.\n\nE sendo assim — porque ele não é nenhum tipo de feiticeiro, seu imbecil! — o cientista louco precisa de ferramentas e materiais bem ao alcance das mãos para realizar seus prodígios. A Verdadeira Ciência é de fato miraculosa, mas não é nenhum tipo de magia. Não, de jeito nenhum…",
    common_instruments: &[
        "Armor",
        "Books",
        "Bones and Remains",
        "Brain/Computer Interface",
        "Celestial Alignments",
        "Computers and IT Gear",
        "Devices and Machines",
        "Elements (Aether, Phlogiston)",
        "Gadgets & Prototypes",
        "Inventions",
        "Laboratories",
        "Languages & Jargon",
        "Numbers and Numerology",
        "Toys",
        "Vehicles (Dirigibles, Ornithopters)",
        "Weapons (Death Rays, Sonic Blasters)",
        "Writing and Inscriptions",
    ],
    common_instruments_pt: &[
        "Armaduras e Exoesqueletos",
        "Tratados Científicos e Plantas",
        "Espécimes Biológicos Preservados",
        "Interface Cérebro/Computador",
        "Alinhamentos Celestes",
        "Computadores de Tubos de Vácuo",
        "Geradores e Transformadores Tesla",
        "Elementos Exóticos (Éter Luminífero, Flogisto)",
        "Aparatos Improvisados",
        "Invenções Excêntricas",
        "Laboratórios com Relâmpagos e Tubos",
        "Equações e Jargão Científico",
        "Cálculos Avançados",
        "Brinquedos Modificados",
        "Veículos (Dirigíveis, Ornitópteros)",
        "Armas Científicas (Raios Desintegradores, Canhões Sônicos)",
        "Quadros Negros Repletos de Fórmulas",
    ],
    associated_abilities: &[
        "Academics",
        "Crafts",
        "Esoterica (Disproven Scientific Theories)",
        "Energy Weapons",
        "Hypertech",
        "Research",
        "Science",
        "Technology",
    ],
    associated_abilities_pt: &[
        "Acadêmicos",
        "Ofícios Mecânicos",
        "Esotérica (Teorias Científicas do Éter)",
        "Armas de Energia",
        "Hipertecnologia",
        "Pesquisa",
        "Ciência",
        "Tecnologia",
    ],
    callouts: &[],
};

// 19. Witchcraft (pp. 584-585)
pub const WITCHCRAFT: PracticeDefinition = PracticeDefinition {
    id: "witchcraft",
    name: "Witchcraft",
    name_pt: "Bruxaria",
    aliases: &["Bruxaria", "The Old Ways", "Craft of the Wise", "Wicca", "Folk Magic"],
    page_ref: "M20, pp. 584-585",
    quote: "Nature-oriented, practical craft focused on everyday miracles and visionary craft.",
    quote_pt: "Ofício prático e voltado para a natureza, focado em milagres cotidianos e feitiçaria visionária.",
    paradigm_affinity: &[
        "A World of Gods and Monsters",
        "Bring Back the Golden Age",
        "Creation’s Divine and Alive",
        "Divine Order and Earthly Chaos",
        "Everything is Chaos",
        "Everything’s an Illusion, Prison, or Mistake",
        "It’s All Good – Have Faith",
        "Might is Right",
        "One-Way Trip to Oblivion",
    ],
    paradigm_affinity_pt: &[
        "Um Mundo de Deuses e Monstros",
        "Trazer de Volta a Idade de Ouro",
        "A Criação é Divina e Viva",
        "Ordem Divina e Caos Terreno",
        "Tudo é Caos",
        "Tudo é uma Ilusão, Prisão ou Erro",
        "Tudo é Bom — Tenha Fé",
        "O Poder Faz o Direito",
        "Viagem Sem Volta para o Esquecimento",
    ],
    description: "Witch. One of the more venomous words in the English language, the label “witch” can send a person to a hideous death. Even now, when the Burning Times seem more like myth than history, the popular imagination equates witches with warty evil hags cackling over poisonous, foul-smelling brews. Why would anyone, then, want to use something as quaintly horrific as “witchcraft”? Because those who understand it know that it works… not only as a magickal practice but also as a form of reverence for the natural world.\n\nThe equally loaded term “witchcraft” covers a lot of ground, from the diabolical maledictions of medieval legend to the reclamationist neopaganism of the modern era. As a Mage practice, however, the term refers to a nature-oriented, practical craft, as opposed to the scholastic abstractions of High Ritual Magick, alchemy, and so on. Traditional witchcraft is a folk-oriented low magick practiced by common people who need discernible results: healing, fertility, divination, luck or misfortune, prosperity, clarity, physical prowess, and intercessions between the people and their gods that are far more intimate than what can be found at the local temple.\n\nToday’s witchcraft features a postmodernist brew of traditional European wise-craft; 19th-century literary occultism and 20-century mystic fusions; pre-Christian elements from Greek, Norse, Celtic, Hindu, Slavic, Roman, Egyptian, and Mesopotamian cultures; repurposed Christian and Jewish practices; postmodernist philosophy, and New Age takes on quantum physics; mass-media iconography; and tons of pure invention. This high-eclectic synergy speaks to people on an elemental level… and yes, as a mystic practice, it’s as effective as any other tool on a mage’s workbench.\n\nIn all its forms, witchcraft has an outlaw mystique – due both to constant persecution and a defiantly sinister stance. Today’s witch might practice holistic medicine and nonviolent politics, but she still exists outside of mainstream respectability… often with a Fuck You attitude. Whatever style of witchcraft she prefers, that Art/Craft incorporates potent symbols – Old Gods, nature spirits, blades, circles, wands, robes, very dark or bright colors, occult iconography, seasons, shadows, chalices, ashes, the four Classical elements, and so on – that reach into the subconscious territory beyond a mainstream comfort zone.\n\nOur 21st-century witch might favor dark clothes, body art, and a swaggering subculture image, or cloak her Arts in a middle-class façade that conceals her elemental devotions. She could follow a strict Witch’s Rule or proclaim herself a mystic anarchist. In more or less all cases, she reveres Nature and diversity, channeling her Will through harmony with light and shadow, death and life. Though epitomized by the Verbena Tradition, she isn’t necessarily Pagan and doesn’t always wear her Art on her sleeve, so to speak. Regardless of her tools or devotions, though, her witchcraft remains eminently practical, focused on everyday miracles and visionary craft.",
    description_pt: "Bruxa. Uma das palavras mais venenosas da língua humana, o rótulo 'bruxa' pode condenar uma pessoa a uma morte horrenda. Mesmo agora, quando os Tempos das Fogueiras parecem mais mito do que história, a imaginação popular equipara bruxas a megeras malignas e verrugosas gargalhando sobre caldeirões venenosos e fétidos. Por que alguém iria querer, então, adotar algo tão pitorescamente aterrorizante quanto a 'bruxaria'? Porque aqueles que a compreendem sabem que ela funciona… não apenas como uma prática mágica, mas também como uma forma de reverência ao mundo natural.\n\nO termo igualmente carregado 'bruxaria' cobre um vasto território, desde as maldições diabólicas da lenda medieval até o neopaganismo restauracionista da era moderna. Como uma prática de Mago, contudo, o termo refere-se a um ofício prático e voltado para a natureza, em oposição às abstrações escolásticas da Alta Magia Ritual, da alquimia e afins. A bruxaria tradicional é uma baixa magia voltada para o povo, praticada por pessoas comuns que necessitam de resultados palpáveis: cura, fertilidade, adivinhação, sorte ou infortúnio, prosperidade, clareza, proeza física e intercessões entre o povo e seus deuses que são muito mais íntimas do que aquilo que se pode encontrar no templo local.\n\nA bruxaria de hoje apresenta uma mistura pós-moderna do ofício tradicional dos sábios europeus; ocultismo literário do século XIX e fusões místicas do século XX; elementos pré-cristãos das culturas grega, nórdica, celta, hindu, eslava, romana, egípcia e mesopotâmica; práticas judaico-cristãs reaproveitadas; filosofia pós-modernista e interpretações da Nova Era sobre física quântica; iconografia da mídia de massa; e toneladas de pura invenção. Essa sinergia altamente eclética fala com as pessoas em um nível primordial… e sim, como uma prática mística, é tão eficaz quanto qualquer outra ferramenta na bancada de um mago.\n\nEm todas as suas formas, a bruxaria possui uma mística fora-da-lei — devida tanto à perseguição constante quanto a uma postura desafiadoramente sinistra. A bruxa de hoje pode praticar medicina holística e política não-violenta, mas ela ainda existe fora da respeitabilidade convencional… frequentemente com uma atitude de 'Foda-se'. Qualquer que seja o estilo de bruxaria que ela prefira, essa Arte/Ofício incorpora símbolos potentes — Deuses Antigos, espíritos da natureza, lâminas, círculos, varinhas, vestes, cores muito escuras ou brilhantes, iconografia oculta, estações do ano, sombras, cálices, cinzas, os quatro elementos clássicos e assim por diante — que alcançam o território subconsciente muito além de uma zona de conforto convencional.\n\nA nossa bruxa do século XXI pode favorecer roupas escuras, modificações corporais e uma imagem rebelde de subcultura, ou camuflar suas Artes sob uma fachada de classe média que oculta suas devoções elementais. Ela pode seguir uma Regra da Bruxa estrita ou proclamar-se uma anarquista mística. Em quase todos os casos, ela reverencia a Natureza e a diversidade, canalizando sua Vontade através da harmonia com luz e sombra, morte e vida. Embora sintetizada pela Tradição Verbena, ela não é necessariamente pagã e nem sempre ostenta sua Arte aos quatro ventos, por assim dizer. No entanto, independentemente de suas ferramentas ou devoções, sua bruxaria permanece eminentemente prática, focada em milagres cotidianos e em um ofício visionário.",
    common_instruments: &[
        "Artwork",
        "Blessings and Curses",
        "Blood and Fluids",
        "Bodywork",
        "Bones and Remains",
        "Books",
        "Brews & Cauldrons",
        "Cards",
        "Celestial Alignments",
        "Circles",
        "Crossroads",
        "Cups and Vessels",
        "Dance",
        "Drugs and Poisons",
        "Elements",
        "Eye Contact",
        "Group Rites",
        "Household Tools",
        "Knots and Ropes",
        "Music",
        "Offerings",
        "Sex and Sensuality",
        "Social Domination",
        "Symbols",
        "True Names",
        "Wands and Staves",
        "Weapons (Athames)",
        "Writing and Inscriptions",
    ],
    common_instruments_pt: &[
        "Arte e Ídolos da Deusa",
        "Bênçãos e Maldições da Terra",
        "Sangue e Fluidos Corporais",
        "Trabalho Corporal e Toques",
        "Ossos e Restos de Animais",
        "Livros das Sombras",
        "Poções, Caldeirões e Infusões",
        "Cartas e Oráculos",
        "Fases da Lua e Solstícios",
        "Círculos Consagrados",
        "Encruzilhadas e Limiares Naturais",
        "Cálices e Taças Rituais",
        "Dança Extática",
        "Ervas e Venenos Vegetais",
        "Quatro Elementos Clássicos",
        "Olhar Penetrante",
        "Covens e Sabás Coletivos",
        "Vassouras e Utensílios Domésticos",
        "Cordas Trançadas e Nós Mágicos",
        "Música Ritual e Cantos",
        "Oferendas de Frutas e Flores",
        "Sexo e União Sagrada",
        "Presença Intensa",
        "Pentáculos e Símbolos Lunares",
        "Nomes Secretos",
        "Varinhas de Carvalho e Avelã",
        "Athames e Facas de Punho Negro",
        "Escritas em Runas",
    ],
    associated_abilities: &[
        "Academics",
        "Animal Kinship",
        "Art",
        "Awareness",
        "Crafts",
        "Medicine",
        "Meditation",
        "Occult",
        "Pharmacopeia",
    ],
    associated_abilities_pt: &[
        "Acadêmicos",
        "Empatia com Animais",
        "Arte e Canto",
        "Consciência / Prontidão",
        "Ofícios Manuais",
        "Medicina Natural",
        "Meditação",
        "Ocultismo",
        "Farmacopeia (Fitoterapia)",
    ],
    callouts: &[BOX_LEFT_AND_RIGHT_HAND_PATHS],
};

// 20. Yoga (pp. 585-586)
pub const YOGA: PracticeDefinition = PracticeDefinition {
    id: "yoga",
    name: "Yoga",
    name_pt: "Ioga",
    aliases: &["Ioga", "Union", "Tantra", "Vedic Discipline", "Pranayama"],
    page_ref: "M20, pp. 585-586",
    quote: "The physical body becomes a vessel for the transcendent Self. This is going to hurt. Don’t be afraid.",
    quote_pt: "O corpo físico se torna um receptáculo para o Eu transcendente. Isso vai doer. Não tenha medo.",
    paradigm_affinity: &[
        "A Mechanistic Cosmos",
        "A World of Gods and Monsters",
        "Bring Back the Golden Age",
        "Creation’s Divine and Alive",
        "Divine Order and Earthly Chaos",
        "Everything’s an Illusion, Prison, or Mistake",
        "It’s All Good – Have Faith",
        "Might is Right",
        "Tech Holds All Answers",
    ],
    paradigm_affinity_pt: &[
        "Um Cosmos Mecanicista",
        "Um Mundo de Deuses e Monstros",
        "Trazer de Volta a Idade de Ouro",
        "A Criação é Divina e Viva",
        "Ordem Divina e Caos Terreno",
        "Tudo é uma Ilusão, Prisão ou Erro",
        "Tudo é Bom — Tenha Fé",
        "O Poder Faz o Direito",
        "A Tecnologia Tem Todas as Respostas",
    ],
    description: "Beneath the popular exercise trend rests a potent metaphysical practice. Named from a Sanskrit word that means union, balance, joining, and (by extension) yoke, yoga employs mental, physical, and spiritual disciplines to refine a higher state of being. Through advanced levels of yoga, a practitioner unlocks the greatest human abilities, eventually transcending his human limits and achieving enlightenment… first temporary, and then perpetual. Dedication to yoga strips away the illusions of physical existence. In communion with Absolute Reality, the True Self – the center of consciousness (Atman or Purusha) – comes to comprehend the Unity of All.\n\nAlthough its historical origins may be disputed, yoga derives from a collection of practices rooted in the Indus-Sarasvati cultures of ancient India. Collected into the Vedas – books of knowledge – these practices and observations refined several forms of ritual, meditation, vocalization, and physical exercise, all dedicated to mending the fractured state of human existence. In the Classical Yoga period, those practices mingled with the Upanishads: scriptures of dynamic unity. Through mastery of those disciplines, an experienced yogi or yogini (male or female practitioner) can see the essential state of Reality… and can work with it as well.\n\nDetails about yoga could fill their own book. In a practical sense, though, a yoga practitioner pursues intense physical, mental, and spiritual study; combines learned wisdom with personal epiphanies; supersedes old limitations; and transforms herself into an instrument of transcendence. Through such refinement, she can attain superhuman abilities, project her consciousness outside of her body, and reveal the illusions of material reality as tricks of the mind… and, by extension, master earthly forces like gravity, time, matter, and the elements – in game terms, all of the Nine Spheres.\n\n(A related tradition of practices that often incorporate yogic disciplines is known collectively as Tantra: “weaving,” “loom,” “activity,” or “essence.” Although many devotees of one still practice the other, however, yoga and Tantra are not the same things. Both share a heritage, a dedication to transcendence of physical and mental limitations, and a view of the Whole beyond the illusions of separation. Generally, though, yoga unifies apparently separate elements into a conscious, transcendent whole, whereas Tantra accesses transcendent energies through sublimating physical reality. For obvious reasons, various mages incorporate elements of both traditions into their practices. For an example, see Lee Ann’s activities in the Prelude.)\n\nOften described as “the science of body, breath, mind, soul, and universe,” yoga can be considered a metaphysical technology. If nothing else, the physical and mental disciplines involved in yoga have proven benefits to the human organism. Thus, technomancers and even Technocrats can pursue a yoga practice, although its more esoteric levels defy pure materialism. By the early 21st century, the Technocracy has accepted the useful elements of yoga and incorporated certain aspects of yoga into its training programs.\n\n(Again, see John Courage’s remarks in the Prelude.) And so, although you won’t see Black Suits defying gravity and throwing bolts of pure Kundalini energy because of their mastery of yoga, the techniques of breathing, strength, and flexibility influence the new-millennium Technocrat’s pursuit of Life, Mind, and Prime Procedures. For traditional mystics (like Chakravanti and Sahajiya), such use of yogic discipline is anathema; for the devotees of Westernized yoga, however, that acceptance provides the punch line for a wondrous joke at the Technocracy’s expense.\n\nDespite the utility of books, scriptures, designs, and various medical and sometimes psychoactive concoctions, yoga is a largely self-contained practice. The physical body becomes a vessel for the transcendent Self. A devotee tends toward extraordinary good health and vitality, incisive perceptions, and a big-picture perspective on things. She might be capable of apparently impossible physical feats of endurance and flexibility, and she can – at advanced levels – sidestep little things like physics. The foundation of her practice, however, involves correct breathing, centered consciousness, and reaching past apparent limitations. As the guru Bikram advised his students: This is going to hurt. Don’t be afraid.",
    description_pt: "Sob a moda contemporânea de academias de ginástica repousa uma das mais profundas práticas metafísicas do mundo. Derivada de uma palavra sânscrita que significa 'união, equilíbrio e integração', a ioga emprega disciplinas físicas, respiratórias, mentais e espirituais para despertar um estado de consciência elevado. Através de níveis avançados de ioga, o praticante destranca as maiores faculdades humanas, eventualmente transcendendo seus limites mundanos e alcançando a iluminação… primeiro temporária, e depois perpétua. A dedicação à ioga desfaz as ilusões da existência física. Em comunhão com a Realidade Absoluta, o Eu Verdadeiro — o centro da consciência (Atman ou Purusha) — passa a compreender a Unidade do Todo.\n\nEmbora suas origens históricas sejam debatidas, a ioga deriva de um conjunto de práticas enraizadas nas culturas do vale do Indo-Sarasvati da Índia antiga. Coletadas nos Vedas — livros de sabedoria —, essas práticas e observações refinaram várias formas de ritual, meditação, vocalização e exercício físico, todas consagradas a curar o estado fragmentado da existência humana. No período da Ioga Clássica, essas práticas se mesclaram aos Upanixades: escrituras de unidade dinâmica. Através do domínio dessas disciplinas, um iogue experiente pode enxergar a essência da Realidade… e operar transformações sobre ela.\n\nDetalhes sobre a ioga poderiam preencher um livro próprio. Em sentido prático, a praticante de ioga persegue um estudo físico, mental e espiritual rigoroso; combina a sabedoria aprendida com epifanias pessoais; supera antigas limitações; e transforma a si mesma em um instrumento de transcendência. Por meio de tal refinamento, ela pode atingir habilidades sobre-humanas, projetar sua consciência para fora do corpo físico e desmascarar as ilusões da realidade material como truques da mente… e, por extensão, dominar forças terrenas como gravidade, tempo, matéria e os elementos — em termos de jogo, todas as Nove Esferas.\n\n(Uma tradição correlata de práticas que frequentemente incorpora disciplinas ióguicas é conhecida coletivamente como Tantra: 'tecer', 'tear', 'atividade' ou 'essência'. Embora muitos adeptos de uma também pratiquem a outra, no entanto, ioga e Tantra não são a mesma coisa. Ambas compartilham uma herança ancestral, a dedicação à transcendência das limitações físicas e mentais, e uma visão do Todo para além das ilusões da separação. De modo geral, contudo, a ioga unifica elementos aparentemente separados em um todo consciente e transcendente, enquanto o Tantra acessa energias transcendentes através da sublimação da própria realidade física. Por razões óbvias, vários magos incorporam elementos de ambas as tradições em suas práticas. Para um exemplo, veja as atividades de Lee Ann no Prelúdio.)\n\nFrequentemente descrita como 'a ciência do corpo, da respiração, da mente, da alma e do universo', a ioga pode ser considerada uma tecnologia metafísica. No mínimo, as disciplinas físicas e mentais envolvidas na ioga trazem benefícios comprovados para o organismo humano. Assim, tecnomantes e até Tecnocratas podem adotar a prática da ioga, embora seus níveis mais esotéricos desafiem o materialismo puro. No início do século XXI, a Tecnocracia aceitou os elementos úteis da ioga e incorporou certos aspectos em seus programas de treinamento.\n\n(Novamente, veja as observações de John Courage no Prelúdio.) E sendo assim, embora você não vá ver Ternos Pretos desafiando a gravidade e disparando raios de pura energia Kundalini devido ao seu domínio da ioga, as técnicas de respiração, força e flexibilidade influenciam profundamente a busca do Tecnocrata do novo milênio por Procedimentos de Vida, Mente e Primórdio. Para os místicos tradicionais (como os Chakravanti e Sahajiya), tal apropriação da disciplina ióguica é um anátema; para os adeptos da ioga ocidentalizada, contudo, essa aceitação serve como o ápice de uma piada fabulosa às custas da Tecnocracia.\n\nApesar da utilidade de livros, escrituras, diagramas e várias misturas medicinais e às vezes psicoativas, a ioga é uma prática em grande parte autossuficiente. O corpo físico torna-se um receptáculo para o Eu transcendente. Uma devota tende a desfrutar de vitalidade e saúde extraordinárias, percepções incisivas e uma visão ampla sobre as coisas. Ela pode ser capaz de feitos físicos aparentemente impossíveis de resistência e flexibilidade e pode — em níveis avançados — driblar pequenos detalhes como as leis da física. O alicerce de sua prática, no entanto, envolve respiração correta, consciência centrada e a superação de limitações aparentes. Como o guru Bikram aconselhou seus discípulos: 'Isto vai doer. Não tenham medo.'",
    common_instruments: &[
        "Bodywork & Asanas",
        "Circles and Designs (Mandalas)",
        "Dances and Movement",
        "Energy (Prana/Kundalini)",
        "Languages (Sanskrit)",
        "Meditation & Dhyana",
        "Music & Chants",
        "Ordeals & Asceticism",
        "Prayers",
        "Sex and Sensuality (Tantra)",
        "Symbols (Yantras)",
        "Thought Forms",
        "Voice (Mantras, The Om)",
        "Writings and Inscriptions",
    ],
    common_instruments_pt: &[
        "Trabalho Corporal e Ásanas",
        "Mandalas e Desenhos Geométricos",
        "Movimentos Fluidos e Posturas",
        "Energia Vital (Prana / Kundalini)",
        "Língua Sânscrita",
        "Meditação e Dhyana",
        "Cânticos e Mantras",
        "Ordálias e Ascetismo",
        "Orações e Devoção",
        "Sexo e Sensualidade Sagrada (Tantra)",
        "Yantras e Símbolos",
        "Formas de Pensamento",
        "Voz e Entonação do Om",
        "Escritas em Sânscrito",
    ],
    associated_abilities: &[
        "Athletics",
        "Awareness",
        "Enigmas",
        "Esoterica (Vedas, Upanishads, Tantra)",
        "Expression",
        "Medicine",
        "Meditation",
        "Survival",
    ],
    associated_abilities_pt: &[
        "Esportes e Flexibilidade",
        "Consciência / Prontidão",
        "Enigmas",
        "Esotérica (Vedas, Upanixades, Tantra)",
        "Expressão",
        "Medicina Ayurvédica",
        "Meditação",
        "Sobrevivência",
    ],
    callouts: &[],
};
