use super::PracticeDefinition;
use super::callouts::*;

// 1. Alchemy (pp. 573-574)
pub const ALCHEMY: PracticeDefinition = PracticeDefinition {
    id: "alchemy",
    name: "Alchemy",
    name_pt: "Alquimia",
    aliases: &["Alquimia", "Spagyrics", "Hermetic Alchemy", "Internal Alchemy (Neidan)"],
    page_ref: "M20, pp. 573-574",
    quote: "The lead is the alchemist, and the gold represents self-perfection.",
    quote_pt: "O chumbo é o próprio alquimista, e o ouro representa a auto-perfeição.",
    paradigm_affinity: &[
        "A Mechanistic Cosmos",
        "Bring Back the Golden Age",
        "Creation’s Divine and Alive",
        "Divine Order and Earthly Chaos",
        "Everything is Data",
        "Might is Right",
        "Tech Holds All Answers",
    ],
    paradigm_affinity_pt: &[
        "Um Cosmos Mecanicista",
        "Trazer de Volta a Idade de Ouro",
        "A Criação é Divina e Viva",
        "Ordem Divina e Caos Terreno",
        "Tudo é Informação",
        "O Poder Faz o Direito",
        "A Tecnologia Tem Todas as Respostas",
    ],
    description: "From turning base materials into decaying messes and then moving them upward toward eventual perfection, the ancient art of alchemy has provided the basis for modern chemistry. Wrapped in elaborate codes, symbols, and metaphors that still remain open to interpretation, this Art depends upon the idea of transformation from lower to higher states of being. The common perception of the Art rests upon its old claim of turning lead into gold; in reality, though, that claim is both metaphor and a way of scamming money to fund alchemical pursuits. Sure, a skilled alchemist might indeed use Matter magick to change lead into gold; on a deeper level, however, the lead is the alchemist and the gold represents self-perfection.\n\nAlthough its common name comes from an Arabic practice, alchemy has several different forms: the Taoist Arts of sublime energies, the medieval European “lead into gold” vocation, the Islamic refinement-of-self through the keys left by Allah in the hands of wise men, the roots of those Arts in Classical Greece and Egypt, the early forms of modern chemistry, the complex pharmacopeia of South American mystics, the postmodern psychotropic experiments of transhumanist philosopher-chemists, and probably a few more forms as well. A 21st-century alchemist might study several of these disciplines, formulating new variations on ancient principles. Alchemy, after all, focuses on learning-based perfection. The practitioner’s mind and body transform themselves through practicing the Art.\n\nAside from its chemical applications (poisons, psychoactives, explosives, and so forth), alchemy isn’t really a fighter’s Art. Its techniques demand patience, time, and a dedicated workspace. As a result, Ascension War alchemists tend to craft Wonders and compounds that come in handy when things get tense. And because it’s not really difficult to turn lead into gold if you know what you’re doing, such mages tend to be quite rich… with all the resources that wealth implies.\n\nIn all its forms, alchemy demands discipline. An alchemist studies principles, experiments with materials, deciphers codes, puzzles over symbols, works in his lab, creates useful goodies, and constantly challenges and refines himself. For him, the practical applications of alchemy – drugs, acids, and other chemical compounds; quick wits; foreign languages; and other techniques of transformation – take a back seat to the self-perfection at the core of this venerable Art.",
    description_pt: "Desde a transformação de materiais básicos em massas em decomposição e sua elevação gradual rumo à perfeição final, a antiga arte da alquimia forneceu as bases para a química moderna. Envolta em códigos elaborados, símbolos e metáforas que ainda permanecem abertos à interpretação, esta Arte depende da ideia de transformação de estados inferiores para estados superiores de existência. A percepção popular da Arte repousa sobre sua velha alegação de transformar chumbo em ouro; na realidade, contudo, essa afirmação é tanto uma metáfora quanto uma maneira de arrancar dinheiro para financiar pesquisas alquímicas. Certamente, um alquimista habilidoso pode de fato usar a magia de Matéria para transformar chumbo em ouro; em um nível mais profundo, porém, o chumbo é o próprio alquimista e o ouro representa a auto-perfeição.\n\nEmbora seu nome comum provenha de uma prática árabe, a alquimia possui várias formas distintas: as Artes Taoístas de energias sublimes, a vocação medieval europeia de 'chumbo em ouro', o refinamento interior islâmico através das chaves deixadas por Alá nas mãos de homens sábios, as raízes dessas Artes na Grécia e no Egito Clássicos, as primeiras formas da química moderna, a complexa farmacopeia dos místicos sul-americanos, os experimentos psicotrópicos pós-modernos de filósofos-químicos transumanistas e provavelmente mais algumas outras formas também. Um alquimista do século XXI pode estudar várias dessas disciplinas, formulando novas variações sobre princípios milenares. A alquimia, afinal de contas, concentra-se na perfeição baseada no aprendizado. A mente e o corpo do praticante se transformam através da prática da Arte.\n\nCom exceção de suas aplicações químicas (venenos, psicoativos, explosivos e afins), a alquimia não é exatamente a Arte de um guerreiro. Suas técnicas demandam paciência, tempo e um espaço de trabalho dedicado. Como resultado, os alquimistas da Guerra da Ascensão tendem a forjar Maravilhas e compostos que se mostram muito úteis quando a situação fica tensa. E como não é realmente difícil transformar chumbo em ouro se você souber o que está fazendo, tais magos tendem a ser bastante ricos… com todos os recursos que a riqueza implica.\n\nEm todas as suas manifestações, a alquimia exige disciplina. Um alquimista estuda princípios, faz experimentos com materiais, decifra códigos, quebra a cabeça sobre símbolos, trabalha em seu laboratório, cria itens e compostos úteis e constantemente desafia e refina a si mesmo. Para ele, as aplicações práticas da alquimia — drogas, ácidos e outros compostos químicos; raciocínio ágil; línguas estrangeiras; e outras técnicas de transformação — ficam em segundo plano diante da auto-perfeição que repousa no cerne desta venerável Arte.",
    common_instruments: &[
        "Books",
        "Brews & Potions",
        "Designs & Circles",
        "Devices",
        "Drugs",
        "Formulas",
        "Laboratories & Alembics",
    ],
    common_instruments_pt: &[
        "Livros e Manuscritos",
        "Poções e Preparados",
        "Círculos e Desenhos",
        "Dispositivos",
        "Drogas e Reagentes",
        "Fórmulas",
        "Laboratórios e Alambiques",
    ],
    associated_abilities: &[
        "Art",
        "Crafts",
        "Cryptography",
        "Enigmas",
        "Esoterica",
        "Medicine",
        "Pharmacopeia",
        "Science (Chemistry)",
    ],
    associated_abilities_pt: &[
        "Arte",
        "Ofícios",
        "Criptografia",
        "Enigmas",
        "Esotérica",
        "Medicina",
        "Farmacopeia",
        "Ciência (Química)",
    ],
    callouts: &[],
};

// 2. The Art of Desire / Hypereconomics (pp. 573-574)
pub const ART_OF_DESIRE: PracticeDefinition = PracticeDefinition {
    id: "art_of_desire",
    name: "The Art of Desire / Hypereconomics",
    name_pt: "A Arte do Desejo / Hiper-economia",
    aliases: &["Ars Cupiditae", "Arte do Desejo", "Hypereconomics", "Hiper-economia", "High Guild Arts"],
    page_ref: "M20, pp. 573-574",
    quote: "What you want, you make happen. An Art of value, drawing connections between people and places.",
    quote_pt: "O que você deseja, você torna realidade. Uma Arte de valor que conecta pessoas e lugares.",
    paradigm_affinity: &[
        "A Mechanistic Cosmos",
        "Bring Back the Golden Age",
        "Divine Order and Earthly Chaos",
        "Everything is Chaos",
        "Everything is Data",
        "Everything’s an Illusion, Prison, or Mistake",
        "Might is Right",
        "One-Way Trip to Oblivion",
        "Tech Holds All Answers",
    ],
    paradigm_affinity_pt: &[
        "Um Cosmos Mecanicista",
        "Trazer de Volta a Idade de Ouro",
        "Ordem Divina e Caos Terreno",
        "Tudo é Caos",
        "Tudo é Informação",
        "Tudo é uma Ilusão, Prisão ou Erro",
        "O Poder Faz o Direito",
        "Viagem Sem Volta para o Esquecimento",
        "A Tecnologia Tem Todas as Respostas",
    ],
    description: "Known in the Renaissance as Ars Cupiditae, the Art of Desire focuses upon achieving your desires through finding out what other people desire and then using that knowledge to enact your Will. Like alchemy (and most other forms of magick, art, and science), this discipline involves plenty of self-perfection: athletic exercise, meditation, mental gymnastics, self-reflection, etiquette, and other social graces. Fashionable clothes, subtle yet influential cosmetics, poise and grace, martial arts, seduction, intimidation, and the trappings of wealth and refinement provide essential tools for this practice. Although it’s most readily associated with the Syndicate and its original form as the High Guild, the Art of Desire has adherents throughout the mortal and Awakened worlds.\n\nEssentially, Ars Cupiditae converts desire to reality. What you want, you make happen. A devotee nurtures her desires and the desires of other people, then uses them to advance her agenda for Reality as a whole. An Art of value, this practice draws connections between people and places, reads emotions and influences thoughts, manipulates the physical and mental states of both the mage and her subjects, and directs probability and material toward a greater goal. As a result, this Art favors the Spheres of Correspondence, Entropy, Life, Matter, Mind, and Prime, using them as parts of a useful, interlocking whole.\n\nAn eminently cultured practice, Ars Cupiditae draws upon a mixture of Asian, European, and Middle Eastern social and philosophical technologies. A practitioner of Desire rarely comes across as a mage at all – she’s more Nikita than Hermione. Although certain Ecstatics and Hermetic wizards favor this approach, and modern Ngoma and Taftani use it to command urban commerce and culture, a devotee of this Art employs social influence, economic wizardry, and sheer personal excellence in order to get what she wants. Such mages rarely use violence themselves, leaving the dirty work to paid enforcers. If and when a practitioner needs to get her hands messy, though, her athletic prowess and advanced technology prove that she’s no corner-office pushover.\n\nA related practice, hypereconomics, refines the Art of Desire into social and global control. By exploring and exploiting desires and values within a given group, a hypereconomist can sense the Primal Energies of want and need within that group and then turn them to her advantage. An arcane practice understood mostly by Syndicate reps and the occasional Virtual Adept, hypereconomics provides an excellent vehicle for Entropy, Mind, and Prime Effects, channeled through social and mathematical activities so subtle that few people even recognize that their lives are being altered. Almost always coincidental (gross violations of Consensus Reality are considered cheap), hypereconomics remains a closely guarded secret in the 21st-century reality wars.",
    description_pt: "Conhecida no Renascimento como Ars Cupiditae, a Arte do Desejo concentra-se em alcançar seus desejos descobrindo o que as outras pessoas desejam e usando esse conhecimento para manifestar sua Vontade. Como a alquimia (e a maioria das outras formas de magia, arte e ciência), essa disciplina envolve farto autoaperfeiçoamento: exercícios atléticos, meditação, ginástica mental, auto-reflexão, etiqueta e outras polidezes sociais. Roupas elegantes na moda, cosméticos sutis porém influentes, porte e graça, artes marciais, sedução, intimidação e os adornos de riqueza e refinamento fornecem ferramentas essenciais para essa prática. Embora seja mais prontamente associada ao Sindicato e à sua encarnação original como a Alta Guilda, a Arte do Desejo possui adeptos por todo o mundo mortal e Desperto.\n\nEssencialmente, a Ars Cupiditae converte desejo em realidade. O que você quer, você faz acontecer. Uma devota nutre seus desejos e os desejos de outras pessoas, e então os utiliza para avançar sua agenda para a Realidade como um todo. Uma Arte de valor, essa prática estabelece conexões entre pessoas e lugares, lê emoções e influencia pensamentos, manipula os estados físicos e mentais tanto da maga quanto de seus alvos, e direciona probabilidades e matéria rumo a um objetivo maior. Como resultado, esta Arte favorece as Esferas de Correspondência, Entropia, Vida, Matéria, Mente e Primórdio, usando-as como partes de um todo útil e integrado.\n\nUma prática eminentemente culta, a Ars Cupiditae baseia-se em uma mistura de tecnologias sociais e filosóficas asiáticas, europeias e do Oriente Médio. Uma praticante do Desejo raramente se parece com um mago — ela é mais Nikita do que Hermione. Embora certos Extáticos e magos Herméticos favoreçam essa abordagem, e modernos Ngoma e Taftani a usem para dominar o comércio e a cultura urbana, uma devota desta Arte emprega influência social, genialidade econômica e pura excelência pessoal para obter o que quer. Tais magos raramente recorrem à violência pessoalmente, deixando o trabalho sujo para executores pagos. Se e quando uma praticante precisa sujar as próprias mãos, contudo, sua destreza atlética e tecnologia avançada provam que ela não é nenhuma executiva de gabinete indefesa.\n\nUma prática relacionada, a hiper-economia, refina a Arte do Desejo em direção ao controle social e global. Ao explorar e tirar proveito de desejos e valores dentro de um determinado grupo, a hiper-economista consegue pressentir as Energias Primordiais de carência e necessidade dentro desse grupo e, em seguida, usá-las a seu favor. Uma prática arcana compreendida principalmente por representantes do Sindicato e pelo ocasional Adepto da Virtualidade, a hiper-economia fornece um veículo excelente para Efeitos de Entropia, Mente e Primórdio, canalizados através de atividades sociais e matemáticas tão sutis que pouquíssimas pessoas chegam a perceber que suas vidas estão sendo alteradas. Quase sempre coincidente (violações grosseiras da Realidade do Consenso são consideradas vulgares), a hiper-economia permanece um segredo zelosamente guardado nas guerras da realidade do século XXI.",
    common_instruments: &[
        "Cards and Dice",
        "Cosmetics",
        "(Very refined) Dance and Gestures",
        "Eye Contact",
        "Fashion",
        "Gadgets",
        "Mass Media",
        "Money & Wealth",
        "Sex & Seduction",
        "Social Domination",
        "Vehicles",
        "Voice",
        "Weapons",
    ],
    common_instruments_pt: &[
        "Cartas e Dados",
        "Cosméticos",
        "Dança e Gestos (Refinados)",
        "Contato Visual",
        "Moda e Vestuário Elegante",
        "Aparatos Tecnológicos",
        "Mídia de Massa",
        "Dinheiro e Riqueza",
        "Sexo e Sedução",
        "Dominação Social",
        "Veículos de Luxo",
        "Voz e Modulação",
        "Armas",
    ],
    associated_abilities: &[
        "Academics (Culture, Philosophy, Psychology)",
        "Athletics",
        "Awareness",
        "Carousing",
        "Etiquette",
        "Expression",
        "Finance",
        "Intimidation",
        "Leadership",
        "Martial Arts",
        "Media",
        "Politics",
        "Seduction",
        "Subterfuge",
    ],
    associated_abilities_pt: &[
        "Acadêmicos (Cultura, Filosofia, Psicologia)",
        "Esportes",
        "Prontidão",
        "Farra",
        "Etiqueta",
        "Expressão",
        "Finanças",
        "Intimidação",
        "Liderança",
        "Artes Marciais",
        "Mídia",
        "Política",
        "Sedução",
        "Subterfúgio",
    ],
    callouts: &[],
};

// 3. Chaos Magick (pp. 574-575)
pub const CHAOS_MAGICK: PracticeDefinition = PracticeDefinition {
    id: "chaos_magick",
    name: "Chaos Magick",
    name_pt: "Magia do Caos",
    aliases: &["Magia do Caos", "Chaotism", "Chaosphere Arts", "Pop-Occultism"],
    page_ref: "M20, pp. 574-575",
    quote: "Each mage is a vortex of potential whose Will spins energy into being.",
    quote_pt: "Cada mago é um vórtice de potencial cuja Vontade gira a energia para a existência.",
    paradigm_affinity: &[
        "A Mechanistic Cosmos",
        "A World of Gods and Monsters",
        "Creation’s Divine and Alive",
        "Divine Order and Earthly Chaos",
        "Everything is Chaos",
        "Everything’s an Illusion, Prison, or Mistake",
        "Might is Right",
        "One-Way Trip to Oblivion",
    ],
    paradigm_affinity_pt: &[
        "Um Cosmos Mecanicista",
        "Um Mundo de Deuses e Monstros",
        "A Criação é Divina e Viva",
        "Ordem Divina e Caos Terreno",
        "Tudo é Caos",
        "Tudo é uma Ilusão, Prisão ou Erro",
        "O Poder Faz o Direito",
        "Viagem Sem Volta para o Esquecimento",
    ],
    description: "It’s not what you think it is. Although the term “chaos magic” tends to be associated with demons and evil, occultists understand chaos magick as a postmodern and often improvisational Art. Like other mystic practices, it emphasizes knowledge, reflection, and other forms of self-improvement. This revolutionary inversion of traditional mystic disciplines, however, depends upon personal intuition and interpretation; individual freedom; a deliberately iconoclastic approach; and an often subversive use of pop-culture symbols, social behaviors, and improvised designs.\n\nChaos magick spits in the face of established dogma. Often regarded by outsiders as a Left-Hand Path, it’s a sex, drugs, and rock-n-roll sort of practice, raising and directing personal energy (that is, Quintessence) through extreme experiences. Obviously, this sort of thing appeals to Cultists of Ecstasy, whose more formal practices – Tantra, vision questing, ordeals, and crazy wisdom – have been integrated into the chaos-magick potpourri. Even that diverse culture, however, is too confining for many chaos practitioners, whose embrace of the Chaosphere – the whirling fractal of absolute existence – resists confinement in any form.\n\nPlayful yet serious, each chaos-magick practice draws from the individual practitioner’s experiences and desires. Depending upon the individual practitioner, it can integrate formalized ritual or involve spontaneous improvisation… or both, or neither. Flexibility and personal investment are innate elements of the practice as a whole, often connected to psychic thought forms called egregores: concepts given reality through extensive investment of psychic energy.\n\nSome folks use toys and Tarot cards, whereas others draw sigils, craft graphic novels, run raves, stage flash mobs, and concoct elaborate pranks on society at large. Eris, Bob, the Flying Spaghetti Monster… these deities supplant the classic divinities in a chaotic pantheon whose figureheads are less concerned with worship than with inversion. Each mage, then, is a vortex of potential whose Will spins energy into being. And if this sounds too abstract to be useful, then you’re thinking about it too hard.",
    description_pt: "Não é o que você pensa que é. Embora o termo 'magia do caos' tenda a ser associado a demônios e ao mal, os ocultistas compreendem a magia do caos como uma Arte pós-moderna e frequentemente improvisada. Como outras práticas místicas, ela enfatiza o conhecimento, a reflexão e outras formas de autoaperfeiçoamento. Esta inversão revolucionária das disciplinas místicas tradicionais, no entanto, depende da intuição e interpretação pessoal; da liberdade individual; de uma abordagem deliberadamente iconoclasta; e de um uso muitas vezes subversivo de símbolos da cultura pop, comportamentos sociais e desenhos improvisados.\n\nA magia do caos cospe na cara do dogma estabelecido. Frequentemente considerada por forasteiros como um Caminho da Mão Esquerda, é um tipo de prática movida a sexo, drogas e rock-n-roll, elevando e direcionando energia pessoal (ou seja, Quintessência) através de experiências extremas. Obviamente, esse tipo de coisa atrai os Cultistas do Êxtase, cujas práticas mais formais — Tantra, buscas de visão, ordálias e sabedoria louca — foram integradas ao caldeirão da magia do caos. Mesmo essa cultura diversificada, contudo, é limitadora demais para muitos praticantes do caos, cujo abraço à Caosfera — o fractal turbilhonante da existência absoluta — resiste a qualquer tipo de confinamento.\n\nLúdica e ao mesmo tempo séria, cada prática de magia do caos bebe das experiências e desejos do praticante individual. Dependendo de quem a pratica, ela pode integrar rituais formalizados ou envolver improvisação espontânea… ou ambos, ou nenhum dos dois. Flexibilidade e investimento pessoal são elementos inatos da prática como um todo, frequentemente conectados a formas de pensamento psíquicas chamadas egrégoras: conceitos aos quais se dá realidade palpável através do investimento massivo de energia psíquica.\n\nAlguns usam brinquedos e cartas de Tarô, enquanto outros desenham sigilos, criam romances gráficos, organizam raves, realizam flash mobs e armam pegadinhas elaboradas contra a sociedade em geral. Éris, Bob, o Monstro do Espaguete Voador… essas divindades suplantam os deuses clássicos em um panteão caótico cujas figuras de proa estão menos preocupadas com adoração do que com inversão. Cada mago, portanto, é um vórtice de potencial cuja Vontade tece energia na existência. E se tudo isso soar abstrato demais para ser útil, então você está pensando a respeito com seriedade excessiva.",
    common_instruments: &[
        "Whatever works, so long as none of it becomes too stable or confining",
        "Cards and Tarot",
        "Toys and Artifacts",
        "Drugs & Entheogens",
        "Music & Raves",
        "Sigils & Graffiti",
        "Social Disruption & Pranks",
        "Thought Forms & Egregores",
    ],
    common_instruments_pt: &[
        "Qualquer coisa que funcione, contanto que nada se torne estático ou aprisionador",
        "Cartas e Tarô",
        "Brinquedos e Bonecos",
        "Drogas e Enteógenos",
        "Música e Raves",
        "Sigilos e Grafite",
        "Subversão Social e Pegadinhas",
        "Formas de Pensamento e Egrégoras",
    ],
    associated_abilities: &[
        "Art",
        "Awareness",
        "Carousing",
        "Computer",
        "Esoterica",
        "Expression",
        "Lucid Dreaming",
        "Meditation",
        "Pharmacopeia",
        "Streetwise",
        "Technology",
    ],
    associated_abilities_pt: &[
        "Arte",
        "Prontidão",
        "Farra",
        "Computador",
        "Esotérica",
        "Expressão",
        "Sonho Lúcido",
        "Meditação",
        "Farmacopeia",
        "Manha",
        "Tecnologia",
    ],
    callouts: &[BOX_LEFT_AND_RIGHT_HAND_PATHS],
};

// 4. Craftwork (pp. 574-576)
pub const CRAFTWORK: PracticeDefinition = PracticeDefinition {
    id: "craftwork",
    name: "Craftwork",
    name_pt: "Artesanato",
    aliases: &["Artesanato", "Craftsmanship", "Forging", "Masonry", "Artisan Arts"],
    page_ref: "M20, pp. 574-576",
    quote: "The heart of craftwork comes from an apparently supernatural expertise with materials and tools.",
    quote_pt: "O coração do artesanato reside em uma perícia aparentemente sobrenatural com matérias-primas e ferramentas.",
    paradigm_affinity: &[
        "A Mechanistic Cosmos",
        "A World of Gods and Monsters",
        "Bring Back the Golden Age",
        "Creation’s Divine and Alive",
        "Divine Order and Earthly Chaos",
        "Everything’s an Illusion, Prison, or Mistake",
        "It’s All Good – Have Faith",
        "Might is Right",
        "Tech Holds All Answers",
    ],
    paradigm_affinity_pt: &[
        "Um Cosmos Mecanicista",
        "Um Mundo de Deuses e Monstros",
        "Trazer de Volta a Idade de Ouro",
        "A Criação é Divina e Viva",
        "Ordem Divina e Caos Terreno",
        "Tudo é uma Ilusão, Prisão ou Erro",
        "Tudo é Bom — Tenha Fé",
        "O Poder Faz o Direito",
        "A Tecnologia Tem Todas as Respostas",
    ],
    description: "There are reasons that Hephaestus is a metalsmith, Jesus is a carpenter, and Ogun is said to be the iron “who always eats first.” It’s no accident that Freemasons remain one of the most respected yet feared societies around – a society responsible, in ways, for the foundation of the United States. Many myths peg humanity’s origins to deities who fashioned us out of clay and then breathed life into their creations. That’s because craftwork – the Art of making miracles out of raw materials – is among the first metaphysical practices.\n\nCraftwork’s mystique has been largely diminished in the industrial world… so much so that it’s often farmed out to sweatshop labor or performed by machines (which hold their own ominous metaphysical connotations – witness the Terminator and Matrix sagas). Even so, there’s something magical about that Geek Squad specialist who can fix your errant computer, the tattooed malcontent repairing your car, or that friend who forges swords or crafts costumes for the SCA. The heart of craftwork comes from an apparently supernatural expertise with materials and tools – the ability to take bits of rock or skin or tree and then make lovely, useful objects from them.\n\nMany mystics bridle at the thought of crediting craftsmanship as a magical practice. After all, the Technocracy began as a bunch of disgruntled Craftmasons who shaped the machines that ended the High Mythic Age, so why should such people be considered mages? And yet, that prejudice ignores the legendary ties between craftwork and the mystic Arts: the legacies of Solomon’s temple and the masons who built it, of the temples whose sacred geometries invited gods to dwell within them, the shapers of iron, gold, and stone who brought humanity out of caves and into cities of their own design.\n\nAs a practice, craftsmanship combines the physical and mental skills involved in various crafts (carpentry, metalsmithing, glasswork, plastics, leatherworking, and so forth), then combines them with Pattern Arts in order to make those materials better than they’d been before. Matter presents the obvious Sphere for such disciplines, but Forces, Prime, and often Life and Entropy are essential too. Old-school crafters employ Spirit to Awaken or placate the spirits within the materials.\n\nA typical crafter-mage seems rough around the edges compared to her more academic peers. Often physically strong and personally abrupt, she can be perceived as boorish and dull. That’s a common but mistaken view. In her chosen craft, this mage is every bit as sharp and knowledgeable as her book-bound contemporaries… most of whom would be lost without her expertise.\n\nAnd although common prejudices view such mages as members of the Technocracy (not without some truth), a crafter is just as likely to be a stonesmith Verbena, an ironworking Ngoma, an artisan Hermetic, or a VA computer tech. The Taftani weavers earned that name from their physical skills as well as their mystical ones, and the Ngoma preserve the practical skills as well as the magical rites from their Egyptian/ Nubian origins. Even Akashayana employ craft Arts in their martial practices – see the film The Man With the Iron Fists for several examples. Though often forgotten in the catalogs of magic, craftwork is as old as humanity yet as fresh as the laptop at your fingertips.",
    description_pt: "Há motivos pelos quais Hefesto é ferreiro, Jesus é carpinteiro e Ogum é saudado como o ferro 'que come primeiro'. Não é por acaso que os Franco-Maçons continuam sendo uma das sociedades mais respeitadas e temidas do mundo — uma ordem responsável, em muitos aspectos, pelos alicerces dos Estados Unidos. Diversos mitos fundacionais narram divindades moldando a humanidade a partir do barro para depois insuflar-lhe a vida. Isso ocorre porque o artesanato — a Arte de fazer milagres a partir da matéria-prima bruta — está entre as práticas metafísicas primordiais.\n\nO fascínio do ofício manual foi ofuscado no mundo industrializado… a ponto de ser terceirizado para galpões de trabalho escravo ou executado por máquinas (que carregam conotações metafísicas sinistras — como testemunham as sagas Exterminador do Futuro e Matrix). Mesmo assim, há algo de profundamente mágico naquele especialista em suporte que ressuscita seu computador pifado, no mecânico tatuado consertando seu carro ou naquele amigo que forja espadas e costura trajes de época. O coração do artesanato reside em uma perícia aparentemente sobrenatural com matérias-primas e ferramentas — a habilidade de transformar fragmentos de rocha, couro ou madeira em objetos admiráveis e funcionais.\n\nMuitos místicos relutam em aceitar o ofício manual como prática mágica. Afinal, a Tecnocracia começou como um grupo de Mestres Artífices dissidentes que projetaram as máquinas que deram fim à Alta Era Mítica; por que então tais artífices deveriam ser considerados magos? No entanto, esse preconceito ignora os laços lendários entre o trabalho manual e as Artes místicas: o legado do templo de Salomão e dos maçons que o ergueram, os templos cujas geometrias sagradas convidavam deuses a habitar neles, e os forjadores de ferro, ouro e pedra que tiraram a humanidade das cavernas e a guiaram até cidades de seu próprio projeto.\n\nComo prática, o artesanato combina as habilidades físicas e mentais envolvidas em vários ofícios (carpintaria, metalurgia, vidraria, plásticos, couro e assim por diante), unindo-as com as Artes dos Padrões para tornar esses materiais melhores do que eram antes. Matéria é a Esfera evidente para tais disciplinas, mas Forças, Primórdio e frequentemente Vida e Entropia também são essenciais. Artífices tradicionalistas empregam Espírito para Despertar ou apaziguar a essência espiritual que habita os materiais.\n\nUma maga artífice típica parece rústica se comparada aos seus pares mais acadêmicos. Frequentemente forte fisicamente e de modos diretos, ela pode ser vista como rude e sem graça. Essa é uma impressão comum, mas completamente equivocada. Em seu ofício escolhido, essa maga é tão arguta e instruída quanto seus contemporâneos presos a livros… a maioria dos quais estaria perdida sem a perícia dela.\n\nE embora preconceitos comuns vejam tais magos como membros da Tecnocracia (não sem certa parcela de verdade), um artífice tem tantas chances de ser um entalhador de pedras Verbena, um ferreiro Ngoma, um artesão Hermético ou um técnico em informática Adepto da Virtualidade. Os tecelões Taftani ganharam esse nome tanto por suas habilidades físicas quanto místicas, e os Ngoma preservam técnicas práticas bem como os ritos mágicos de suas origens egípcias/núbias. Até mesmo os Akashayana empregam Artes de artífice em suas práticas marciais — veja o filme O Homem com Punhos de Ferro para diversos exemplos. Embora muitas vezes esquecido nos catálogos de magia, o ofício manual é tão antigo quanto a humanidade e, no entanto, tão atual quanto o laptop sob as pontas dos seus dedos.",
    common_instruments: &[
        "Artwork",
        "Blood",
        "Books",
        "Computers and IT Gear",
        "Devices and Machines",
        "Elements",
        "Gadgets",
        "Household and Crafting Tools",
        "Laboratories and Workshops",
        "Symbols",
        "Weapons (Hammers, Blades, Sickles, Guns)",
    ],
    common_instruments_pt: &[
        "Obras de Arte",
        "Sangue",
        "Livros Técnicos",
        "Computadores e Equipamentos de TI",
        "Dispositivos e Máquinas",
        "Elementos (Fogo, Ar, Terra)",
        "Aparatos",
        "Ferramentas Manuais e de Oficina",
        "Laboratórios e Forjas",
        "Símbolos e Marcas de Artífice",
        "Armas (Martelos, Lâminas, Foices)",
    ],
    associated_abilities: &[
        "Academics",
        "Arts",
        "Computers",
        "Crafts",
        "Energy Weapons",
        "Esoterica (Sacred Geometry, Stone and Metal Lore)",
        "Hypertech",
        "Research",
        "Science",
        "Technology",
    ],
    associated_abilities_pt: &[
        "Acadêmicos",
        "Artes",
        "Computadores",
        "Ofícios",
        "Armas de Energia",
        "Esotérica (Geometria Sagrada, Metalurgia)",
        "Hipertecnologia",
        "Pesquisa",
        "Ciência",
        "Tecnologia",
    ],
    callouts: &[],
};

// 5. Crazy Wisdom (p. 576)
pub const CRAZY_WISDOM: PracticeDefinition = PracticeDefinition {
    id: "crazy_wisdom",
    name: "Crazy Wisdom",
    name_pt: "Sabedoria Louca",
    aliases: &["Sabedoria Louca", "Antinomian Praxis", "Holy Madness", "Divine Folly"],
    page_ref: "M20, p. 576",
    quote: "Deliberately irrational activities that grant wisdom by shattering established concepts of what is real.",
    quote_pt: "Atividades deliberadamente irracionais que concedem sabedoria ao despedaçar noções prévias da realidade.",
    paradigm_affinity: &[
        "A World of Gods and Monsters",
        "Creation’s Divine and Alive",
        "Divine Order and Earthly Chaos",
        "Everything is Chaos",
        "Everything’s an Illusion, Prison, or Mistake",
        "It’s All Good – Have Faith",
        "One-Way Trip to Oblivion",
    ],
    paradigm_affinity_pt: &[
        "Um Mundo de Deuses e Monstros",
        "A Criação é Divina e Viva",
        "Ordem Divina e Caos Terreno",
        "Tudo é Caos",
        "Tudo é uma Ilusão, Prisão ou Erro",
        "Tudo é Bom — Tenha Fé",
        "Viagem Sem Volta para o Esquecimento",
    ],
    description: "A mage who gets a little bit out of her head when performing magick might use what’s often called the crazy wisdom practice: deliberately irrational activities that supposedly grant wisdom by shattering established concepts of what is and is not possible and real.\n\nAnother sex, drugs, and rock-n-roll approach to magick, crazy wisdom often involves psychoactive entheogens, trance-inducing music, vision quests, risky ordeals, sexual excess, gender inversions, social misrule, mass ecstatic rituals, and solitary isolation in which the practitioner turns her own personal reality inside out and then ponders what that means. Although it’s technically undisciplined by the standards of more rigid forms of magick, such behavior provides a potent tool for enlightenment… assuming it doesn’t kill you first!\n\nAlthough its obvious adherents come from the Cult of Ecstasy, crazy wisdom has a long and respected history as part of shamanism, voodoo, witchcraft, and even certain High Ritual practices. The Order of Hermes has its own variation – the Antinomian Praxis – in which a mage smashes taboos, violates her own standards, and breaks through constraints to find what lies beyond them. Drawing strength from its obvious contradictions, crazy wisdom is dangerous, disruptive, often scary, and potentially lethal. That’s kind of the point, though danger isn’t always involved. Mystic contraries and genderqueers, who deliberately invert social expectations about identity and gender, practice a form of crazy wisdom on a social scale, fucking with people’s preconceptions in order to show greater possibilities.\n\nThis is the Trickster’s Path, breaking on through like Jim Morrison in a mosh pit with Patti Smith, Br’er Rabbit, the Cat in the Hat, and several buckets of paint.",
    description_pt: "Uma maga que se desprende das amarras da sanidade comum ao realizar seus efeitos mágicos pode estar empregando a prática da sabedoria louca: atividades intencionalmente irracionais que concedem iluminação ao despedaçar noções prévias sobre o que é ou não possível e real.\n\nOutra abordagem do tipo 'sexo, drogas e rock-and-roll' para a magia, a sabedoria louca frequentemente envolve enteógenos psicoativos, músicas indutoras de transe, buscas de visão, ordálias arriscadas, transbordamento sensorial, inversões de gênero, desordem social, rituais extáticos coletivos e isolamento solitário no qual a praticante vira sua própria realidade do avesso para ponderar o que isso significa. Embora seja tecnicamente indisciplinada para os padrões de formas mais rígidas de magia, essa conduta oferece uma ferramenta formidável para a iluminação… supondo que ela não mate você antes!\n\nEmbora seus adeptos mais óbvios pertençam ao Culto do Êxtase, a sabedoria louca possui uma longa e respeitada história no xamanismo, no vodu, na bruxaria e até mesmo em certas práticas de Alta Magia Ritual. A Ordem de Hermes possui sua própria variação — a Práxis Antinomiana —, na qual o mago quebra tabus, viola seus próprios padrões morais e rompe amarras para descobrir o que reside além delas. Extraindo força de suas evidentes contradições, a sabedoria louca é perigosa, perturbadora, muitas vezes aterrorizante e potencialmente letal. Esse é o cerne da questão, embora o perigo nem sempre seja obrigatório. Contrários místicos e indivíduos genderqueer, que invertem deliberadamente as expectativas sociais sobre identidade e gênero, praticam uma forma de sabedoria louca em escala social, confrontando os preconceitos das pessoas para descortinar possibilidades maiores.\n\nEste é o Caminho do Trapaceiro (Trickster), irrompendo pelas portas da percepção como Jim Morrison em uma roda de mosh com Patti Smith, o Coelho Quincas, o Gato de Cartola e vários baldes de tinta.",
    common_instruments: &[
        "Blood and Body Fluids",
        "Bones and Remains",
        "Brain/Computer Interface",
        "Dance & Movement",
        "Drugs & Entheogens",
        "Music",
        "Ordeals & Extreme Sensations",
        "Sex and Sensuality",
        "Social Domination & Misrule",
        "Thought Forms",
        "Toys",
        "Tricks and Illusions",
        "Voice & Glossolalia",
    ],
    common_instruments_pt: &[
        "Sangue e Fluidos Corporais",
        "Ossos e Restos Mortais",
        "Interface Cérebro/Computador",
        "Dança e Transe",
        "Drogas e Enteógenos",
        "Música Hipnótica",
        "Ordálias e Provações Físicas",
        "Sexo e Sensualidade",
        "Desordem Social e Inversões",
        "Formas de Pensamento",
        "Brinquedos e Truques",
        "Ilusões e Máscaras",
        "Voz e Glossolalia",
    ],
    associated_abilities: &[
        "Art",
        "Athletics",
        "Carousing",
        "Esoterica",
        "Lucid Dreaming",
        "Meditation",
        "Pharmacopeia",
        "Survival",
    ],
    associated_abilities_pt: &[
        "Arte",
        "Esportes",
        "Farra",
        "Esotérica",
        "Sonho Lúcido",
        "Meditação",
        "Farmacopeia",
        "Sobrevivência",
    ],
    callouts: &[BOX_LEFT_AND_RIGHT_HAND_PATHS],
};

// 6. Cybernetics (pp. 576-577)
pub const CYBERNETICS: PracticeDefinition = PracticeDefinition {
    id: "cybernetics",
    name: "Cybernetics",
    name_pt: "Cibernética",
    aliases: &["Cibernética", "Bionics", "Biomechanical Engineering", "Systemic Control"],
    page_ref: "M20, pp. 576-577",
    quote: "Creation as a vast machine whose systems can be understood and manipulated with sufficient dedication.",
    quote_pt: "A Criação como uma vasta máquina cujos sistemas podem ser compreendidos e manipulados com dedicação.",
    paradigm_affinity: &[
        "A Mechanistic Cosmos",
        "Everything is Data",
        "Everything’s an Illusion, Prison, or Mistake",
        "Might is Right",
        "One-Way Trip to Oblivion",
        "Tech Holds All Answers",
    ],
    paradigm_affinity_pt: &[
        "Um Cosmos Mecanicista",
        "Tudo é Informação",
        "Tudo é uma Ilusão, Prisão ou Erro",
        "O Poder Faz o Direito",
        "Viagem Sem Volta para o Esquecimento",
        "A Tecnologia Tem Todas as Respostas",
    ],
    description: "When organic machines get wedded to mechanical machines, the synergy called cybernetics raises the human animal to a whole new level. On a broader plane, cybernetics reaches beyond mere flesh and machine to embrace the technologies of communication, language, electrical impulses, complex systems, and thought itself. Drawn from a Greek phrase meaning “to steer or govern,” cybernetic practices employ complex interactive systems – computers, electronics, prosthetics, mathematical formulae, linguistics, philosophy, even social dynamics – to extend the practitioner’s control… first over his own reality, and then over the reality of other systems and entities.\n\nEssentially, the cybernetic practice views Creation as a vast machine whose systems can be understood and manipulated with sufficient dedication. For many adherents – like the members of Iteration X – that dedication includes merging their bodies with mechanical components. Other practitioners, though, use cybernetics as a theoretical construct – a model through which calculations, psychology, symbols, and external devices and machines (as opposed to implanted ones) can bend probability (through Entropy), change minds (the Mind Sphere), transform materials (Life and Matter), channel energies (Forces and Prime), and redefine temporal physics… or, in plain English, reroute Time.\n\nDespite the dated overuse of “cyber” as an adjective, cybernetics remains a bleeding-edge discipline. Rooted in Chinese, Greek, and Arab technologies, this discipline blossomed during the Industrial Revolution and hasn’t stopped blooming yet. In the 21st century, whole nations are composed of cyborgs – smart-phone-using, video-watching, TV-nurtured, socially networked machine-people whose relationships and realities are defined by the 24/7 interface of our Information Era.\n\nAnd although the science-fiction landscape of depersonalized drones looks nothing like the world as we know it now, every element of life in our new millennium depends upon a complex interplay of cybernetic forces that very few people truly understand… and that even fewer – aside from certain technomancers – can control.",
    description_pt: "Quando máquinas orgânicas se unem a máquinas mecânicas, a sinergia chamada cibernética eleva o animal humano a um patamar inteiramente novo. Em um plano mais amplo, a cibernética vai além da mera carne e máquina para abraçar as tecnologias de comunicação, linguagem, impulsos elétricos, sistemas complexos e o próprio pensamento. Derivada de uma palavra grega que significa 'governar ou pilotar', as práticas cibernéticas empregam sistemas interativos complexos — computadores, eletrônica, próteses, fórmulas matemáticas, linguística, filosofia e até mesmo dinâmica social — para estender o controle do praticante… primeiro sobre sua própria realidade, e depois sobre a realidade de outros sistemas e entidades.\n\nEssencialmente, a prática cibernética enxerga a Criação como uma vasta máquina cujos sistemas podem ser compreendidos e manipulados com dedicação suficiente. Para muitos adeptos — como os membros da Iteração X —, essa dedicação inclui fundir seus próprios corpos com componentes mecânicos. Outros praticantes, contudo, usam a cibernética como um construto teórico — um modelo através do qual cálculos, psicologia, símbolos e dispositivos e máquinas externos (em oposição aos implantados) podem dobrar probabilidades (através de Entropia), alterar mentes (a Esfera da Mente), transformar matérias (Vida e Matéria), canalizar energias (Forças e Primórdio) e redefinir a física temporal… ou, em bom português, redirecionar o Tempo.\n\nApesar do uso desgastado do prefixo 'ciber' como adjetivo, a cibernética permanece uma disciplina de vanguarda absoluta. Enraizada em tecnologias chinesas, gregas e árabes, esta disciplina floresceu durante a Revolução Industrial e não parou de florescer até hoje. No século XXI, nações inteiras são compostas por ciborgues — pessoas-máquinas conectadas 24 horas por dia, 7 dias por semana, usando smartphones, assistindo a vídeos, alimentadas pela TV e pelas redes sociais, cujas relações e realidades são definidas pela interface contínua da nossa Era da Informação.\n\nE embora o cenário de ficção científica repleto de drones despersonalizados não se pareça em nada com o mundo como o conhecemos agora, cada elemento da vida em nosso novo milênio depende de uma interação complexa de forças cibernéticas que pouquíssimas pessoas compreendem de verdade… e que menos pessoas ainda — com exceção de certos tecnomantes — são capazes de controlar.",
    common_instruments: &[
        "Books",
        "Brain/Computer Interface",
        "Computers and IT Gear",
        "Devices and Machines",
        "Gadgets & Inventions",
        "Laboratories",
        "Languages & Protocols",
        "Mass Media",
        "Nanotech",
        "Numbers and Numerology",
        "Weapons",
        "Writing and Inscriptions",
    ],
    common_instruments_pt: &[
        "Livros e Manuais Técnicos",
        "Interface Cérebro/Computador (Cyberware)",
        "Computadores e Equipamentos de TI",
        "Dispositivos e Máquinas",
        "Aparatos e Próteses Biomecânicas",
        "Laboratórios de Montagem",
        "Linguagens de Código e Protocolos",
        "Mídia de Massa",
        "Nanotecnologia",
        "Números e Algoritmos",
        "Armas Integradas",
        "Escritas e Inscrições",
    ],
    associated_abilities: &[
        "Academics",
        "Biotech",
        "Computer",
        "Crafts",
        "Energy Weapons",
        "Hypertech",
        "Media",
        "Politics",
        "Science",
        "Technology",
    ],
    associated_abilities_pt: &[
        "Acadêmicos",
        "Biotecnologia",
        "Computador",
        "Ofícios",
        "Armas de Energia",
        "Hipertecnologia",
        "Mídia",
        "Política",
        "Ciência",
        "Tecnologia",
    ],
    callouts: &[],
};

// 7. Dominion (p. 577)
pub const DOMINION: PracticeDefinition = PracticeDefinition {
    id: "dominion",
    name: "Dominion",
    name_pt: "Domínio",
    aliases: &["Domínio", "Social Command", "Leadership Authority", "The Art of Kings"],
    page_ref: "M20, p. 577",
    quote: "You command Reality because you believe you do, and you make other folks believe you do as well.",
    quote_pt: "Você comanda a Realidade porque acredita que comanda, e faz os outros acreditarem nisso também.",
    paradigm_affinity: &[
        "A Mechanistic Cosmos",
        "A World of Gods and Monsters",
        "Bring Back the Golden Age",
        "Divine Order and Earthly Chaos",
        "Everything is Chaos",
        "Might is Right",
        "One-Way Trip to Oblivion",
        "Tech Holds All Answers",
    ],
    paradigm_affinity_pt: &[
        "Um Cosmos Mecanicista",
        "Um Mundo de Deuses e Monstros",
        "Trazer de Volta a Idade de Ouro",
        "Ordem Divina e Caos Terreno",
        "Tudo é Caos",
        "O Poder Faz o Direito",
        "Viagem Sem Volta para o Esquecimento",
        "A Tecnologia Tem Todas as Respostas",
    ],
    description: "Social domination might just be the oldest form of magick. At its most basic levels, this practice directs animal instincts and human interactions toward the will (and Will) of the dominant party. Although other practices – notably Ars Cupiditae, shamanism, and High Ritual Magick – draw upon these techniques of domination, a raw assertion of command is the foundation of capital-A Authority… most notably among the New World Order.\n\nRarely considered “magick” in the usual sense, the dominion practice employs inner discipline, social control, a cultivated understanding of behavior and governance, significant words and symbols, the trappings of power and authority, and a host of verbal and physical tricks that keep the practitioner on top of a given situation. At its lowest form, it’s the art of the abuser, con-man, and pick-up artist. On a metaphysical level, dominion taps into the primal need for leadership and parenting, then directs that need with a conscious eye toward overwhelming control. Through that control, in turn, you command Reality because you believe you do, and you make other folks believe you do as well.\n\nA serious practitioner of dominion goes beyond crude intimidation, studying the deeper applications of social domination and self-perfection. Like a devotee of desire, he learns how to maximize his personal strengths and minimize his social flaws while taking full advantage of another party’s weaknesses and appealing to their need to be protected and led. Like Ars Cupiditae concentrates upon desire, the discipline of dominion concentrates upon command.\n\nThe techniques can seem rather arcane, especially when they’re combined with religious and/ or philosophical beliefs; it’s through technology, however, that dominion finds its greatest influence. Queen Victoria was a master of this Art… and though she used technological instruments to get her point across, she exerted such a charismatic mystique that we still use her name to define the age she ruled.\n\nSkilled dominion practitioners employ eye contact, body language, vocal tactics, peer pressure, social appeal, and resonant symbols (uniforms, weapons, parental behavior, religious iconography) in order to cow their herd. From there, these alphas enact their Will in both a mundane and Awakened sense. Lots of mages use social techniques, but a dominion master takes them to a metaphysical extent, wresting control of Reality itself through mass domination – an Art of Kings that has shaped past history and continues to do so today.",
    description_pt: "A dominação social pode muito bem ser a forma mais antiga de magia. Em seus níveis mais primordiais, esta prática direciona instintos animais e interações humanas rumo à vontade (e à Vontade) da parte dominante. Embora outras práticas — notadamente a Ars Cupiditae, o xamanismo e a Alta Magia Ritual — utilizem-se dessas técnicas de dominação, uma pura afirmação de comando é o alicerce da Autoridade com 'A' maiúsculo… mais notadamente entre a Nova Ordem Mundial.\n\nRaramente considerada 'magia' no sentido usual, a prática do domínio emprega disciplina interior, controle social, uma compreensão cultivada do comportamento e da governança, palavras e símbolos marcantes, os adornos de poder e autoridade e uma miríade de truques verbais e físicos que mantêm o praticante no comando de qualquer situação. Em sua forma mais rasteira, é a arte do abusador, do vigarista e do conquistador de ocasião. Em um nível metafísico, o domínio conecta-se à necessidade primordial por liderança e tutela paterna, direcionando essa carência com foco consciente rumo ao controle avassalador. Por meio desse controle, por sua vez, você comanda a Realidade porque acredita que a comanda, e faz com que as outras pessoas acreditem nisso também.\n\nUm praticante sério do domínio vai além da intimidação grosseira, estudando as aplicações mais profundas da dominação social e do autoaperfeiçoamento. Como um devoto do desejo, ele aprende a maximizar suas forças pessoais e a minimizar suas falhas sociais, ao mesmo tempo em que tira proveito máximo das fraquezas alheias e apela para a necessidade delas de serem protegidas e conduzidas. Assim como a Ars Cupiditae se concentra no desejo, a disciplina do domínio concentra-se no comando.\n\nAs técnicas podem parecer bastante arcanas, especialmente quando combinadas com crenças religiosas e/ou filosóficas; é através da tecnologia, contudo, que o domínio encontra sua maior influência. A Rainha Vitória foi uma mestra desta Arte… e embora tenha usado instrumentos tecnológicos para impor sua vontade, ela exercia uma mística carismática tão poderosa que ainda usamos seu nome para definir a era em que governou.\n\nPraticantes habilidosos de domínio empregam contato visual, linguagem corporal, táticas vocais, pressão dos pares, apelo social e símbolos ressonantes (uniformes, armas, postura paternalista, iconografia religiosa) a fim de subjugar seu rebanho. A partir daí, esses alfas manifestam sua Vontade tanto em sentido mundano quanto Desperto. Muitos magos usam técnicas sociais, mas um mestre do domínio as eleva a um patamar metafísico, arrancando o controle da própria Realidade através da dominação em massa — uma Arte dos Reis que moldou a história do passado e continua a fazê-lo hoje.",
    common_instruments: &[
        "Art",
        "Brain/Computer Interface",
        "Eye Contact & Gaze",
        "Fashion & Uniforms",
        "Group Rites",
        "Languages & Directives",
        "Mass Media",
        "Music",
        "Social Domination",
        "Symbols of Authority",
        "Thought Forms",
        "Tricks and Illusions",
        "Voice",
    ],
    common_instruments_pt: &[
        "Arte e Retratos",
        "Interface Cérebro/Computador",
        "Contato Visual e Olhar Fixo",
        "Moda, Ternos e Uniformes de Autoridade",
        "Ritos em Grupo e Desfiles",
        "Linguagens e Diretrizes Formais",
        "Mídia de Massa",
        "Música Marcial ou Hipnótica",
        "Dominação Social",
        "Símbolos e Insígnias de Poder",
        "Formas de Pensamento",
        "Truques Psicológicos e Ilusões",
        "Voz e Entonação de Comando",
    ],
    associated_abilities: &[
        "Academics (History, Psychology)",
        "Art",
        "Belief Systems",
        "Empathy",
        "Expression",
        "Intimidation",
        "Leadership",
        "Media",
        "Politics",
        "Seduction",
        "Technology",
    ],
    associated_abilities_pt: &[
        "Acadêmicos (História, Psicologia)",
        "Arte",
        "Sistemas de Crença",
        "Empatia",
        "Expressão",
        "Intimidação",
        "Liderança",
        "Mídia",
        "Política",
        "Sedução",
        "Tecnologia",
    ],
    callouts: &[],
};

// 8. Faith (pp. 577-578)
pub const FAITH: PracticeDefinition = PracticeDefinition {
    id: "faith",
    name: "Faith",
    name_pt: "Fé",
    aliases: &["Fé", "Devotion", "Divine Submission", "Theurgy of the Faithful"],
    page_ref: "M20, pp. 577-578",
    quote: "Through faith, all things are possible. The faithful mage says: THY Will be done.",
    quote_pt: "Através da fé, todas as coisas são possíveis. O mago fiel diz: Seja feita a TUA Vontade.",
    paradigm_affinity: &[
        "A World of Gods and Monsters",
        "Bring Back the Golden Age",
        "Creation’s Divine and Alive",
        "Divine Order and Earthly Chaos",
        "Everything’s an Illusion, Prison, or Mistake",
        "It’s All Good – Have Faith!",
    ],
    paradigm_affinity_pt: &[
        "Um Mundo de Deuses e Monstros",
        "Trazer de Volta a Idade de Ouro",
        "A Criação é Divina e Viva",
        "Ordem Divina e Caos Terreno",
        "Tudo é uma Ilusão, Prisão ou Erro",
        "Tudo é Bom — Tenha Fé!",
    ],
    description: "Through faith, all things are possible. This saying underscores the essence of what might be the most common mystic practice in the world: devotion to a higher source. Drawn from the Latin word fides – “loyalty, trust, belief” – faith provides the foundation for many other practices, yet it stands as a practice in its own right. For although witches, shamans, Voudoun practitioners, and even scientists might be faithful to their higher power, faith itself provides comfort and power for those who believe.\n\nOften regarded as the core of overtly religious sects like the Celestial Chorus and Ahl-i-Batin, faith can inspire and energize any mage. Even the demonic Nephandi maintain faith in their horrific Absolute or the Infernal entities they adore. Faith, you see, provides the believer with stability and purpose. And although magick is often seen as an egotistical practice, faith ideally removes the ego in favor of that greater Source. The faithful mage says “THY Will be done,” then acts as an instrument for that Divine Will.\n\nFor a mage of faith, the actions she takes and the Arts she pursues all represent the ideals of her higher power. In most cases, those ideals come through a religion – a binding that unites Divinity with the people of the faith. Not all faithful people, though, are religious; strictly speaking, religion is a social institution, whereas faith is a personal connection. Even science – often seen these days as an enemy of faith – can be a devotional practice. The foundations of modern science, historically, were laid by men and women of faith who used their discoveries to delve into, and then to reveal, the glories of their God.\n\nA faithful magus follows the tenets of her creed, maintains contact with her source through prayer, and acts – as often as possible – as an emissary of her creed’s ideals. “Keeping the faith” means pursuing virtues that supposedly please the higher power, and although the particulars depend upon the specific creed (a Franciscan Catholic, a Shi’a devotee, and an Odinist spá-kona all have very different ideas about virtue!), the mage’s adherence to that creed is essential. “Faith” does, after all, mean loyalty.",
    description_pt: "Através da fé, todas as coisas são possíveis. Esse provérbio sublinha a essência daquela que talvez seja a prática mística mais comum no mundo: a devoção a uma fonte superior. Derivada da palavra latina fides — 'lealdade, confiança, crença' —, a fé fornece o alicerce para muitas outras práticas, mas ergue-se como uma prática por direito próprio. Pois embora bruxas, xamãs, praticantes de Vodu e até cientistas possam ser fiéis ao seu poder superior, a fé em si mesma proporciona conforto e poder àqueles que creem.\n\nFrequentemente considerada o cerne de seitas abertamente religiosas como o Coro Celestial e os Ahl-i-Batin, a fé pode inspirar e energizar qualquer mago. Até mesmo os demoníacos Nefandi mantêm fé em seu terrível Absoluto ou nas entidades infernais que adoram. A fé, veja bem, fornece ao crente estabilidade e propósito. E embora a magia seja frequentemente vista como uma prática egoísta, a fé idealmente remove o ego em favor daquela Fonte maior. O mago fiel diz: 'Seja feita a TUA Vontade', e então age como um instrumento para essa Vontade Divina.\n\nPara uma maga de fé, as ações que ela realiza e as Artes que persegue representam todas os ideais de seu poder superior. Na maioria dos casos, esses ideais vêm através de uma religião — um elo que une a Divindade ao povo da fé. Nem todas as pessoas fiéis, contudo, são religiosas; a rigor, religião é uma instituição social, enquanto a fé é uma conexão pessoal. Até mesmo a ciência — frequentemente vista hoje em dia como inimiga da fé — pode ser uma prática devocional. As bases da ciência moderna, historicamente, foram assentadas por homens e mulheres de fé que usaram suas descobertas para mergulhar e então revelar as glórias de seu Deus.\n\nUma maga fiel segue os preceitos de seu credo, mantém contato com sua fonte por meio da oração e atua — o mais frequentemente possível — como uma emissária dos ideais de seu credo. 'Manter a fé' significa buscar virtudes que supostamente comprazem o poder superior; e embora os detalhes dependam do credo específico (um católico franciscano, um devoto xiita e uma spá-kona odinista têm ideias muito diferentes sobre virtude!), a adesão da maga a esse credo é essencial. 'Fé', afinal de contas, significa lealdade.",
    common_instruments: &[
        "Blessings and Curses",
        "Books (Scriptures)",
        "Cups and Vessels",
        "Energy",
        "Food and Drink (Communion)",
        "Group Rites",
        "Music & Chants",
        "Offerings and Sacrifice",
        "Ordeals and Exertions",
        "Prayers and Invocations",
        "Sacred Iconography",
        "Symbols",
        "Thought Forms",
        "Voice",
        "Writings and Inscriptions",
    ],
    common_instruments_pt: &[
        "Bênçãos e Maldições",
        "Livros e Escrituras Sagradas",
        "Cálices e Vasos Sagrados",
        "Energia Divina",
        "Alimento e Bebida (Comunhão)",
        "Ritos e Cultos em Grupo",
        "Música Sacra e Cânticos",
        "Oferendas e Sacrifícios",
        "Ordálias e Penitências",
        "Orações e Invocações",
        "Iconografia Sagrada e Relíquias",
        "Símbolos de Fé",
        "Formas de Pensamento",
        "Voz e Sermões",
        "Escritas e Inscrições Sagradas",
    ],
    associated_abilities: &[
        "Academics (Tenets of Faith)",
        "Awareness",
        "Belief Systems",
        "Cosmology",
        "Empathy",
        "Enigmas",
        "Esoterica",
        "Expression",
        "Medicine",
    ],
    associated_abilities_pt: &[
        "Acadêmicos (Doutrinas de Fé)",
        "Consciência / Prontidão",
        "Sistemas de Crença",
        "Cosmologia",
        "Empatia",
        "Enigmas",
        "Esotérica",
        "Expressão",
        "Medicina",
    ],
    callouts: &[],
};

// 9. Gutter Magick (p. 578)
pub const GUTTER_MAGICK: PracticeDefinition = PracticeDefinition {
    id: "gutter_magick",
    name: "Gutter Magick",
    name_pt: "Magia de Sarjeta",
    aliases: &["Magia de Sarjeta", "Street Sorcery", "Junk Magick", "Low Art of Making Do"],
    page_ref: "M20, p. 578",
    quote: "The craft of making do. Gutter magick proves you don’t need high wizardry to get attention from the spirits.",
    quote_pt: "A arte do improviso. A magia de sarjeta prova que você não precisa de alta feitiçaria para chamar a atenção dos espíritos.",
    paradigm_affinity: &[
        "A World of Gods and Monsters",
        "Creation’s Divine and Alive",
        "Divine Order and Earthly Chaos",
        "Everything is Chaos",
        "Everything’s an Illusion, Prison, or Mistake",
        "It’s All Good – Have Faith",
        "Might is Right",
        "One-Way Trip to Oblivion",
    ],
    paradigm_affinity_pt: &[
        "Um Mundo de Deuses e Monstros",
        "A Criação é Divina e Viva",
        "Ordem Divina e Caos Terreno",
        "Tudo é Caos",
        "Tudo é uma Ilusão, Prisão ou Erro",
        "Tudo é Bom — Tenha Fé",
        "O Poder Faz o Direito",
        "Viagem Sem Volta para o Esquecimento",
    ],
    description: "The most practical magick practice is the one that uses whatever you’ve got to work with. Sure, wizards and cyborgs and Enlightened tycoons can afford all the best ritual gear around. What happens, though, when you’re more or less broke? Homeless, maybe? Living in a squat or stuck on the street or getting by as part of the working poor? Well then, you use gutter magick, the craft of making do.\n\nComposed of odds and ends with symbolic connotations, gutter magick features coins, cards, toys, scraps, bottles, cans, nails, junk, graffiti, and things crafted out of the cast-offs of consumer society. Dead TVs, old magazines, cardboard boxes, gnawed chicken bones, sacrificed rats and alley cats, old clothes repurposed and restyled with feral urban flair… such instruments direct the Will of the truly destitute. On the next rung up the socioeconomic ladder, lower-class mages use cheap tricks, cheesy clothes, New Age books, action figures, and other tokens of postmodern mall-magic. When invested with Awakened intentions, these otherwise useless trinkets provide focus for orphans, Hollowers, and other mystics with more ambition than resources.\n\nAs with many other mystic practices, art forms a potent force in gutter magick. Hip-hop culture, Gothic rock, the various flavors of heavy metal, the blues, neotribal, techno-industrial, and even country/western music styles provide soundtracks for the mystic side of the urban scene. Inside the clubs, dancing and drugs create hypnotic atmospheres in which it often seems like anything could happen. A paranormal survival tactic, gutter magick skulks in the shadows of the alley between respectability and forbidden Arts.\n\nGutter magick proves that you don’t need high wizardry and ancient tomes in order to get attention (if not necessarily respect) from the spirit world. In its darker elements, such magick employs guns, blades, cheap sex and cheaper booze, crimes and punishments, madness and desperation. Though not exactly new in form, it’s a common practice in the new millennium.",
    description_pt: "A prática mágica mais prática é aquela que utiliza tudo o que você tem à mão para trabalhar. Claro, magos herméticos, ciborgues e magnatas Iluminados podem pagar pelos melhores apetrechos rituais existentes. O que acontece, no entanto, quando você está mais ou menos quebrado? Sem teto, talvez? Vivendo em uma ocupação, ou preso na rua, ou sobrevivendo como parte dos trabalhadores pobres? Bem, então você usa a magia de sarjeta: a arte do improviso.\n\nComposta de sobras e quinquilharias com conotações simbólicas, a magia de sarjeta apresenta moedas, cartas, brinquedos, retalhos, garrafas, latas, pregos, lixo, grafites e objetos forjados a partir dos descartes da sociedade de consumo. Televisores queimados, revistas velhas, caixas de papelão, ossos de galinha roídos, ratos e gatos de rua sacrificados, roupas velhas reaproveitadas e estilizadas com um toque urbano selvagem… tais instrumentos direcionam a Vontade dos verdadeiramente despossuídos. No degrau seguinte da escada socioeconômica, magos de classe baixa usam truques baratos, roupas bregas, livros de Nova Era, bonecos de ação e outros amuletos da magia de shopping pós-moderna. Quando investidos de intenções Despertas, esses bibelôs que de outro modo seriam inúteis fornecem foco para Órfãos, Vazios e outros místicos com mais ambição do que recursos.\n\nAssim como em muitas outras práticas místicas, a arte constitui uma força potente na magia de sarjeta. A cultura hip-hop, o rock gótico, as várias vertentes do heavy metal, o blues, estilos neotribais, tecno-industriais e até mesmo country/western fornecem trilhas sonoras para o lado místico da cena urbana. Dentro dos clubes, a dança e as drogas criam atmosferas hipnóticas nas quais frequentemente parece que qualquer coisa poderia acontecer. Uma tática de sobrevivência paranormal, a magia de sarjeta espreita nas sombras do beco entre a respeitabilidade e as Artes proibidas.\n\nA magia de sarjeta prova que você não precisa de alta feitiçaria nem de tomos arcanos a fim de obter atenção (se não necessariamente respeito) do mundo espiritual. Em seus elementos mais sombrios, tal magia emprega armas de fogo, lâminas, sexo barato e bebida ainda mais barata, crimes e punições, loucura e desespero. Embora não seja exatamente inovadora em sua forma, é uma prática comum no novo milênio.",
    common_instruments: &[
        "Artwork & Graffiti",
        "Blood and Fluids",
        "Bones and Remains (Cast-offs)",
        "Cards and Dice",
        "Dance",
        "Drugs and Poisons",
        "Eye Contact",
        "Fashion (Feral Urban Flair)",
        "Herbs and Plants (Weeds)",
        "Household Tools & Scraps",
        "Music",
        "Offerings and Sacrifice",
        "Sex",
        "Social Domination",
        "Symbols",
        "Thought Forms",
        "Toys & Action Figures",
        "Tricks and Illusions",
        "Weapons",
        "Vehicles",
    ],
    common_instruments_pt: &[
        "Grafite e Murais Urbanos",
        "Sangue e Fluidos",
        "Ossos e Restos Mortais (Descartes)",
        "Cartas e Dados Baratos",
        "Dança de Rua",
        "Drogas e Bebidas Baratas",
        "Contato Visual Desafiador",
        "Moda Urbana Marginal",
        "Ervas Daninhas e Matas de Asfalto",
        "Ferramentas Domésticas e Sucata",
        "Música de Subúrbio",
        "Oferendas de Sarjeta",
        "Sexo",
        "Intimidação Social",
        "Pichações e Símbolos",
        "Formas de Pensamento",
        "Brinquedos e Bonecos Usados",
        "Truques e Trapaças",
        "Armas Improvisadas",
        "Veículos Velhos",
    ],
    associated_abilities: &[
        "Animal Kinship (Rats, Cats, Crows)",
        "Area Knowledge",
        "Art",
        "Crafts",
        "Expression",
        "Firearms",
        "Intimidation",
        "Pharmacopeia",
        "Streetwise",
        "Survival (Urban)",
        "Technology",
    ],
    associated_abilities_pt: &[
        "Empatia com Animais (Ratos, Gatos, Corvos)",
        "Conhecimento de Área",
        "Arte e Grafite",
        "Ofícios Improvisados",
        "Expressão",
        "Armas de Fogo",
        "Intimidação",
        "Farmacopeia das Ruas",
        "Manha",
        "Sobrevivência Urbana",
        "Tecnologia",
    ],
    callouts: &[BOX_LEFT_AND_RIGHT_HAND_PATHS],
};

// 10. High Ritual Magick (pp. 578-579)
pub const HIGH_RITUAL_MAGICK: PracticeDefinition = PracticeDefinition {
    id: "high_ritual_magick",
    name: "High Ritual Magick",
    name_pt: "Alta Magia Ritual",
    aliases: &["Alta Magia", "Alta Magia Ritual", "Ceremonial Magick", "Hermetic Arts", "The Great Work"],
    page_ref: "M20, pp. 578-579",
    quote: "To achieve excellence, one must have perfection. To work one’s Will, one must master that Will.",
    quote_pt: "Para alcançar a excelência, é preciso perfeição. Para impor sua Vontade, deve-se dominar essa Vontade.",
    paradigm_affinity: &[
        "A Mechanistic Cosmos",
        "A World of Gods and Monsters",
        "Bring Back the Golden Age",
        "Divine Order and Earthly Chaos",
        "Everything is Data",
        "Everything’s an Illusion, Prison, or Mistake",
        "Might is Right",
        "Tech Holds All Answers",
    ],
    paradigm_affinity_pt: &[
        "Um Cosmos Mecanicista",
        "Um Mundo de Deuses e Monstros",
        "Trazer de Volta a Idade de Ouro",
        "Ordem Divina e Caos Terreno",
        "Tudo é Informação",
        "Tudo é uma Ilusão, Prisão ou Erro",
        "O Poder Faz o Direito",
        "A Tecnologia Tem Todas as Respostas",
    ],
    description: "To achieve excellence, one must have perfection. To work one’s Will, one must have the discipline to master that Will and then direct it with utmost confidence. In an outsider’s perspective, the rigorous devotees of High Ritual Magick (all capitalized) are a pretentious pack of OCD pricks. For those devotees, however, the truth is plain: you must be strong, courageous, disciplined, and wise to unlock Creation’s power. High Ritual Magick demands those qualities.\n\nIn High Ritual Magick, everything has significance: the alignment of planets, the tone of words, the calculations necessary to discover the correct number of times to repeat certain phrases, the formalities of address, and the measure or angle of materials aligned just so for maximum effect. That precision has a dual purpose: in one regard, the relationship of those many elements is crucial for success. In the other regard, the precision tests and challenges the magician, forcing him to overcome his flaws and become the superior person whom such intricacies demand. This practice is both an Art and a Science whose expertise has withstood the tests of time.\n\n(This mindset also explains the condescending attitude for which High Ritual Magicians are so infamous. Although they don’t all feel this way, many such wizards believe that other practitioners have not earned the right to work True Magick. Lesser mages, to them, are like drunken kids speeding down dark mountain roads with Daddy’s car, an expired learner’s permit, and the wizard strapped in the back seat, unable to avoid the coming crash.)\n\nThough often associated with medieval Europe, High Ritual Magick has many forms, all of them refined by civilized urban cultures. China’s ritual magick boasts Confucian complexity, and rites from Egypt and Mesopotamia provide the centerpiece for the Western occult traditions of Greece, Rome, Persia, Israel, and Arabia. Nubia’s ritual Arts remain a closely guarded secret, held by the Ngoma as a timeless inheritance. In all forms, High Ritual Magick demands preparation, discipline, and the finest materials a magician can acquire.\n\nDespite all those trappings, an accomplished Ritual Magus understands that it is his Will that commands those elements. He does not hope or beg – he commands. Spirits can be bargained with, dragons might be conjured, God Himself might slip the mage a favor, but in the end all of those parties respect the High Magus because, ultimately, he has shaped himself into the true instrument of Will.",
    description_pt: "Para alcançar a excelência, é preciso buscar a perfeição. Para manifestar a Vontade, é preciso dominar essa Vontade com disciplina férrea e dirigi-la com máxima convicção. Na perspectiva de quem está de fora, os rigorosos adeptos da Alta Magia Ritualística (tudo em maiúsculas) parecem um bando pretensioso e obsessivo. Para esses devotos, contudo, a verdade é cristalina: é preciso ser forte, corajoso, disciplinado e sábio para destrancar o poder da Criação. A Alta Magia Ritual exige essas qualidades.\n\nNa Alta Magia Ritualística, cada elemento possui significado: o alinhamento dos planetas, o tom exato das palavras, os cálculos necessários para descobrir o número correto de repetições de certas frases, as formalidades de tratamento e a medida ou ângulo de cada material posicionado para o efeito máximo. Essa precisão tem um propósito duplo: por um lado, o relacionamento de todos esses elementos é crucial para o sucesso; por outro lado, a precisão testa e desafia o mago, forçando-o a superar suas imperfeições e a se tornar a pessoa superior que tais complexidades exigem. Esta prática é tanto uma Arte quanto uma Ciência cuja maestria resistiu ao teste dos séculos.\n\n(Essa mentalidade também explica a postura condescendente pela qual os Magos de Alta Magia Ritualística são tão infames. Embora nem todos sintam o mesmo, muitos desses magos acreditam que outros praticantes não conquistaram o direito de operar a Verdadeira Magia. Magos menores, para eles, são como jovens embriagados acelerando por estradas montanhosas escuras no carro do papai, com uma permissão de dirigir vencida e com o próprio mago amarrado no banco de trás, impotente para evitar o desastre iminente.)\n\nEmbora frequentemente associada à Europa medieval, a Alta Magia Ritual possui muitas formas, todas refinadas por culturas urbanas civilizadas. A magia ritual da China ostenta complexidade confuciana, e ritos do Egito e da Mesopotâmia formam a pedra angular das tradições ocultas ocidentais da Grécia, Roma, Pérsia, Israel e Arábia. As Artes rituais da Núbia permanecem um segredo zelosamente guardado, preservado pelos Ngoma como herança atemporal. Em todas as suas formas, a Alta Magia Ritual exige preparação, disciplina e os materiais mais nobres que um mago possa adquirir.\n\nApesar de toda essa pompa cerimonial, um Alto Mago realizado compreende que é a sua Vontade que comanda esses elementos. Ele não espera nem implora — ele comanda. Pode-se negociar com espíritos, dragões podem ser conjurados, o próprio Deus pode conceder um favor ao mago, mas no fim todas essas entidades respeitam o Alto Mago porque, em última análise, ele moldou a si mesmo como o verdadeiro instrumento da Vontade.",
    common_instruments: &[
        "Books & Grimoires",
        "Celestial Alignments",
        "Circles and Designs",
        "Computers (Modern Wizards)",
        "Cups and Vessels",
        "Elements",
        "Eye Contact",
        "Fashion & Robes",
        "Gems",
        "Gestures",
        "Languages (Latin, Sanskrit, Enochian, Greek)",
        "Meditation",
        "Numbers and Numerology",
        "Offerings and Sacrifices",
        "Prayer and Invocations",
        "Social Domination",
        "Symbols",
        "Thought Forms",
        "True Names",
        "Wands and Staves",
        "Weapons (Swords and Athames)",
        "Writing and Inscriptions",
    ],
    common_instruments_pt: &[
        "Livros e Grimórios Rituais",
        "Alinhamentos Celestes e Efemérides",
        "Círculos Mágicos e Triângulos de Arte",
        "Computadores (Magos Herméticos Modernos)",
        "Cálices e Recipientes Sagrados",
        "Elementos Puros",
        "Olhar Firme e Solene",
        "Túnicas e Vestes Consagradas",
        "Gemas e Metais Nobres",
        "Gestos Rituais Precisos",
        "Línguas Sagradas (Latim, Enoquiano, Hebraico, Grego)",
        "Meditação e Foco",
        "Números e Numerologia Sagrada",
        "Oferendas e Libações",
        "Orações e Invocações Solenes",
        "Postura de Autoridade Mágica",
        "Símbolos e Selos Salomônicos",
        "Formas de Pensamento",
        "Nomes Verdadeiros",
        "Varinhas e Cajados de Poder",
        "Armas Rituais (Espadas e Athames)",
        "Escritas e Inscrições Consagradas",
    ],
    associated_abilities: &[
        "Academics",
        "Belief Systems",
        "Cosmology",
        "Crafts",
        "Expression",
        "Esoterica",
        "Investigation",
        "Leadership",
        "Meditation",
        "Occult",
        "Research",
    ],
    associated_abilities_pt: &[
        "Acadêmicos",
        "Sistemas de Crença",
        "Cosmologia",
        "Ofícios",
        "Expressão",
        "Esotérica",
        "Investigação",
        "Liderança",
        "Meditação",
        "Ocultismo",
        "Pesquisa",
    ],
    callouts: &[],
};
