//! M20 Dados Canônicos das Esferas da Mágika.
//!
//! M20 Capítulo 10: O Livro das Esferas (pp. 504-534).

use super::models::{SphereDefinition, SphereRank, SphereTheoryArticle};
pub const CORRESPONDENCE: SphereDefinition = SphereDefinition {
    id: "correspondence",
    name: "Correspondence",
    name_pt: "Correspondência",
    subtitle: "Mastery of Space and Distance",
    subtitle_pt: "Domínio do Espaço e da Distância",
    page_ref: "M20, pp. 512-513",
    specialties: "Apportation, Bi-location, Scrying, Spatial Folding, Teleportation, Ward",
    specialties_pt: "Aporte, Bilocação, Clarividência, Dobra Espacial, Teletransporte, Proteção Mágika",
    description: "Distance is an illusion. Space is a matter of perception. To the initiate of Correspondence, all things exist in a single, unified point. Through this understanding, a mage bends the continuum of space to her will, perceiving and acting across impossible distances.",
    description_pt: "A distância é uma ilusão. O espaço é uma questão de percepção. Para o iniciado da Correspondência, todas as coisas coexistem em um único ponto unificado. Através desta compreensão, a maga curva o contínuo do espaço à sua vontade, percebendo e agindo através de distâncias impossíveis.",
    ranks: &[
        SphereRank {
            rank: 1,
            name: "Spatial Perceptions",
            name_pt: "Percepções Espaciais",
            description: "Judge distance, orientation, and spatial anomalies with pinpoint precision. Gauge degrees of connection.",
            description_pt: "Calcula distâncias, orientação e anomalias espaciais com precisão milimétrica. Avalia graus de conexão.",
        },
        SphereRank {
            rank: 2,
            name: "Sense Space / Line of Sight",
            name_pt: "Sentir o Espaço / Linha de Visão",
            description: "Cast senses elsewhere without physically moving. Perceive through another location as if present.",
            description_pt: "Projeta sentidos para outro local sem se mover fisicamente. Percebe através de outro ponto como se estivesse presente.",
        },
        SphereRank {
            rank: 3,
            name: "Pierce Space / Seal Space",
            name_pt: "Perfurar o Espaço / Selar o Espaço",
            description: "Step across space, opening tiny portals or snatching small items across distances (apportation).",
            description_pt: "Corta o tecido do espaço, abrindo pequenos portais ou puxando pequenos objetos através de distâncias (aporte).",
        },
        SphereRank {
            rank: 4,
            name: "Rend Space / Dimensional Cohabitation",
            name_pt: "Rasgar o Espaço / Coabitação Dimensional",
            description: "Open wide portals for groups, stand in multiple places at once, or fold space dramatically.",
            description_pt: "Abre portais amplos para grupos, manifesta-se em múltiplos locais simultaneamente ou dobra o espaço drasticamente.",
        },
        SphereRank {
            rank: 5,
            name: "Mutate Space / Co-locality",
            name_pt: "Mutar o Espaço / Colocalidade",
            description: "Bend, distort, or stack physical space into impossible shapes. Overlap multiple locations into one.",
            description_pt: "Dobra, distorce ou empilha o espaço físico em configurações impossíveis. Sobrepõe múltiplos locais em um só.",
        },
    ],
    technocracy_equivalent: Some("Data"),
    technocracy_equivalent_pt: Some("Dados"),
    mystic_equivalent: None,
    mystic_equivalent_pt: None,
    is_optional_rule: false,
};

pub const ENTROPY: SphereDefinition = SphereDefinition {
    id: "entropy",
    name: "Entropy",
    name_pt: "Entropia",
    subtitle: "Fate, Fortune, and Decay",
    subtitle_pt: "Destino, Fortuna e Decaimento",
    page_ref: "M20, pp. 514-515",
    specialties: "Chaos, Decay, Fate, Fortune, Order, Probability, Rot",
    specialties_pt: "Caos, Decaimento, Destino, Sorte, Ordem, Probabilidade, Putrefação",
    description: "All things end, all systems degrade, and all events are governed by probability and fate. The master of Entropy steers the roll of the dice, foresees the breaking points of objects and souls, and speeds or halts decay.",
    description_pt: "Todas as coisas chegam ao fim, todos os sistemas se degradam e todos os eventos são regidos pela probabilidade e pelo destino. O mestre da Entropia comanda o rolar dos dados, prevê os pontos de ruptura de objetos e almas, e acelera ou suspende a decomposição.",
    ranks: &[
        SphereRank {
            rank: 1,
            name: "Sense Fate & Fortune",
            name_pt: "Sentir Destino & Fortuna",
            description: "Spot flaws, weaknesses, and probabilities. See who is favored by luck and who is marked for doom.",
            description_pt: "Detecta falhas, fraquezas e probabilidades. Vê quem é favorecido pela sorte e quem está marcado pela desgraça.",
        },
        SphereRank {
            rank: 2,
            name: "Control Probability",
            name_pt: "Controlar Probabilidade",
            description: "Nudge minor chance events in one's favor — coin tosses, traffic lights, glancing blows, lucky breaks.",
            description_pt: "Manipula pequenos eventos de sorte a seu favor — lançamentos de moedas, semáforos, golpes de raspão, golpes de sorte.",
        },
        SphereRank {
            rank: 3,
            name: "Degrade Matter",
            name_pt: "Degradar a Matéria",
            description: "Ruin inanimate objects through spontaneous rust, rot, mechanical jams, and systemic failure.",
            description_pt: "Arruína objetos inanimados através de ferrugem espontânea, podridão, travamentos mecânicos e colapso de sistemas.",
        },
        SphereRank {
            rank: 4,
            name: "Blight Life",
            name_pt: "Definhar a Vida",
            description: "Direct the forces of decay into living flesh — aging tissue, triggering disease, and inflicting lethal wounds.",
            description_pt: "Direciona as forças da decomposição para tecidos vivos — envelhecendo células, ativando doenças e infligindo ferimentos letais.",
        },
        SphereRank {
            rank: 5,
            name: "Mutate Thought / Binding Oath",
            name_pt: "Mutar Pensamento / Juramento Vinculante",
            description: "Erode ideas, paradigms, and sanity. Forge absolute oaths bound by cosmic karmic retribution.",
            description_pt: "Erode ideias, paradigmas e sanidade. Forja juramentos absolutos selados por retribuição cármica cósmica.",
        },
    ],
    technocracy_equivalent: None,
    technocracy_equivalent_pt: None,
    mystic_equivalent: None,
    mystic_equivalent_pt: None,
    is_optional_rule: false,
};

pub const FORCES: SphereDefinition = SphereDefinition {
    id: "forces",
    name: "Forces",
    name_pt: "Forças",
    subtitle: "Command of Energies and Dynamics",
    subtitle_pt: "Comando de Energias e Dinâmicas",
    page_ref: "M20, pp. 515-516",
    specialties: "Electricity, Fire, Gravity, Kinetic Energy, Light, Sound, Radiation",
    specialties_pt: "Eletricidade, Fogo, Gravidade, Energia Cinética, Luz, Som, Radiação",
    description: "Forces governs the primal dynamics of energy — light, sound, fire, gravity, kinetic impact, and nuclear power. It is the most visibly explosive and destructive of the Spheres, commanding the raw physical energies of the cosmos.",
    description_pt: "Forças governa as dinâmicas primordiais de energia — luz, som, fogo, gravidade, impacto cinético e potência nuclear. É a mais visivelmente explosiva e destrutiva das Esferas, comandando as energias físicas brutas do cosmos.",
    ranks: &[
        SphereRank {
            rank: 1,
            name: "Perceive Forces",
            name_pt: "Perceber Forças",
            description: "Sense energy spectra beyond human vision — infrared, ultraviolet, radio waves, electrical currents, and kinetic forces.",
            description_pt: "Percebe espectros de energia além da visão humana — infravermelho, ultravioleta, ondas de rádio, correntes elétricas e vetores cinéticos.",
        },
        SphereRank {
            rank: 2,
            name: "Control Minor Forces",
            name_pt: "Controlar Forças Menores",
            description: "Redirect, bend, or silence existing energies: snuff out a candle, bend light for camouflage, damp sound.",
            description_pt: "Redireciona, curva ou silencia energias existentes: apaga uma vela, curva a luz para camuflagem, amortece sons.",
        },
        SphereRank {
            rank: 3,
            name: "Transmute / Conjure Minor Forces",
            name_pt: "Transmutar / Conjurar Forças Menores",
            description: "Summon energy out of apparent nothingness or convert one energy into another: light into fire, sound into kinetic shock.",
            description_pt: "Conjura energia a partir do nada aparente ou converte uma forma de energia em outra: luz em fogo, som em choque cinético.",
        },
        SphereRank {
            rank: 4,
            name: "Control Major Forces",
            name_pt: "Controlar Forças Maiores",
            description: "Manipulate large-scale energetic phenomena: redirect lightning, deflect storms, manipulate localized gravity.",
            description_pt: "Manipula fenômenos energéticos de grande escala: redireciona relâmpagos, desvia tempestades, altera gravidade localizada.",
        },
        SphereRank {
            rank: 5,
            name: "Transmute / Conjure Major Forces",
            name_pt: "Transmutar / Conjurar Forças Maiores",
            description: "Unleash devastating catastrophes: nuclear detonations, earth-shaking storms, absolute gravity inversion.",
            description_pt: "Desencadeia catástrofes devastadoras: detonações nucleares, tempestades sísmicas, inversão gravitacional absoluta.",
        },
    ],
    technocracy_equivalent: None,
    technocracy_equivalent_pt: None,
    mystic_equivalent: None,
    mystic_equivalent_pt: None,
    is_optional_rule: false,
};

pub const LIFE: SphereDefinition = SphereDefinition {
    id: "life",
    name: "Life",
    name_pt: "Vida",
    subtitle: "Biology, Flesh, and Metamorphosis",
    subtitle_pt: "Biologia, Carne e Metamorfose",
    page_ref: "M20, pp. 516-517",
    specialties: "Cloning, Disease, Evolution, Healing, Metamorphosis, Physical Enhancement",
    specialties_pt: "Clonagem, Doenças, Evolução, Cura, Metamorfose, Aprimoramento Físico",
    description: "Life rules all organic organisms, from single-celled microbes to plants, beasts, and human beings. Through Life magick, a mage heals wounds, purges disease, morphs flesh, and alters the biological codes of nature.",
    description_pt: "Vida rege todos os organismos orgânicos, desde micróbios unicelulares até plantas, animais e seres humanos. Através da mágica da Vida, o mago cura ferimentos, expurga doenças, transmuta a carne e altera os códigos biológicos da natureza.",
    ranks: &[
        SphereRank {
            rank: 1,
            name: "Sense Life",
            name_pt: "Sentir a Vida",
            description: "Detect living organisms, assess health, diagnose ailments, scan genetic makeup, and spot biological weaknesses.",
            description_pt: "Detecta organismos vivos, avalia saúde, diagnostica doenças, analisa constituição genética e identifica fraquezas biológicas.",
        },
        SphereRank {
            rank: 2,
            name: "Alter Simple Patterns / Heal Self",
            name_pt: "Alterar Padrões Simples / Curar a Si Mesmo",
            description: "Heal own damage, mend simple organisms (plants, insects, bacteria), or mutate simple biology.",
            description_pt: "Cura ferimentos próprios, regenera organismos simples (plantas, insetos, bactérias) ou induz mutações em biologia elementar.",
        },
        SphereRank {
            rank: 3,
            name: "Alter Self / Transform Simple Life / Heal Others",
            name_pt: "Alterar a Si Mesmo / Transformar Vida Simples / Curar Outros",
            description: "Boost own physical Attributes, heal other complex beings, or inflict lethal biological damage on enemies.",
            description_pt: "Aumenta Atributos Físicos próprios, cura outros seres complexos ou inflige danos biológicos letais em inimigos.",
        },
        SphereRank {
            rank: 4,
            name: "Alter Complex Life / Transform Self",
            name_pt: "Alterar Vida Complexa / Transformar a Si Mesmo",
            description: "Shapeshift own body into beasts or other human forms; mutate or modify other complex living creatures.",
            description_pt: "Metamorfoseia o próprio corpo em animais ou outras formas humanas; altera ou aprimora outras criaturas vivas complexas.",
        },
        SphereRank {
            rank: 5,
            name: "Mutate Complex Life / Create Life",
            name_pt: "Mutar Vida Complexa / Criar Vida",
            description: "Create new species from scratch, engineer chimeras, grant biological immortality, or reduce enemies to primordial slime.",
            description_pt: "Cria novas espécies a partir do nada, projeta quimeras, concede imortalidade biológica ou dissolve inimigos em lodo primordial.",
        },
    ],
    technocracy_equivalent: None,
    technocracy_equivalent_pt: None,
    mystic_equivalent: None,
    mystic_equivalent_pt: None,
    is_optional_rule: false,
};

pub const MATTER: SphereDefinition = SphereDefinition {
    id: "matter",
    name: "Matter",
    name_pt: "Matéria",
    subtitle: "Inanimate Substance and Structure",
    subtitle_pt: "Substância Inanimada e Estrutura",
    page_ref: "M20, pp. 517-519",
    specialties: "Alchemy, Armor, Construction, Molecular Shaping, Transmutation",
    specialties_pt: "Alquimia, Blindagem, Construção, Modelagem Molecular, Transmutação",
    description: "Matter governs all non-living physical substances — metals, stone, plastics, gases, liquids, and complex machines. An Adept of Matter transmutes lead into gold, crafts unbreakable alloys, and reshapes solid stone as if it were clay.",
    description_pt: "Matéria governa todas as substâncias físicas inanimadas — metais, rochas, plásticos, gases, líquidos e máquinas complexas. Um Adepto da Matéria transmuta chumbo em ouro, forja ligas inquebráveis e molda rocha sólida como se fosse argila.",
    ranks: &[
        SphereRank {
            rank: 1,
            name: "Matter Perceptions",
            name_pt: "Percepções da Matéria",
            description: "Analyze the composition, weight, structural integrity, and hidden properties of inanimate objects.",
            description_pt: "Analisa a composição, peso, integridade estrutural e propriedades ocultas de objetos inanimados.",
        },
        SphereRank {
            rank: 2,
            name: "Basic Transmutation",
            name_pt: "Transmutação Básica",
            description: "Alter homogeneous substances without changing state of matter: water to wine, lead to copper, reshaping soft materials.",
            description_pt: "Altera substâncias homogêneas sem mudar o estado físico: água em vinho, chumbo em cobre, remodelagem de materiais maleáveis.",
        },
        SphereRank {
            rank: 3,
            name: "Alter Form / Complex Transmutation",
            name_pt: "Alterar Forma / Transmutação Complexa",
            description: "Reshape solid objects, change states of matter (gas to solid), or transmute complex composite materials.",
            description_pt: "Remodela objetos sólidos, altera estados físicos (gás para sólido) ou transmuta materiais compostos complexos.",
        },
        SphereRank {
            rank: 4,
            name: "Complex Alteration",
            name_pt: "Alteração Complexa",
            description: "Transform complex mechanisms, create exotic alloys, make materials hyper-dense, lightweight, or bulletproof.",
            description_pt: "Transforma mecanismos complexos, cria ligas exóticas, torna materiais hiperdensos, ultraleves ou à prova de balas.",
        },
        SphereRank {
            rank: 5,
            name: "Alter Properties / Transmutation of Elements",
            name_pt: "Alterar Propriedades / Transmutação de Elementos",
            description: "Synthesize impossible substances with contradictory physical laws (e.g. cold fire, liquid diamond, anti-matter alloys).",
            description_pt: "Sintetiza substâncias impossíveis com propriedades físicas contraditórias (ex: fogo frio, diamante líquido, ligas de antimatéria).",
        },
    ],
    technocracy_equivalent: None,
    technocracy_equivalent_pt: None,
    mystic_equivalent: None,
    mystic_equivalent_pt: None,
    is_optional_rule: false,
};

pub const MIND: SphereDefinition = SphereDefinition {
    id: "mind",
    name: "Mind",
    name_pt: "Mente",
    subtitle: "Art of Consciousness",
    subtitle_pt: "Arte da Consciência",
    page_ref: "M20, pp. 519-520",
    specialties: "Astral Travel, Communication, Emotion, Illusion, Mind-Shielding, Psychic Combat",
    specialties_pt: "Viagem Astral, Comunicação, Emoção, Ilusão, Escudo Mental, Combate Psíquico",
    description: "Human reality is shaped by the interplay of consciousness. The Mind-mage alters those realities, soothing dementia, shattering sanity, broadcasting telepathic thoughts, and stepping untethered into the Astral Umbra.",
    description_pt: "A realidade humana é moldada pela interação da consciência. O mago da Mente altera essas realidades, acalmando a loucura, despedaçando a sanidade, transmitindo pensamentos telepáticos e desprendendo-se na Umbra Astral.",
    ranks: &[
        SphereRank {
            rank: 1,
            name: "Sense Thoughts & Emotions / Mind Shield",
            name_pt: "Sentir Pensamentos & Emoções / Escudo Mental",
            description: "Read emotional auras, detect lies, shield own mind from mental probes, and boost mental processing speed.",
            description_pt: "Lê auras emocionais, detecta mentiras, protege a própria mente contra sondas mentais e potencializa o processamento cognitivo.",
        },
        SphereRank {
            rank: 2,
            name: "Read Surface Thoughts / Mental Impulse",
            name_pt: "Ler Pensamentos Superficiais / Impulso Mental",
            description: "Scan surface thoughts, transmit short words or empathic impressions, and read psychic residues on objects.",
            description_pt: "Sonda pensamentos superficiais, projeta palavras breves ou impressões empáticas e lê resíduos psíquicos em objetos.",
        },
        SphereRank {
            rank: 3,
            name: "Mental Link / Project Illusions / Psychic Blast",
            name_pt: "Elo Mental / Projetar Ilusões / Golpe Psíquico",
            description: "Establish telepathic links, cast sensory illusions, explore dreams, and unleash painful psychic attacks.",
            description_pt: "Estabelece elos telepáticos, projeta ilusões sensoriais, navega em sonhos e desfecha ataques psíquicos dolorosos.",
        },
        SphereRank {
            rank: 4,
            name: "Control Conscious Mind / Astral Projection",
            name_pt: "Controlar Mente Consciente / Projeção Astral",
            description: "Command actions and thoughts, alter memories, rewrite personalities, and project astral form into the Astral Umbra.",
            description_pt: "Comanda ações e pensamentos, altera memórias, reescreve personalidades e projeta a forma astral na Umbra Astral.",
        },
        SphereRank {
            rank: 5,
            name: "Control Subconscious / Forge Psyche",
            name_pt: "Controlar Subconsciente / Forjar Psique",
            description: "Rewrite minds permanently, rewrite Nature Traits, transfer consciousness into new bodies, and create conscious minds from scratch.",
            description_pt: "Reescreve mentes permanentemente, altera a Natureza, transfere a consciência para novos corpos e gera mentes conscientes a partir do nada.",
        },
    ],
    technocracy_equivalent: None,
    technocracy_equivalent_pt: None,
    mystic_equivalent: None,
    mystic_equivalent_pt: None,
    is_optional_rule: false,
};

pub const PRIME: SphereDefinition = SphereDefinition {
    id: "prime",
    name: "Prime",
    name_pt: "Primórdio",
    subtitle: "Essence of all Things",
    subtitle_pt: "Essência de Todas as Coisas",
    page_ref: "M20, pp. 520-521",
    specialties: "Artifice, Channeling, Creation, Destruction, Perceptions, Resonance",
    specialties_pt: "Artifício, Canalização, Criação, Destruição, Percepções, Ressonância",
    description: "Prime is the raw fuel of Creation — Quintessence, Odyllic Force, the fundamental metaphysical currency that sustains all Patterns of Forces, Life, Matter, and Spirit.",
    description_pt: "Primórdio é o combustível bruto da Criação — Quintessência, Força Odílica, a moeda metafísica fundamental que sustenta todos os Padrões de Forças, Vida, Matéria e Espírito.",
    ranks: &[
        SphereRank {
            rank: 1,
            name: "Etheric Senses / Consecration",
            name_pt: "Sentidos Etéricos / Consagração",
            description: "Perceive Quintessence, detect Resonance and Synergy, absorb Quintessence, and consecrate personal items.",
            description_pt: "Percebe Quintessência, detecta Ressonância e Sinergia, absorve Quintessência e consagra itens pessoais.",
        },
        SphereRank {
            rank: 2,
            name: "Fuel Pattern / Enchant Patterns / Body of Light",
            name_pt: "Alimentar Padrão / Encantar Padrões / Corpo de Luz",
            description: "Infuse items with Quintessence to strike spirits or inflict aggravated damage. Conjure a Body of Light.",
            description_pt: "Imbui itens com Quintessência para ferir espíritos ou infligir dano agravado. Conjura um Corpo de Luz.",
        },
        SphereRank {
            rank: 3,
            name: "Channel Quintessence / Energy Weapon / Craft Periapts",
            name_pt: "Canalizar Quintessência / Arma de Energia / Forjar Periapto",
            description: "Draw Quintessence from Nodes and Tass, enchant living beings, create energy weapons, and forge temporary Wonders.",
            description_pt: "Extrai Quintessência de Nodos e Tass, encanta seres vivos, ergue armas de pura energia e forja Maravilhas temporárias.",
        },
        SphereRank {
            rank: 4,
            name: "Expel or Infuse Energy / Tap Wellspring / Permanent Wonders",
            name_pt: "Expelir ou Imbuir Energia / Drenar Manancial / Maravilhas Permanentes",
            description: "Disintegrate inanimate targets by draining Prime, tap into energetic Wellsprings, craft Tass, and forge permanent Wonders.",
            description_pt: "Desintegra alvos inanimados drenando sua Quintessência, colhe energia de Mananciais, forja Tass e cria Maravilhas permanentes.",
        },
        SphereRank {
            rank: 5,
            name: "Infuse or Withdraw Life Force / Create Node / Nullify Paradox",
            name_pt: "Imbuir ou Drenar Força Vital / Criar Nodo / Neutralizar Paradoxo",
            description: "Consume life force to obliterate living beings, create new Nodes, turn organisms into Soulflowers, and nullify Paradox.",
            description_pt: "Consome a força vital para aniquilar seres vivos, funda novos Nodos, transforma organismos em Flores da Alma e neutraliza Paradoxo.",
        },
    ],
    technocracy_equivalent: Some("Primal Utility"),
    technocracy_equivalent_pt: Some("Utilidade Primordial"),
    mystic_equivalent: None,
    mystic_equivalent_pt: None,
    is_optional_rule: false,
};

pub const SPIRIT: SphereDefinition = SphereDefinition {
    id: "spirit",
    name: "Spirit",
    name_pt: "Espírito",
    subtitle: "Art of the Otherworlds",
    subtitle_pt: "Arte dos Outros Mundos",
    page_ref: "M20, pp. 521-522",
    specialties: "Celestials, Gauntlet Manipulation, Infernals, Possession, Primal Spirits, Spirit Dealings, Tech Spirits, Umbral Travel",
    specialties_pt: "Celestiais, Manipulação da Película, Infernais, Possessão, Espíritos Primordiais, Trato com Espíritos, Espíritos Tecnológicos, Viagem Umbral",
    description: "Spirit reaches across the Gauntlet into the Umbra, dealing with spirits, ancestors, gods, and demons that exist beyond the physical Consensus.",
    description_pt: "Espírito alcança através da Película os reinos da Umbra, lidando com espíritos, ancestrais, deuses e demônios que habitam além do Consenso físico.",
    ranks: &[
        SphereRank {
            rank: 1,
            name: "Spirit Sight / Spirit Sense",
            name_pt: "Visão Espiritual / Sentido Espiritual",
            description: "Perceive the Penumbra, detect spirits, gauge Gauntlet thickness, and spot spiritual attachments.",
            description_pt: "Percebe a Penumbra, detecta espíritos, afere a espessura da Película e identifica vínculos espirituais em objetos.",
        },
        SphereRank {
            rank: 2,
            name: "Touch Spirit / Manipulate Gauntlet",
            name_pt: "Tocar Espírito / Manipular Película",
            description: "Reach across the Gauntlet, speak to or touch spirits, and thin or thicken the local Gauntlet barrier.",
            description_pt: "Toca através da Película, conversa com entidades espirituais e afina ou adensa a barreira da Película local.",
        },
        SphereRank {
            rank: 3,
            name: "Pierce Gauntlet / Step Sideways / Rouse Spirit",
            name_pt: "Rasgar a Película / Passo Lateral / Despertar Espírito",
            description: "Step physically into the Umbra, harm spirit entities, awaken slumbering spirits, or lull active ones.",
            description_pt: "Transmuta-se para adentrar fisicamente a Umbra, fere entidades espirituais, acorda espíritos adormecidos ou acalma entidades ativas.",
        },
        SphereRank {
            rank: 4,
            name: "Rend Gauntlet / Seal Breach / Bind Spirit",
            name_pt: "Dilacerar Película / Selar Ruptura / Aprisionar Espírito",
            description: "Tear open portals in the Gauntlet, bind spirits into Fetishes, become a living Fetish, or exorcise possessed mortals.",
            description_pt: "Abre portais na Película para grupos, aprisiona espíritos em Fetiches, torna-se um fetiche vivo temporário ou exorciza possessões.",
        },
        SphereRank {
            rank: 5,
            name: "Forge Ephemera / Gilgul / Break the Dreamshell",
            name_pt: "Forjar Efêmera / Gilgul / Romper a Concha Onírica",
            description: "Create Umbral Realms, bestow the terrible sentence of Gilgul (destroying an Avatar), and venture into the Deep Umbra.",
            description_pt: "Cria Reinos Umbrais, profere a sentença de Gilgul (destruição permanente do Avatar) e navega pelos confins da Umbra Profunda.",
        },
    ],
    technocracy_equivalent: Some("Dimensional Science"),
    technocracy_equivalent_pt: Some("Ciência Dimensional"),
    mystic_equivalent: None,
    mystic_equivalent_pt: None,
    is_optional_rule: false,
};

pub const TIME: SphereDefinition = SphereDefinition {
    id: "time",
    name: "Time",
    name_pt: "Tempo",
    subtitle: "Tricking the Flow",
    subtitle_pt: "Enganando o Fluxo",
    page_ref: "M20, pp. 522-523",
    specialties: "Perceptions, Prophecy, Temporal Control, Time Travel, Triggers",
    specialties_pt: "Percepções, Profecia, Controle Temporal, Viagem no Tempo, Gatilhos",
    description: "Time is fluid and subjective. Masters of Time perceive echoes of antiquity and prophecies of futures yet unwritten, accelerate into bullet time, or rewind crucial seconds.",
    description_pt: "O tempo é fluido e subjetivo. Mestres do Tempo percebem ecos da antiguidade e profecias de futuros ainda não escritos, aceleram em efeito bala ou retrocedem segundos cruciais.",
    ranks: &[
        SphereRank {
            rank: 1,
            name: "Time Sense",
            name_pt: "Sentido Temporal",
            description: "Maintain an infallible internal chronometer; detect temporal ripples and distortions in the time-stream.",
            description_pt: "Mantém um cronômetro biológico infalível; detecta ondulações temporais e distorções no fluxo do tempo.",
        },
        SphereRank {
            rank: 2,
            name: "Past & Future Sight / Thicken Walls of Time",
            name_pt: "Visão do Passado & Futuro / Espessar as Paredes do Tempo",
            description: "Glimpse past events and future probabilities at current location. Hinder temporal magicks of others.",
            description_pt: "Vislumbra acontecimentos passados e probabilidades futuras no local. Dificulta a mágica temporal de rivais.",
        },
        SphereRank {
            rank: 3,
            name: "Time Contraction or Dilation / Bullet Time / Rewind",
            name_pt: "Contração ou Dilatação Temporal / Bullet Time / Retroceder",
            description: "Gain multiple actions, slow enemies to a crawl, or rewind time by turns to correct immediate failures.",
            description_pt: "Ganha ações múltiplas, desacelera inimigos drasticamente ou retrocede o tempo em turnos para desfazer ações imediatas.",
        },
        SphereRank {
            rank: 4,
            name: "Time Determinism / Trigger Effect / Time Bubble",
            name_pt: "Determinismo Temporal / Efeito de Gatilho / Bolha de Tempo",
            description: "Freeze entities in stasis bubbles, suspend spells until triggered, and establish temporal anchor points.",
            description_pt: "Suspende alvos em bolhas de estase temporal, retém feitiços até que um gatilho ocorra e fixa pontos de âncora no tempo.",
        },
        SphereRank {
            rank: 5,
            name: "Temporal Travel / Time Immunity",
            name_pt: "Viagem Temporal / Imunidade ao Tempo",
            description: "Step completely outside the flow of time, immunize objects and people against aging, or travel across history.",
            description_pt: "Desliga-se do fluxo cronológico, torna indivíduos e objetos imunes à passagem do tempo ou viaja fisicamente pelos séculos.",
        },
    ],
    technocracy_equivalent: None,
    technocracy_equivalent_pt: None,
    mystic_equivalent: None,
    mystic_equivalent_pt: None,
    is_optional_rule: false,
};

pub const DATA: SphereDefinition = SphereDefinition {
    id: "data",
    name: "Data",
    name_pt: "Dados",
    subtitle: "Accessing Reality Metacode (Correspondence)",
    subtitle_pt: "Acessando o Metacódigo da Realidade (Correspondência)",
    page_ref: "M20, pp. 524-525",
    specialties: "Co-location, Encryption, Fabrication, Firewalling, Surveillance/Sousveillance",
    specialties_pt: "Colocalização, Criptografia, Fabricação, Firewalls, Vigilância/Sousveillance",
    description: "The Technocratic refinement of Correspondence used by Virtual Adepts and the New World Order. Treats distance and connection as entries in the reality metacode via electronic networks.",
    description_pt: "O refinamento Tecnocrático da Correspondência utilizado por Adeptos da Virtualidade e Nova Ordem Mundial. Trata distância e conexão como linhas no metacódigo da realidade através de redes eletrônicas.",
    ranks: &[
        SphereRank {
            rank: 1,
            name: "On the Ones and Zeros",
            name_pt: "Nos Zeros e Uns",
            description: "Calculate distances and network node connections through baseline digital metacode analysis.",
            description_pt: "Calcula distâncias e conexões entre nós de rede através da análise do metacódigo digital básico.",
        },
        SphereRank {
            rank: 2,
            name: "The Reach and the View",
            name_pt: "O Alcance e a Visão",
            description: "Access remote sensor feeds and touch distant locations hooked into global telecommunications.",
            description_pt: "Acessa transmissões de sensores remotos e alcança locais distantes integrados à malha de telecomunicações.",
        },
        SphereRank {
            rank: 3,
            name: "Quantum Teleportation / Firewalling",
            name_pt: "Teletransporte Quântico / Firewalls",
            description: "Download matter into quantum transit mode and erect particle-physics firewalls around systems and targets.",
            description_pt: "Transfere matéria em modo quântico e ergue firewalls de física de partículas ao redor de sistemas e alvos.",
        },
        SphereRank {
            rank: 4,
            name: "Between Space / Multilocation Access",
            name_pt: "Entreespaço / Acesso Multilocacional",
            description: "Open quantum gateways and deploy solid holographic manifestations across several locations simultaneously.",
            description_pt: "Abre portais quânticos e projeta manifestações holográficas sólidas em múltiplos locais simultâneos.",
        },
        SphereRank {
            rank: 5,
            name: "Fold Space / Hyperdispersed Perceptions",
            name_pt: "Dobrar Espaço / Percepções Hiperdispersas",
            description: "Stack physical coordinates into identical points and disperse sensor awareness across the entire globe.",
            description_pt: "Empilha coordenadas físicas no mesmo espaço e dispersa a percepção de sensores através de todo o globo.",
        },
    ],
    technocracy_equivalent: None,
    technocracy_equivalent_pt: None,
    mystic_equivalent: Some("Correspondence"),
    mystic_equivalent_pt: Some("Correspondência"),
    is_optional_rule: false,
};

pub const DIMENSIONAL_SCIENCE: SphereDefinition = SphereDefinition {
    id: "dimensional_science",
    name: "Dimensional Science",
    name_pt: "Ciência Dimensional",
    subtitle: "Parsing Alternate Reality Spectrums (Spirit)",
    subtitle_pt: "Decodificando Espectros de Realidade Alternativa (Espírito)",
    page_ref: "M20, pp. 525-526",
    specialties: "Anthropic Principle Applications, Applied Theory, Dimensional Anomaly, EDE Relations, Mapping, Subdimensions",
    specialties_pt: "Aplicações do Princípio Antrópico, Teoria Aplicada, Anomalia Dimensional, Relações com EDEs, Cartografia, Subdimensões",
    description: "The Void Engineers' paradigm for navigating subdimensions, containing Extra-Dimensional Entities (EDEs), and breaching the Deep Universe using hypermath and dimensional technology.",
    description_pt: "O paradigma dos Engenheiros do Vácuo para navegar em subdimensões, conter Entidades Extradimensionais (EDEs) e desbravar o Universo Profundo através de hipermatemática e maquinário dimensional.",
    ranks: &[
        SphereRank {
            rank: 1,
            name: "EDE Scan / Evaluate Gauntlet",
            name_pt: "Escaneamento de EDE / Avaliar Película",
            description: "Detect EDE incursions and calculate the density and stability of the local Dimensional Gauntlet.",
            description_pt: "Detecta incursões de EDEs e calcula a densidade e estabilidade da Película Dimensional local.",
        },
        SphereRank {
            rank: 2,
            name: "Modify Dimensional Gauntlet / Transdimensional Field",
            name_pt: "Modificar Película Dimensional / Campo Transdimensional",
            description: "Lower the Gauntlet to 0 without mystic backlash, and emit radiation pulses to signal alternate dimensions.",
            description_pt: "Reduz a Película até 0 sem sofrer retaliação mística e emite pulsos de radiação para sinalizar dimensões paralelas.",
        },
        SphereRank {
            rank: 3,
            name: "Dimensional Shift / Phase Disruption Field",
            name_pt: "Salto Dimensional / Campo de Disrupção de Fase",
            description: "Step into subdimensions and use phased energy weapons to stun, injure, or disintegrate EDEs.",
            description_pt: "Adentra fisicamente subdimensões e emprega armamento de disrupção de fase para atordoar, ferir ou desintegrar EDEs.",
        },
        SphereRank {
            rank: 4,
            name: "Dimensional Gateway / Stabilize Dimensional Field",
            name_pt: "Portal Dimensional / Estabilizar Campo Dimensional",
            description: "Open large transdimensional gates and reinforce human biology against Void Adaptation.",
            description_pt: "Abre portais transdimensionais para equipes e naves, e imuniza a biologia humana contra a Adaptação ao Vácuo.",
        },
        SphereRank {
            rank: 5,
            name: "Anthropic Field / Cosmogenesis",
            name_pt: "Campo Antrópico / Cosmogênese",
            description: "Maintain an artificial Anthropic Field for Deep Universe exploration and construct Horizon bases.",
            description_pt: "Gera um Campo Antrópico autossustentado para exploração do Universo Profundo e concebe bases de Horizonte.",
        },
    ],
    technocracy_equivalent: None,
    technocracy_equivalent_pt: None,
    mystic_equivalent: Some("Spirit"),
    mystic_equivalent_pt: Some("Espírito"),
    is_optional_rule: false,
};

pub const PRIMAL_UTILITY: SphereDefinition = SphereDefinition {
    id: "primal_utility",
    name: "Primal Utility",
    name_pt: "Utilidade Primordial",
    subtitle: "Investing Essential Energies (Prime)",
    subtitle_pt: "Investindo Energias Essenciais (Primórdio)",
    page_ref: "M20, pp. 526-527",
    specialties: "Assessment, Generating Energetic Capital, Investment, Personal Value, Primal Ventures, Wellsprings",
    specialties_pt: "Avaliação, Geração de Capital Energético, Investimento, Valor Pessoal, Empreendimentos Primordiais, Mananciais",
    description: "The Syndicate's hypereconomic mastery of Prime energy. Treats Quintessence as energetic capital generated by human ambition, commerce, and transaction value.",
    description_pt: "A maestria hipereconômica do Sindicato sobre a energia do Primórdio. Trata Quintessência como capital energético gerado pela ambição humana, comércio e valor transacional.",
    ranks: &[
        SphereRank {
            rank: 1,
            name: "Assess Primal Utility / Exploit Primal Venture",
            name_pt: "Avaliar Utilidade Primordial / Explorar Empreendimento",
            description: "Analyze energetic financial flows and draw Quintessence from commercial business Ventures.",
            description_pt: "Analisa fluxos financeiros energéticos e extrai Quintessência de Empreendimentos comerciais mundanos.",
        },
        SphereRank {
            rank: 2,
            name: "Create Gadgets / Primal Innovation",
            name_pt: "Criar Dispositivos / Inovação Primordial",
            description: "Infuse consumer items with high perceived value to replicate Prime 2 effects through corporate innovation.",
            description_pt: "Imbui bens de consumo com alto valor agregado para reproduzir os efeitos de Primórdio 2 via inovação de ponta.",
        },
        SphereRank {
            rank: 3,
            name: "Create Stable Devices / Use Currency",
            name_pt: "Criar Dispositivos Estáveis / Usar Moeda",
            description: "Convert energetic Currency (Tass) into permanent tech Devices and recharge corporate Matrices (Periapts).",
            description_pt: "Converte Moeda energética (Tass) em Dispositivos permanentes e recarrega Matrizes corporativas (Periaptos).",
        },
        SphereRank {
            rank: 4,
            name: "Create Tass / Liquidate Assets",
            name_pt: "Criar Tass / Liquidar Ativos",
            description: "Materialize physical Currency (platinum cards, bearer bonds) and liquidate physical assets to deny competitors.",
            description_pt: "Materializa Moeda tangível (cartões platinum, títulos ao portador) e liquida ativos físicos privando competidores.",
        },
        SphereRank {
            rank: 5,
            name: "Create Living Assets / Market Compensation",
            name_pt: "Criar Ativos Vivos / Compensação de Mercado",
            description: "Found commercial mega-Ventures, liquidate living targets cleanly, and mitigate Market Correction (Paradox).",
            description_pt: "Inaugura mega-Empreendimentos comerciais, liquida alvos vivos e compensa a Correção de Mercado (Paradoxo).",
        },
    ],
    technocracy_equivalent: None,
    technocracy_equivalent_pt: None,
    mystic_equivalent: Some("Prime"),
    mystic_equivalent_pt: Some("Primórdio"),
    is_optional_rule: false,
};

pub const WILD_TALENT: SphereDefinition = SphereDefinition {
    id: "wild_talent",
    name: "Wild Talent",
    name_pt: "Talento Selvagem",
    subtitle: "Optional Rule: Uncontrolled Paranormal Power",
    subtitle_pt: "Regra Opcional: Poder Paranormal Descontrolado",
    page_ref: "M20, pp. 527-528",
    specialties: "Crisis Surges, Marauder Chaos, Death-Strike",
    specialties_pt: "Surtos de Crise, Caos dos Espreitadores, Golpe Mortal",
    description: "A sudden burst of uncontrolled magick erupting under extreme trauma, Awakening, or death. An optional plot device where the Avatar takes the wheel.",
    description_pt: "Uma erupção súbita de mágica descontrolada sob trauma extremo, Despertar ou morte iminente. Um recurso narrativo opcional onde o Avatar assume o controle.",
    ranks: &[],
    technocracy_equivalent: None,
    technocracy_equivalent_pt: None,
    mystic_equivalent: None,
    mystic_equivalent_pt: None,
    is_optional_rule: true,
};

// ============================================================================
// REGRAS TEÓRICAS GERAIS DE ESFERAS (M20, pp. 511-512)
// ============================================================================

pub const SPHERE_THEORY_RULES: SphereTheoryArticle = SphereTheoryArticle {
    id: "theory_sphere_rules",
    title: "General Sphere Rules: Metaphysics, Ranks & Conjunctional Magick",
    title_pt: "Regras Gerais das Esferas: Metafísica, Graduações & Mágica Conjunta",
    page_ref: "M20, pp. 511-512",
    content: include_str!("../../../data/compendium/spheres/theory_sphere_rules.en.md"),
    content_pt: include_str!("../../../data/compendium/spheres/theory_sphere_rules.pt.md"),
};
