//! Regras Canônicas Expandidas de Dô & Truques de Combate M20
//! Truque do Golpe Trovão (p. 449), Oito Membros da Maestria (p. 580) e Regras de Dô (pp. 580-581)

use super::models::{MageTrickArticle, EightLimbsArticle, LimbDefinition, DoRulesArticle, DoAdvantage};

/// Box Oficial do Livro M20 (p. 449): "Mage Trick: The Thunder Punch"
pub const THUNDER_PUNCH_TRICK: MageTrickArticle = MageTrickArticle {
    id: "thunder_punch",
    title: "Mage Trick: The Thunder Punch",
    title_pt: "Truque de Mago: O Golpe Trovão",
    page_ref: "M20, p. 449",
    spheres_summary: "Correspondence 1, Entropy 1-2, Forces 2, Life 3, Mind 2, Matter 2, Prime 2-3, or Time 2",
    spheres_summary_pt: "Correspondência 1, Entropia 1-2, Forças 2, Vida 3, Mente 2, Matéria 2, Primórdio 2-3 ou Tempo 2",
    difficulty_rule: "Each success reduces attack difficulty by -1 (maximum adjustment: -3)",
    difficulty_rule_pt: "Cada sucesso reduz a dificuldade do ataque em -1 (ajuste máximo: -3)",
    damage_rule: "Coincidental: Bashing damage. Life 3 or Prime 3: Aggravated damage (Pattern assault). Vulgar if visibly disproportionate to physique.",
    damage_rule_pt: "Coincidente: Dano Contundente. Vida 3 ou Primórdio 3: Dano Agravado (ataque ao Padrão). Vulgar se visivelmente desproporcional à compleição.",
    backlash_rule: "If target soaks ALL damage, attacker takes the full intended damage (Bashing; Lethal if striking walls/steel armor).",
    backlash_rule_pt: "Se o alvo absorver TODO o dano, o próprio mago sofre o dano pretendido (Contundente; Letal contra paredes/armadura de aço).",
    paragraphs: &[
        "Throwing Enlightened force behind a punch, kick, or other hand-to-hand attack, a fighting mage delivers an unexpectedly powerful blow. Story-wise, the trick looks like a perfectly executed strike. In game terms, the mage employs either Correspondence 1 (to judge the perfect spot to hit), Entropy 1 or 2 (to either find a weak spot or adjust probability to the perfect place and time), Forces 2 (to increase velocity), Life 3 (to boost Strength or to damage the enemy internally), Mind 2 (to send an impulse to surrender), Matter 2 (to break inert materials), Prime 2 (to directly attack the target’s Pattern), or Time 2 (to note the perfect opening). As with most other tricks, each success reduces the difficulty of the attack roll by -1 per success, to a maximum adjustment of -3.",
        "In most cases, this “thunder punch” – which can also be performed with hand-to-hand weapons – is coincidental and inflicts bashing damage. A Life 3 or Prime 3 Pattern assault, however, inflicts aggravated damage instead, using the blow to focus an all-out metaphysical attack. Truly powerful blows may slip into vulgar magick if the mage appears to be too weak to have inflicted such a powerful strike… like, say, the proverbial skinny geek smashing every bone in the body of a towering muscle-thug. Oh, yeah – the thunder punch can kill people if you’re not careful, so it’s best to save this trick for Night-Folk and other such opponents unless your mage wants to face charges for manslaughter or murder.",
        "Another flipside to the blow is obvious: you can hurt yourself while doing it. If the target manages to soak every level of damage inflicted by a thunder punch, then the attacker hurts himself; the damage he would have inflicted on the target gets inflicted on the mage instead (yes, he can try to soak it too). In the case of the Pattern attacks, the mage simply suffers bashing damage, not aggravated harm. If, however, the mage tries to thunder punch a wall, steel armor, solid stone, and so forth, he might take lethal damage instead, possibly shattering his hand or foot… or, if he’s using a weapon to strike, breaking his weapon against that unyielding surface.",
    ],
    paragraphs_pt: &[
        "Colocando força Iluminada por trás de um soco, chute ou outro ataque corpo a corpo, um mago lutador desfere um golpe inesperadamente poderoso. Narrativamente, o truque parece um golpe perfeitamente executado. Em termos de jogo, o mago emprega Correspondência 1 (para julgar o ponto de impacto perfeito), Entropia 1 ou 2 (para encontrar um ponto fraco ou ajustar a probabilidade ao momento e local ideais), Forças 2 (para aumentar a velocidade), Vida 3 (para aumentar a Força ou lesionar internamente o inimigo), Mente 2 (para enviar um impulso de rendição), Matéria 2 (para quebrar materiais inertes), Primórdio 2 (para atacar diretamente o Padrão do alvo) ou Tempo 2 (para notar a brecha perfeita). Como na maioria dos outros truques, cada sucesso reduz a dificuldade da rolagem de ataque em -1 por sucesso, até um ajuste máximo de -3.",
        "Na maioria dos casos, este \"golpe trovão\" — que também pode ser executado com armas brancas — é coincidente e causa dano contundente. Um ataque ao Padrão com Vida 3 ou Primórdio 3, contudo, causa dano agravado, usando o impacto físico para focar um ataque metafísico devastador. Golpes verdadeiramente poderosos podem deslizar para mágica vulgar se o mago parecer fraco demais para ter causado tal impacto... como o lendário geek franzino quebrando todos os ossos do corpo de um brutamontes imenso. E sim — o golpe trovão pode matar se você não tiver cuidado, portanto é melhor guardar este truque para o Povo da Noite e oponentes semelhantes, a menos que seu mago queira responder por homicídio culposo ou assassinato.",
        "O outro lado da moeda é evidente: você pode se machucar ao usá-lo. Se o alvo conseguir absorver cada nível de dano infligido pelo golpe trovão, o próprio atacante se fere; o dano que ele teria infligido ao alvo é aplicado no próprio mago (sim, ele também pode tentar absorver). No caso dos ataques ao Padrão, o mago sofre apenas dano contundente, e não dano agravado. Se, no entanto, o mago tentar desferir um golpe trovão contra uma parede, armadura de aço, pedra maciça e afins, ele pode sofrer dano letal, possivelmente esfacelando sua mão ou pé... ou, se estiver empunhando uma arma para golpear, quebrando-a contra a superfície inquebrável.",
    ],
    sphere_tags: &[
        "Correspondence 1",
        "Entropy 1-2",
        "Forces 2",
        "Life 3",
        "Mind 2",
        "Matter 2",
        "Prime 2-3",
        "Time 2",
    ],
    sphere_tags_pt: &[
        "Correspondência 1",
        "Entropia 1-2",
        "Forças 2",
        "Vida 3",
        "Mente 2",
        "Matéria 2",
        "Primórdio 2-3",
        "Tempo 2",
    ],
};

// ============================================================================

pub const EIGHT_LIMBS_ARTICLE: EightLimbsArticle = EightLimbsArticle {
    id: "eight_limbs",
    title: "Eight Limbs of Expertise",
    title_pt: "Os Oito Membros da Maestria",
    subtitle: "Akashic Dharma Sutra • Chapter Six & Book of Secrets",
    subtitle_pt: "Dharma Sutra Akashiano • Capítulo Seis & Livro dos Segredos",
    page_ref: "M20 Ch. 6, p. 580",
    intro: "According to the Akashic Dharma Sutra, the Way is divided into eight fields of expertise. And although Do is often regarded as a martial art, its devotees recognize that a truly harmonious human being understands at least a little bit about all of them.",
    intro_pt: "De acordo com o Dharma Sutra Akashiano, o Caminho é dividido em oito campos de maestria. E embora o Dô seja frequentemente considerado uma arte marcial, seus devotos reconhecem que um ser humano verdadeiramente harmonioso compreende ao menos um pouco sobre todos eles.",
    limbs: &[
        LimbDefinition {
            name: "Dharmamukti",
            title: "Dharmamukti (The Dharma Clasped Hand)",
            title_pt: "Dharmamukti (A Mão Unida do Dharma)",
            description: "Unarmed combat techniques of the Dharma Clasped Hand. Both adapting and inspiring other martial arts techniques, this limb comprises the most obvious form of Do, but only one of its many applications.",
            description_pt: "Técnicas de combate desarmado da Mão Unida do Dharma. Tanto adaptando quanto inspirando outras técnicas marciais, este membro compreende a forma mais evidente do Dô, mas é apenas uma de suas inúmeras aplicações.",
            abilities: &["Alertness", "Athletics", "Do"],
            abilities_pt: &["Prontidão", "Atletismo", "Dô"],
        },
        LimbDefinition {
            name: "Dhyana",
            title: "Dhyana (The Limb of Meditation)",
            title_pt: "Dhyana (O Membro da Meditação)",
            description: "The Limb of Meditation, focused upon calming an excitable mind. Refined as a way to escape the clutches of egotism and attachment, Dhyana employs mandalas, the Five Asian Elements, meditative movement practices, and the greater realm beyond Self.",
            description_pt: "O Membro da Meditação, voltado para aquietar uma mente agitada. Refinado como uma senda para escapar das amarras do egoísmo e do apego, Dhyana emprega mandalas, os Cinco Elementos Orientais, práticas de movimento meditativo e a transcendência além do Eu.",
            abilities: &["Awareness", "Enigmas", "Meditation"],
            abilities_pt: &["Consciência", "Enigmas", "Meditação"],
        },
        LimbDefinition {
            name: "Jivahasta",
            title: "Jivahasta (The Hand of Life)",
            title_pt: "Jivahasta (A Mão da Vida)",
            description: "The Hand of Life, a study of healing arts and bodywork.",
            description_pt: "A Mão da Vida, um estudo aprofundado das artes de cura, terapias corporais e equilíbrio biológico.",
            abilities: &["Esoterica (Bodywork, Herbalism, Yoga)", "Medicine (Alternate Healing)", "Survival"],
            abilities_pt: &["Esotérica (Trabalho Corporal, Herbalismo, Ioga)", "Medicina (Técnicas Alternativas de Cura)", "Sobrevivência"],
        },
        LimbDefinition {
            name: "Karma",
            title: "Karma (Devotion to Humble Labor)",
            title_pt: "Karma (Devoção ao Labor Humilde)",
            description: "Devotion to humble labor, the perfect focus of small things, and one’s place within an infinite cosmos, epitomized by the saying, “Before enlightenment, chopping wood and carrying water. After enlightenment, chopping wood and carrying water.”",
            description_pt: "Devoção ao trabalho humilde, foco perfeito nas pequenas coisas e consciência do próprio lugar dentro de um cosmos infinito, sintetizado no provérbio: \"Antes da iluminação, cortar lenha e carregar água. Depois da iluminação, cortar lenha e carregar água\".",
            abilities: &["Art (all kinds)", "Crafts (non-martial)", "Etiquette"],
            abilities_pt: &["Arte (todas as formas)", "Ofícios (especialidades não-marciais)", "Etiqueta"],
        },
        LimbDefinition {
            name: "Prajna",
            title: "Prajna (Study of Ethics and Philosophy)",
            title_pt: "Prajna (Estudo da Ética e Filosofia)",
            description: "The study of ethics and philosophy. Just as a devotee of the Way refines his body for war, he must also refine his mind with kindness, compassion, and the stillness of perfect harmony.",
            description_pt: "O estudo da ética e da filosofia. Assim como um devoto do Caminho refina seu corpo para o combate, ele também deve refinar sua mente com bondade, compaixão e a serenidade da harmonia perfeita.",
            abilities: &["Academics (Philosophy)", "Belief Systems", "Cosmology"],
            abilities_pt: &["Instrução (Filosofia)", "Sistemas de Crença", "Cosmologia"],
        },
        LimbDefinition {
            name: "Shastamarga",
            title: "Shastamarga (The Way of Weapons)",
            title_pt: "Shastamarga (O Caminho das Armas)",
            description: "The Way of Weapons, intended to expand bodily awareness into the tools that extend the body’s reach. By focusing on weapons, the craftsmanship involved, and the awful consequences of their use and abuse, a devotee learns to judge the implications of her own actions upon the greater whole.",
            description_pt: "O Caminho das Armas, destinado a expandir a consciência corporal através dos instrumentos que prolongam o alcance físico. Ao focar nas armas, no artesanato e nas terríveis consequências de seu uso e abuso, o devoto aprende a ponderar as implicações de seus atos sobre a totalidade.",
            abilities: &["Academics (Strategy)", "Crafts (Weaponsmithing)", "Melee"],
            abilities_pt: &["Instrução (Estratégia)", "Ofícios (Armaria / Forja)", "Armas Brancas"],
        },
        LimbDefinition {
            name: "Sunyakaya",
            title: "Sunyakaya (The Limb of the Empty Body)",
            title_pt: "Sunyakaya (O Membro do Corpo Vazio)",
            description: "The Limb of the Empty Body, cultivating the ability to disappear. Based as it is upon the removal of ego through the concealment of identity, this limb has more practical uses as well.",
            description_pt: "O Membro do Corpo Vazio, cultivando a capacidade de desaparecer. Fundamentado na dissolução do ego através da ocultação da identidade, este membro possui também aplicações práticas e de furtividade suprema.",
            abilities: &["Meditation", "Stealth", "Subterfuge"],
            abilities_pt: &["Meditação", "Furtividade", "Subterfúgio"],
        },
        LimbDefinition {
            name: "Tricanmarga",
            title: "Tricanmarga (The Way of the Triple Struggle)",
            title_pt: "Tricanmarga (O Caminho da Tripla Luta)",
            description: "The Way of the Triple Struggle, balancing out the forces of Dynamism, Stasis, and Entropy (seen as Tiger, Phoenix, and Dragon) within one’s own self and then – by extension – reaching greater harmony with the world beyond that self.",
            description_pt: "O Caminho da Tripla Luta, equilibrando as forças do Dinamismo, Estase e Entropia (representadas como o Tigre, a Fênix e o Dragão) dentro de si mesmo e, por extensão, alcançando maior harmonia com o mundo além do Eu.",
            abilities: &["Acrobatics", "Athletics", "Esoterica (Body Control, Yoga)"],
            abilities_pt: &["Acrobacia", "Atletismo", "Esotérica (Controle Corporal, Ioga)"],
        },
    ],
    progression_rule: "In game terms, you must have at least two dots in limb-related Abilities other than Dharmamukti for every dot in Do. Before you can add another dot of Do, you must first add two other dots in limb-related fields. To go, for example, from Do 2 to Do 3, your character would also have to learn at least two dots in one of the Abilities on the sidebar. Ideally, he’ll eventually learn at least one dot in all eight limbs.",
    progression_rule_pt: "Em termos de sistema, você deve possuir ao menos dois pontos em Habilidades ligadas aos membros (exceto Dharmamukti) para cada ponto em Dô. Antes de adquirir um novo ponto em Dô, o mago precisa primeiro adquirir dois outros pontos nos campos dos membros. Para evoluir, por exemplo, de Dô 2 para Dô 3, o personagem precisa desenvolver ao menos dois pontos em uma das Habilidades listadas. O ideal é eventualmente possuir ao menos um ponto em todos os oito membros.",
    peaceful_way_title: "Optional Rule: The Peaceful Way",
    peaceful_way_title_pt: "Regra Opcional: O Caminho Pacífico",
    peaceful_way_rule: "Do is not merely a martial art. By applying the Way to peaceful tasks, a Tao-shih may focus its principles to great success. In story terms, the Akashic character meditates upon the Way as he performs whatever task he has set his mind to doing.\n\nIn game terms, the player spends one Willpower point and then rolls his Do Trait as a dice pool against difficulty 8. Each success he rolls adds one success to a mundane task associated with one of the eight limbs listed above. To perform the task itself, the player rolls the associated Attribute + Ability, at whatever difficulty seems to fit the task at hand.\n\nOnly the Associated Abilities listed above may be enhanced by this optional rule, with the exceptions of Do combat maneuvers and the Abilities associated with the Shastamarga limb. Such violent tasks do not get the benefit of this rule; this is, after all, the Peaceful Way, and so martial applications are not appropriate to its purity.",
    peaceful_way_rule_pt: "O Dô não é apenas uma arte marcial. Aplicando o Caminho a tarefas pacíficas, um Tao-shih pode canalizar seus princípios com enorme sucesso. Narrativamente, o personagem akashiano medita sobre o Caminho enquanto realiza a tarefa a que se propôs.\n\nEm termos de jogo, o jogador gasta um ponto de Força de Vontade e rola sua parada de Dô contra dificuldade 8. Cada sucesso obtido adiciona um sucesso automático a uma tarefa mundana associada a um dos oito membros listados acima. Para realizar a tarefa em si, o jogador rola o Atributo + Habilidade correspondente na dificuldade apropriada à situação.\n\nApenas as Habilidades Associadas listadas acima podem ser beneficiadas por esta regra opcional, com a exceção expressa de manobras de combate de Dô e das Habilidades associadas ao membro Shastamarga (Armas). Tarefas violentas não recebem o benefício desta regra; trata-se, afinal, do Caminho Pacífico, e aplicações de combate não são condizentes com sua pureza.",
};



pub const DO_RULES_ARTICLE: DoRulesArticle = DoRulesArticle {
    id: "do_rules",
    title: "Do: The Way of Life & Fighting Prowess",
    title_pt: "Dô: O Caminho da Vida & Destreza Marcial",
    subtitle: "Akashic Brotherhood Canonical Combat Rules • M20",
    subtitle_pt: "Regras Canônicas de Combate da Irmandade de Akashayana • M20",
    page_ref: "M20 Ch. 6, pp. 580-581",
    overview: "The quintessential martial art from which all other disciplines supposedly descend, Do is far more than a mere collection of fighting techniques. As shown by its Trait listing in Chapter Six, Do is a way of life… or, more literally, the Way of life. When directed toward peaceful ends, Do allows a person to refine enormous potential. And when directed, by sad necessity, toward the ends of violence, Do is legendary in its martial applications.",
    overview_pt: "A arte marcial quintessencial da qual todas as outras disciplinas supostamente descendem, o Dô é muito mais do que uma simples coleção de técnicas de combate. O Dô é um modo de vida... ou, mais literalmente, o Caminho da vida. Quando direcionado para fins pacíficos, o Dô permite a uma pessoa refinar um potencial colossal. E quando direcionado, por triste necessidade, para a violência, o Dô é lendário em suas aplicações marciais.",
    commitment: "A starting character cannot begin play with more than two dots in Do. Further expertise must be earned over the course of the game. Only Akashics and their closest, most trusted allies may learn it, and that discipline is a lifetime commitment. A Tao-shih (Way-scholar/warrior) must spend at least one hour every day practicing Do; otherwise, his skills diminish. In game terms, he loses dots temporarily until regular training resumes – roughly one dot for every two weeks without practice.",
    commitment_pt: "Um personagem iniciante não pode começar o jogo com mais de dois pontos em Dô. Maestria adicional deve ser conquistada ao longo das crônicas. Apenas akashianos e seus aliados mais íntimos e leais podem aprendê-lo, e essa disciplina é um compromisso para toda a vida. Um Tao-shih (guerreiro/sábio do Caminho) precisa dedicar ao menos uma hora todos os dias à prática de Dô; do contrário, suas habilidades diminuem. Em termos de jogo, ele perde pontos temporariamente até que retome o treino regular — aproximadamente um ponto para cada duas semanas sem prática.",
    advantages: &[
        DoAdvantage {
            code: "secret_teachings",
            title: "Secret Teachings",
            title_pt: "Ensinamentos Secretos",
            icon: "📜",
            rule: "Only the most skilled Akashayana (Do 3+) may teach this Art. A teacher passes on one fighting maneuver for each dot of Do she possesses, plus one more for each dot in Intelligence. A student cannot learn Do without studying the eight limbs of Do.",
            rule_pt: "Apenas akashianos mestres (Dô 3+) podem ensinar esta Arte. Um instrutor transmite uma manobra de combate para cada ponto de Dô que possui, mais uma por ponto em Inteligência. O aprendiz não pode avançar em Dô sem estudar os oito membros.",
        },
        DoAdvantage {
            code: "flexibility",
            title: "Flexibility",
            title_pt: "Flexibilidade",
            icon: "🥋",
            rule: "A Do-using character may employ any general or martial arts combat maneuver (1 dot in Do satisfies 1 dot required in Martial Arts). Dirty fighting techniques cannot be used – they are brutal, undisciplined, and inharmonious.",
            rule_pt: "Um praticante de Dô pode utilizar qualquer manobra de combate geral ou marcial (1 ponto em Dô substitui 1 ponto exigido em Artes Marciais). Não pode empregar manobras de Luta Suja — brutais, indisciplinadas e desarmônicas.",
        },
        DoAdvantage {
            code: "precision",
            title: "Precision (Well-Trained Advantage)",
            title_pt: "Precisão (Vantagem de Bem Treinado)",
            icon: "🎯",
            rule: "When employing general combat maneuvers, subtracts -1 from the usual difficulty; a punch, for instance, is difficulty 5, not 6. Maneuvers from Do or Martial Arts use normal difficulty.",
            rule_pt: "Ao empregar manobras gerais de combate corporal, subtrai -1 na dificuldade habitual; um soco, por exemplo, tem dificuldade 5, e não 6. Manobras próprias de Dô ou Artes Marciais usam as dificuldades normais.",
        },
        DoAdvantage {
            code: "martial_mastery",
            title: "Martial Mastery",
            title_pt: "Maestria Marcial",
            icon: "⚡",
            rule: "Select two martial arts maneuvers for every dot in Do, plus one special Do technique for every dot above the first. A character with both Do and Martial Arts adds all maneuvers together.",
            rule_pt: "O jogador escolhe duas manobras de artes marciais para cada ponto em Dô, mais uma técnica especial de Dô para cada ponto acima do primeiro. Tendo Dô e Artes Marciais, soma todas as manobras.",
        },
        DoAdvantage {
            code: "differences_in_mastery",
            title: "Differences in Mastery",
            title_pt: "Diferença nas Paradas de Dados",
            icon: "⚖️",
            rule: "Uses Dexterity + Martial Arts for maneuvers acquired through Martial Arts, and Dexterity + Do for those learned through Do. Once Do exceeds Martial Arts, use Do for all combat maneuver dice pools.",
            rule_pt: "Usa Destreza + Artes Marciais para as manobras aprendidas via Artes Marciais, e Destreza + Dô para as aprendidas através de Dô. Quando o valor de Dô superar Artes Marciais, usa Dô para todas as rolagens!",
        },
        DoAdvantage {
            code: "lethal_damage",
            title: "Lethal Damage",
            title_pt: "Dano Letal Desarmado",
            icon: "⚔️",
            rule: "Thanks to intense focus and precision, unarmed attacks inflict lethal damage. The Akashic may choose to use bashing damage reflexively at any time before rolling to hit.",
            rule_pt: "Graças ao foco e precisão supremos, ataques desarmados causam dano letal. O akashiano pode optar reflexivamente por causar dano contundente a qualquer instante antes da rolagem de ataque.",
        },
        DoAdvantage {
            code: "hardened_defense",
            title: "Hardened Defense",
            title_pt: "Defesa Endurecida",
            icon: "🛡️",
            rule: "An unarmed Do practitioner can block Brawl or Melee attacks that cause lethal damage using bare palms and limbs. (Cannot stop projectiles without special techniques like Arrow Cutting).",
            rule_pt: "Um praticante desarmado de Dô pode bloquear e aparar ataques de Briga ou Armas Brancas que causem dano letal usando as mãos nuas e antebraços. (Não detém projéteis sem técnicas como Aparar Flechas).",
        },
    ],
};
