//! Catálogo Canônico de Manobras de Combate (M20 pp. 423-426, 448-450, 580-581)

use super::models::{CombatManeuver, ManeuverCategory};

pub const ALL_COMBAT_MANEUVERS: &[CombatManeuver] = &[
    // ------------------------------------------------------------------------
    // Manobras Gerais de Corpo a Corpo (General Hand-to-Hand)
    // ------------------------------------------------------------------------
    CombatManeuver {
        id: "bite",
        name: "Bite",
        name_pt: "Mordida",
        category: ManeuverCategory::General,
        roll: "Dexterity + Brawl",
        roll_pt: "Destreza + Briga",
        damage: "Strength + 1 / B or L",
        damage_pt: "Força + 1 / C ou L",
        difficulty: "5",
        actions: 1,
        requirement: "Creatures with teeth",
        requirement_pt: "Criaturas com dentes",
        description: "Creatures with teeth can bite. Human jaws normally inflict Strength in bashing damage, but a shapechanged mage’s teeth can deal out lethal harm instead. Certain Night-Folk inflict aggravated damage with their bites, but a mage – even in a more dangerous form – inflicts lethal damage only. Typically, a bite attack causes Strength +1 damage; an especially large mouth or teeth, however, may add +2 or even +3 to that attack.",
        description_pt: "Criaturas com dentes podem morder. Mandíbulas humanas normalmente causam Força em dano contundente, mas os dentes de um mago metamorfo podem causar dano letal. Certos Membros do Povo da Noite causam dano agravado com suas mordidas, mas um mago – mesmo em forma mais perigosa – causa apenas dano letal. Tipicamente, um ataque de mordida causa dano de Força +1; bocas ou dentes excepcionalmente grandes, contudo, podem somar +2 ou +3 a esse ataque.",
    },
    CombatManeuver {
        id: "claw",
        name: "Claw",
        name_pt: "Garras",
        category: ManeuverCategory::General,
        roll: "Dexterity + Brawl",
        roll_pt: "Destreza + Briga",
        damage: "Strength + 1 to + 3 / L or A",
        damage_pt: "Força + 1 a + 3 / L ou A",
        difficulty: "6",
        actions: 1,
        requirement: "Claws, implants or shapechanged",
        requirement_pt: "Garras, implantes ou metamorfoseado",
        description: "Cyborgs, beasts, shapechanged mages, and folks wearing surgically implanted claws can slash their enemies. Again, this inflicts lethal, not aggravated, damage unless the attacker has some sort of special advantage like Primium claws or Quintessence enhancement. Normal claws inflict Strength +1; Wolverine-style claws dish out Strength +2, and terrifying monster claws deal out Strength +3.",
        description_pt: "Ciborgues, feras, magos metamorfos e indivíduos com garras implantadas cirurgicamente podem retalhar seus inimigos. Novamente, isso causa dano letal (não agravado), a menos que o atacante possua uma vantagem especial como garras de Primium ou aprimoramento por Quintessência. Garras normais causam Força +1; garras estilo Wolverine causam Força +2, e garras monstruosas aterrorizantes podem infligir Força +3.",
    },
    CombatManeuver {
        id: "disarm",
        name: "Disarm",
        name_pt: "Desarmar",
        category: ManeuverCategory::General,
        roll: "Dexterity + Melee (or Brawl / Martial Arts)",
        roll_pt: "Destreza + Armas Brancas (ou Briga / Artes Marciais)",
        damage: "Special (Drops Weapon)",
        damage_pt: "Especial (Derruba a Arma)",
        difficulty: "+1 usual / 8 (bare hands) / 7 (Martial Arts 3+)",
        actions: 1,
        requirement: "None",
        requirement_pt: "Nenhum",
        description: "With a clever strike and twist, the fighter removes her opponent’s weapon from his hand. To succeed, the attacker rolls Dexterity + Melee at +1 to her usual difficulty; if her successes exceed her opponent’s Strength score, then he drops that weapon. If she doesn’t score enough successes to disarm the opponent, she still inflicts her usual damage. If she botches that roll, she loses her own weapon instead.\n\nA brave or skillful attacker can try to disarm an armed opponent with her bare hands. In this case, the roll is Dexterity + Brawl, the difficulty is 8, and she subtracts one die from her usual attack dice pool. A character with at least three dots in the Martial Arts Skill can perform this bare-handed disarm maneuver at difficulty 7 instead; in this case, the roll is Dexterity + Martial Arts, not Brawl.",
        description_pt: "Com um golpe hábil e uma torção, o lutador arranca a arma da mão do oponente. Para ter sucesso, o atacante rola Destreza + Armas Brancas com +1 na dificuldade habitual; se seus sucessos superarem a Força do oponente, este solta a arma. Se não obtiver sucessos suficientes para desarmar, ainda causa o dano normal do golpe. Se tiver uma falha crítica, perde sua própria arma.\n\nUm atacante corajoso ou habilidoso pode tentar desarmar um inimigo armado com as próprias mãos desarmadas. Nesse caso, o teste é Destreza + Briga, dificuldade 8, e subtrai um dado de sua parada. Um personagem com pelo menos três pontos em Artes Marciais pode realizar esse desarme desarmado na dificuldade 7 (Destreza + Artes Marciais).",
    },
    CombatManeuver {
        id: "flank_rear",
        name: "Flank or Rear Attacks",
        name_pt: "Ataques de Flanco ou Retaguarda",
        category: ManeuverCategory::General,
        roll: "Normal attack roll",
        roll_pt: "Teste normal de ataque",
        damage: "Normal",
        damage_pt: "Normal",
        difficulty: "-1 (Flank) / -2 (Rear)",
        actions: 1,
        requirement: "Tactical positioning",
        requirement_pt: "Posicionamento tático vantajoso",
        description: "By attacking an opponent’s flank, an attacker reduces his difficulty by -1; by attacking from the rear, he reduces it by -2.",
        description_pt: "Ao atacar o flanco de um oponente, o atacante reduz a dificuldade de seu ataque em -1; ao atacar pelas costas (retaguarda), a dificuldade é reduzida em -2.",
    },
    CombatManeuver {
        id: "grapple",
        name: "Grapple",
        name_pt: "Agarrar / Imobilizar (Clinch)",
        category: ManeuverCategory::General,
        roll: "Strength + Brawl, Martial Arts, or Do",
        roll_pt: "Força + Briga, Artes Marciais ou Dô",
        damage: "Strength or none / B (L with spikes/claws)",
        damage_pt: "Força ou nenhum / C (L com espinhos/garras)",
        difficulty: "6",
        actions: 1,
        requirement: "Limbs free",
        requirement_pt: "Mãos livres",
        description: "Grabbing hold of her antagonist, the attacker tries to either immobilize him (a hold) or crush him (a clinch). The latter option requires strength, but Life Sphere magick makes many things possible.\n\nTo grapple, the attacker rolls Strength + Brawl, Martial Arts, or Do. If she wants to inflict damage, the player can roll Strength for damage, beginning on the next turn and continuing until her opponent breaks free (who can soak normally). If instead she holds her opponent still, he’s stuck in her grip until his next action.\n\nTo escape, the opponent can break free in a resisted Strength + Brawl roll, or reverse the hold with two successes more. An agile character can use Dexterity to escape; Acrobatics, Martial Arts, or Do can replace Brawl.",
        description_pt: "Segurando seu antagonista, o atacante tenta imobilizá-lo (uma chave) ou esmagá-lo (clinch). Esta última opção exige força bruta, mas a mágica da Esfera da Vida torna muitas coisas possíveis.\n\nPara agarrar, o atacante faz um teste de Força + Briga, Artes Marciais ou Dô. Se desejar infligir dor, o jogador pode rolar Força para causar dano a partir do turno seguinte e continuamente até que o oponente se solte (podendo absorver normalmente). Se optar por imobilizar, o alvo fica preso até sua próxima ação.\n\nPara escapar, o oponente pode se soltar vencendo um teste resistido de Força + Briga, ou reverter a chave obtendo dois sucessos a mais que o atacante. Personagens ágeis podem usar Destreza, Acrobacia, Artes Marciais ou Dô.",
    },
    CombatManeuver {
        id: "kick",
        name: "Kick",
        name_pt: "Chute",
        category: ManeuverCategory::General,
        roll: "Dexterity + Brawl",
        roll_pt: "Destreza + Briga",
        damage: "Strength + 1 / B",
        damage_pt: "Força + 1 / C",
        difficulty: "7",
        actions: 1,
        requirement: "None",
        requirement_pt: "Nenhum",
        description: "Lashing out with a leg, the character hits an opponent where it hurts. Kicks normally inflict bashing damage. A cyborg, HIT Mark, or other massive attacker, though, may deal out lethal damage from sheer density.",
        description_pt: "Desferindo um golpe com a perna, o personagem atinge o oponente onde mais dói. Chutes normalmente causam dano contundente (Força +1). Ciborgues, HIT Marks ou atacantes de grande densidade podem causar dano letal pelo puro peso do impacto.",
    },
    CombatManeuver {
        id: "punch",
        name: "Punch",
        name_pt: "Soco",
        category: ManeuverCategory::General,
        roll: "Dexterity + Brawl",
        roll_pt: "Destreza + Briga",
        damage: "Strength / B",
        damage_pt: "Força / C",
        difficulty: "6",
        actions: 1,
        requirement: "None",
        requirement_pt: "Nenhum",
        description: "One fist, one face, one very basic attack. Most punches inflict bashing damage, but punches by metal-handed cyborgs or reinforced gauntlets can do lethal harm instead.",
        description_pt: "Um punho, um rosto, o ataque mais elementar. A maioria dos socos causa dano contundente equivalente à Força, mas golpes de ciborgues com punhos de aço ou manoplas reforçadas podem infligir dano letal.",
    },
    CombatManeuver {
        id: "reading_opponent",
        name: "Reading an Opponent",
        name_pt: "Ler um Oponente",
        category: ManeuverCategory::General,
        roll: "Perception + Combat Trait (vs Wits + Combat Trait)",
        roll_pt: "Percepção + Traço de Combate (vs Raciocínio + Traço)",
        damage: "N/A (+1 die per success on next action)",
        damage_pt: "N/A (+1 dado por sucesso na próxima ação)",
        difficulty: "6",
        actions: 1,
        requirement: "Perception & Combat Trait (max Wits times/scene)",
        requirement_pt: "Percepção & Combate (máx vezes na cena = Raciocínio)",
        description: "Mages specialize in out-thinking their opponents. With the Storyteller’s permission, a hand-to-hand combatant may try to read an opponent’s intentions with a roll of Perception + either Brawling, Do, or Martial Arts. This becomes a resisted roll, pitting the observer’s Perception + combat Trait against her opponent’s Wits + combat Trait. If the observer succeeds, she adds one die per success to the dice pool to perform her next action.\n\nDemands one action. The character may attempt to do this only once per combat scene for each dot she has in Wits. Beyond 20 feet, this does not work without Correspondence or Mind magick.",
        description_pt: "Magos se especializam em superar seus oponentes pela inteligência. Um combatente corpo a corpo pode tentar antecipar as intenções do inimigo com um teste de Percepção + Briga, Dô ou Artes Marciais, resistido por Raciocínio + Traço de Combate do alvo. Se o observador vencer, ganha +1 dado em sua próxima ação por sucesso obtido.\n\nExige 1 ação. O personagem só pode tentar essa manobra um número de vezes por cena igual aos seus pontos em Raciocínio. A distâncias superiores a 6 metros, exige mágica de Correspondência ou Mente.",
    },
    CombatManeuver {
        id: "sweep",
        name: "Sweep",
        name_pt: "Rasteira",
        category: ManeuverCategory::General,
        roll: "Dexterity + Brawl or Melee",
        roll_pt: "Destreza + Briga ou Armas Brancas",
        damage: "None / B (Knocks to ground)",
        damage_pt: "Nenhum / C (Derruba no chão)",
        difficulty: "8",
        actions: 1,
        requirement: "Legs or appropriate weapon",
        requirement_pt: "Pernas ou arma apropriada",
        description: "With a weapon (Melee) or leg (Brawl, Martial Arts, or Do), our fighter knocks his enemy’s own legs out from under him. If the blow succeeds, the antagonist winds up on the ground that turn placing him at a serious disadvantage.",
        description_pt: "Com uma arma (Armas Brancas) ou perna (Briga, Artes Marciais ou Dô), o lutador ceifa a base do oponente por baixo dele. Se acertar, o adversário vai ao chão imediatamente, ficando vulnerável e em grande desvantagem no combate.",
    },
    CombatManeuver {
        id: "tackle",
        name: "Tackle",
        name_pt: "Investida (Derrubar)",
        category: ManeuverCategory::General,
        roll: "Dexterity + Brawl or Athletics",
        roll_pt: "Destreza + Briga ou Atletismo",
        damage: "Strength / B or L",
        damage_pt: "Força / C ou L",
        difficulty: "7",
        actions: 1,
        requirement: "At least 2 yards of running distance",
        requirement_pt: "Ao menos 2 metros de corrida livre",
        description: "Employing a mix of weight and momentum, the attacker throws herself into her opponent. A tackle requires at least two yards of distance. Each combatant must make a successful Dexterity + Athletics roll (diff 6 for attacker, 6 + attacker’s successes for target), or else wind up sprawled on the ground afterward.\n\nFor the most part, tackle damage is bashing. A person crushed beneath a flying cyborg or mass-enhanced body (Life/Forces), however, inflicts lethal damage instead.",
        description_pt: "Usando uma combinação de massa e aceleração, o atacante se arremessa contra o oponente para contê-lo ou impedir sua fuga. Exige pelo menos 2 metros de distância de corrida. Ambos os lutadores devem fazer um teste de Destreza + Atletismo (dificuldade 6 para o atacante; 6 + sucessos do atacante para o alvo), sob pena de caírem esparramados no chão.\n\nO dano é contundente, tornando-se letal caso o atacante seja um ciborgue pesado ou tenha sua massa/momento potencializados por mágica de Vida ou Forças.",
    },

    // ------------------------------------------------------------------------
    // Luta Suja (Dirty Fighting — Requer Briga 3+)
    // ------------------------------------------------------------------------
    CombatManeuver {
        id: "blinding",
        name: "Blinding",
        name_pt: "Cegamento",
        category: ManeuverCategory::DirtyFighting,
        roll: "Dexterity + Subterfuge",
        roll_pt: "Destreza + Subterfúgio",
        damage: "Special (Blinded 1 turn/success, -2 dice)",
        damage_pt: "Especial (Cego 1 turno/sucesso, -2 dados)",
        difficulty: "9",
        actions: 1,
        requirement: "Brawl 3+ and street background",
        requirement_pt: "Briga 3+ e vivência de rua",
        description: "Scratching an enemy’s eyes, throwing dirt in his face, spraying him with chemicals or using some similar attack, the brawler tries to render her opponent sightless. If she succeeds, the enemy gets blinded for one turn per success and loses two dice from his dice pools until he recovers. Five successes or more may destroy the eyes completely.",
        description_pt: "Arranhando os olhos do inimigo, jogando terra ou areia na face, borrifando produtos químicos ou golpeando sorrateiramente, o lutador tenta cegar o oponente. Com sucesso, o adversário fica cego por 1 turno por sucesso e perde 2 dados de todas as suas paradas de ação até se recuperar. Cinco ou mais sucessos podem destruir a visão permanentemente.",
    },
    CombatManeuver {
        id: "body_slam",
        name: "Body Slam",
        name_pt: "Bate-Estaca",
        category: ManeuverCategory::DirtyFighting,
        roll: "Dexterity + Brawl",
        roll_pt: "Destreza + Briga",
        damage: "Strength + 2 / B or L",
        damage_pt: "Força + 2 / C ou L",
        difficulty: "6",
        actions: 2,
        requirement: "Brawl 3+, requires successful grapple",
        requirement_pt: "Briga 3+, exige agarrão bem-sucedido",
        description: "Lifting his opponent up over his head, a strong fighter can use brute strength and momentum to burst various important innards. Requires a successful grappling attack. If the enemy can’t break free within that turn, the brawler can use his next action to slam his foe into the nearest and most painful surface (Strength +2 damage).",
        description_pt: "Erguendo o oponente acima da cabeça, o lutador usa força bruta e gravidade para arrebentar o corpo do adversário contra o solo ou paredes. Exige um agarrão anterior bem-sucedido. Se o alvo não se soltar, a próxima ação do lutador é arremessá-lo violentamente contra a superfície mais dura e dolorosa próxima (Força +2 de dano).",
    },
    CombatManeuver {
        id: "curbstomp",
        name: "Curbstomp",
        name_pt: "Pisoteamento",
        category: ManeuverCategory::DirtyFighting,
        roll: "Strength + Brawl",
        roll_pt: "Força + Briga",
        damage: "Strength + 2 / L",
        damage_pt: "Força + 2 / L",
        difficulty: "6",
        actions: 2,
        requirement: "Brawl 3+, target must be stunned or immobilized",
        requirement_pt: "Briga 3+, alvo atordoado ou imobilizado no chão",
        description: "An ugly way of rearranging someone’s face involves propping said face against a curb or hard surface and stomping down on the back of his head. Requires a stunned or immobilized target, plus one turn to place his face into position. Inflicts lethal damage (Strength +2) and lasting horrific injuries (broken teeth, shattered jaw, ruined face).",
        description_pt: "Uma tática brutal das ruas: apoiar a face do alvo contra o meio-fio ou superfície de concreto e desferir um pisão impiedoso na nuca. Exige que o oponente esteja atordoado ou imobilizado no chão e consome 1 turno para posicioná-lo. Causa dano letal (Força +2) e traumas grotescos (maxilar quebrado, dentes destruídos, deformidade facial).",
    },
    CombatManeuver {
        id: "haymaker",
        name: "Haymaker",
        name_pt: "Cruzado Selvagem",
        category: ManeuverCategory::DirtyFighting,
        roll: "Dexterity + Brawl",
        roll_pt: "Destreza + Briga",
        damage: "Strength + 2 / B (Knockback)",
        damage_pt: "Força + 2 / C (Empurrão)",
        difficulty: "7",
        actions: 1,
        requirement: "Brawl 3+",
        requirement_pt: "Briga 3+",
        description: "Making like Popeye the Sailor, the brawler winds up, spots an opening, and hurls everything she has into a jaw-cracking punch. If successful, this blow knocks the opponent back a yard or so unless he makes a Strength roll (difficulty 8); if he botches, he hits the ground.",
        description_pt: "Como um golpe fulminante de marinheiro, o lutador gira o tronco, aproveita uma brecha na guarda e lança todo o peso de seu corpo em um soco devastador. Em caso de sucesso, empurra o oponente 1 metro para trás a menos que ele passe num teste de Força (dif 8); se falhar criticamente, beija o asfalto.",
    },
    CombatManeuver {
        id: "head_butt",
        name: "Head Butt",
        name_pt: "Cabeçada",
        category: ManeuverCategory::DirtyFighting,
        roll: "Dexterity + Brawl",
        roll_pt: "Destreza + Briga",
        damage: "Strength + 1 / B",
        damage_pt: "Força + 1 / C",
        difficulty: "6",
        actions: 1,
        requirement: "Brawl 3+, close clinch range",
        requirement_pt: "Briga 3+, combate agarrado (corpo a corpo colado)",
        description: "In a close-clinch situation, the attacker can smash her head into the face or stomach of an opponent. Benefit comes from surprise. Inflicts bashing damage. If the target soaks all damage, however, the attacker is stunned for one turn. Head butting a cyborg causes the attacker to suffer the damage herself!",
        description_pt: "Em distância de clinch ou agarramento, o lutador desfere uma cabeçada violenta no nariz ou estômago do oponente aproveitando o fator surpresa. Causa dano contundente de Força +1. Atenção: se o alvo absorver todo o dano, o próprio atacante fica atordoado por 1 turno! Dar cabeçada em ciborgues faz o atacante sofrer o próprio dano.",
    },
    CombatManeuver {
        id: "jab_pistol",
        name: "Jab Pistol",
        name_pt: "Disparo à Queima-Roupa",
        category: ManeuverCategory::DirtyFighting,
        roll: "Dexterity + Brawl",
        roll_pt: "Destreza + Briga",
        damage: "As per firearm + 2 / L",
        damage_pt: "Conforme arma de fogo + 2 / L",
        difficulty: "6",
        actions: 1,
        requirement: "Brawl 3+, pistol in hand, close combat",
        requirement_pt: "Briga 3+, pistola empunhada em combate corpo a corpo",
        description: "Jamming a firearm directly into his opponent’s body, the attacker blasts a rather large hole in her. Risky and messy, this move forces the attacker to get as close as possible. Because the gun is used hand-to-hand, the maneuver employs Brawl instead of Firearms. Only pistols can be used this way, dealing firearm damage +2.",
        description_pt: "Pressionando o cano da arma de fogo diretamente contra o peito ou abdômen do oponente em plena briga física, o atirador puxa o gatilho abrindo um rombo devastador. Como a arma é engatilhada colada na luta corporal, usa-se Briga no lugar de Armas de Fogo. Apenas pistolas podem ser usadas assim, adicionando +2 ao dano padrão da arma.",
    },
    CombatManeuver {
        id: "low_blow",
        name: "Low Blow",
        name_pt: "Golpe Baixo",
        category: ManeuverCategory::DirtyFighting,
        roll: "Dexterity + Brawl",
        roll_pt: "Destreza + Briga",
        damage: "Strength + Stun / B or L",
        damage_pt: "Força + Atordoamento / C ou L",
        difficulty: "7",
        actions: 1,
        requirement: "Brawl 3+",
        requirement_pt: "Briga 3+",
        description: "Going for the takedown, a brawler aims a shot at some location – kidneys, septum, genitals – that’s sure to hurt a lot. If successful, the target winds up stunned for one turn for each health level inflicted after soak (can resist with Stamina roll diff 8).",
        description_pt: "Mirando pontos hipersensíveis — genitais, rim, septo nasal ou plexo solar —, o lutador busca a incapacitação imediata pela dor. O alvo fica atordoado por 1 turno para cada nível de vitalidade sofrido após a absorção, podendo tentar resistir com um teste de Vigor (dificuldade 8).",
    },
    CombatManeuver {
        id: "pistol_whip",
        name: "Pistol Whip",
        name_pt: "Coronhada",
        category: ManeuverCategory::DirtyFighting,
        roll: "Dexterity + Melee",
        roll_pt: "Destreza + Armas Brancas",
        damage: "Strength + 2 / L",
        damage_pt: "Força + 2 / L",
        difficulty: "7",
        actions: 1,
        requirement: "Brawl 3+, gun or heavy object in hand",
        requirement_pt: "Briga 3+, arma de fogo ou objeto pesado em mãos",
        description: "Adding emphasis to injury, the brawler cracks his opponent across the head or face with a gun or other small, hard, heavy object (crowbar, mug, laptop). Inflicts lethal damage (Strength +2) and may stun the opponent for one turn on failed Stamina roll (diff 8) or two turns on botch.",
        description_pt: "Golpeando o rosto ou têmpora do oponente com a coronha de metal da pistola (ou objeto pesado como pé de cabra ou notebook), o lutador desfere um traumatismo violento. Causa dano letal de Força +2 e atordoa por 1 turno caso o alvo falhe em teste de Vigor (dif 8), ou por 2 turnos se tiver falha crítica.",
    },

    // ------------------------------------------------------------------------
    // Artes Marciais Canônicas (Martial Arts - M20 pp. 423-426)
    // ------------------------------------------------------------------------
    CombatManeuver {
        id: "counter_throw",
        name: "Counter Throw",
        name_pt: "Contra-Arremesso",
        category: ManeuverCategory::MartialArts,
        roll: "Dexterity + Martial Arts (resisted vs attack)",
        roll_pt: "Destreza + Artes Marciais (resistido vs ataque)",
        damage: "As Throw",
        damage_pt: "Como Arremesso",
        difficulty: "6",
        actions: 1,
        requirement: "Martial Arts 1, Athletics 1 (soft style)",
        requirement_pt: "Artes Marciais 1, Atletismo 1 (estilo suave)",
        description: "Directing an attacker’s momentum against him, the martial artist sends him flying into the nearest wall… or the ground… or worse. A basic soft-style maneuver, this remains an effective technique.\n\nWhen the martial artist is attacked, make a resisted roll of Dexterity + Martial Arts against the attacker’s Dexterity + Brawl, Melee, or Martial Arts (depending on the Ability the opponent uses). If you score more successes than your attacker, you deflect the attack and may – immediately and without having to divide your dice pool – try to throw him (as per Throw). If you fail the throw, you still sidestep his attack.",
        description_pt: "Direcionando o impulso do atacante contra ele mesmo, o artista marcial o arremessa voando contra a parede mais próxima... ou o chão... ou pior. Uma técnica clássica e extremamente eficaz do estilo suave.\n\nAo ser atacado, faça um teste resistido de Destreza + Artes Marciais contra a Destreza + Briga, Armas Brancas ou Artes Marciais do adversário. Se obtiver mais sucessos que o agressor, você deflete o golpe e pode — imediatamente e sem precisar dividir sua parada de dados — tentar arremessá-lo. Se falhar no arremesso, ainda assim consegue se esquivar do golpe.",
    },
    CombatManeuver {
        id: "death_strike",
        name: "Death Strike",
        name_pt: "Golpe Mortal",
        category: ManeuverCategory::MartialArts,
        roll: "Dexterity + Martial Arts",
        roll_pt: "Destreza + Artes Marciais",
        damage: "Strength + 2 / L",
        damage_pt: "Força + 2 / L",
        difficulty: "5",
        actions: 1,
        requirement: "Martial Arts 3 (hard style)",
        requirement_pt: "Artes Marciais 3 (estilo duro)",
        description: "Aiming a rigid hand at an organ, joint, or other incapacitating location, the attacker directs devastating force at that target. This strike inflicts lethal damage.",
        description_pt: "Mirando uma mão rígida como ponta de lança contra um órgão interno, juntura ou ponto incapacitante, o atacante canaliza uma energia devastadora no alvo. Este golpe inflige dano letal.",
    },
    CombatManeuver {
        id: "deflecting_block",
        name: "Deflecting Block",
        name_pt: "Bloqueio Defletor",
        category: ManeuverCategory::MartialArts,
        roll: "Dexterity + Martial Arts",
        roll_pt: "Destreza + Artes Marciais",
        damage: "Attacker’s Strength / B",
        damage_pt: "Força do atacante / C",
        difficulty: "6",
        actions: 1,
        requirement: "Martial Arts 2 (soft style), Athletics or Acrobatics 2",
        requirement_pt: "Artes Marciais 2 (estilo suave), Atletismo ou Acrobacia 2",
        description: "Evading an attacker’s blow, the martial artist redirects the attacker’s force against her. In game terms, the defender rolls Dexterity + Martial Arts in Phase Two: Defense. Each success subtracts one success from the attacker’s roll. If the defender scores more successes than his attacker, then the attacker must roll Dexterity (difficulty 8) or else fall to the ground (or smash into a nearby surface), taking her own Strength in bashing damage.",
        description_pt: "Esquivando-se do golpe do agressor, o artista marcial redireciona o vetor de força do atacante contra ele. O defensor rola Destreza + Artes Marciais na Fase de Defesa. Cada sucesso subtrai um sucesso do teste do atacante. Se o defensor obtiver mais sucessos que o agressor, o atacante deve rolar Destreza (dificuldade 8) ou cairá esparramado no chão (ou contra uma parede próxima), sofrendo sua própria Força em dano contundente.",
    },
    CombatManeuver {
        id: "dragon_tail_sweep",
        name: "Dragon Tail Sweep",
        name_pt: "Rasteira Cauda de Dragão (Varredura)",
        category: ManeuverCategory::MartialArts,
        roll: "Dexterity + Martial Arts",
        roll_pt: "Destreza + Artes Marciais",
        damage: "Opponent’s Strength / B",
        damage_pt: "Força do oponente / C",
        difficulty: "8",
        actions: 1,
        requirement: "Martial Arts 1 (hard style), Athletics or Acrobatics 1",
        requirement_pt: "Artes Marciais 1 (estilo duro), Atletismo ou Acrobacia 1",
        description: "A spinning leg sweep that knocks an opponent sprawling. In game terms, the effects work like a throw, but the martial artist doesn’t need to grab her opponent first.",
        description_pt: "Uma rasteira circular giratória com a perna que derruba o oponente com estrondo. Em regras, os efeitos funcionam exatamente como uma projeção/arremesso, mas o lutador não precisa agarrar o oponente antes de executá-la.",
    },
    CombatManeuver {
        id: "elbow_knee_strike",
        name: "Elbow/Knee Strike",
        name_pt: "Golpe de Cotovelo ou Joelhada",
        category: ManeuverCategory::MartialArts,
        roll: "Dexterity + Martial Arts",
        roll_pt: "Destreza + Artes Marciais",
        damage: "Strength + 1 / B",
        damage_pt: "Força + 1 / C",
        difficulty: "5",
        actions: 1,
        requirement: "Martial Arts 1 (any style)",
        requirement_pt: "Artes Marciais 1 (qualquer estilo)",
        description: "A quick, brutal blow with an elbow or kneecap, usually directed at a vulnerable spot at close range.",
        description_pt: "Um impacto rápido e contundente desferido com a ponta do cotovelo ou rótula do joelho, mirando áreas vulneráveis do tronco ou rosto em combate corpo a corpo colado.",
    },
    CombatManeuver {
        id: "flying_kick",
        name: "Flying Kick",
        name_pt: "Chute Voador",
        category: ManeuverCategory::MartialArts,
        roll: "Dexterity + Martial Arts",
        roll_pt: "Destreza + Artes Marciais",
        damage: "Strength + 2 / B",
        damage_pt: "Força + 2 / C",
        difficulty: "7",
        actions: 1,
        requirement: "Martial Arts 1 (hard style), Athletics or Acrobatics 1",
        requirement_pt: "Artes Marciais 1 (estilo duro), Atletismo ou Acrobacia 1",
        description: "Leaping through the air, the martial artist combines her body weight and momentum into a powerful blow.",
        description_pt: "Saltando pelos ares, o artista marcial combina sua massa corporal e momento cinético em um impacto aéreo formidável.",
    },
    CombatManeuver {
        id: "hard_soft_strike",
        name: "Hard Strike/Soft Strike",
        name_pt: "Golpe Duro ou Golpe Suave",
        category: ManeuverCategory::MartialArts,
        roll: "Dexterity + Martial Arts",
        roll_pt: "Destreza + Artes Marciais",
        damage: "Strength + 1 / B",
        damage_pt: "Força + 1 / C",
        difficulty: "hard 5 / soft 6",
        actions: 1,
        requirement: "Martial Arts 1 (any style)",
        requirement_pt: "Artes Marciais 1 (qualquer estilo)",
        description: "Here’s a basic combat blow, focused with more skill than a wild punch. The hard variant involves a clenched fist or rigid fingers (the Tiger Claw technique), whereas a soft blow typically involves tripping the opponent or otherwise using his own force to hurt him.",
        description_pt: "O golpe básico refinado de combate marcial, desferido com disciplina incomparável a um soco comum. A variante dura utiliza punhos cerrados ou dedos rígidos (Garra de Tigre), enquanto o golpe suave utiliza alavancas, tropeços e o próprio ímpeto do inimigo para feri-lo.",
    },
    CombatManeuver {
        id: "joint_lock",
        name: "Joint Lock",
        name_pt: "Chave de Articulação",
        category: ManeuverCategory::MartialArts,
        roll: "Dexterity + Martial Arts",
        roll_pt: "Destreza + Artes Marciais",
        damage: "Successes / L",
        damage_pt: "Sucessos / L",
        difficulty: "5",
        actions: 1,
        requirement: "Martial Arts 2 (any style), Athletics or Acrobatics 2",
        requirement_pt: "Artes Marciais 2 (qualquer estilo), Atletismo ou Acrobacia 2",
        description: "Having already grappled his opponent, the martial artist applies pressure to joints and pressure points. If he chooses to exert force against that spot, he can dislocate or break limbs, joints, or possibly even the neck.\n\nThe player rolls Dexterity + Martial Arts to grapple his opponent, then may immediately (without dividing his dice pool between attacks) roll Dexterity + Martial Arts to inflict damage. Each success rolled inflicts one health level’s worth of lethal injury.",
        description_pt: "Após prender o oponente em um agarrão anterior, o artista marcial aplica torção e pressão extrema em articulações e juntas anatômicas. Se optar por exercer pressão destrutiva, pode deslocar ou fraturar braços, pernas, ombros ou até mesmo quebrar o pescoço.\n\nO jogador rola Destreza + Artes Marciais para travar o agarrão e, em seguida, pode imediatamente (sem dividir a parada de dados) rolar Destreza + Artes Marciais para dano. Cada sucesso obtido causa diretamente 1 nível de vitalidade em dano letal.",
    },
    CombatManeuver {
        id: "nerve_strike",
        name: "Nerve/Pressure Point Strike",
        name_pt: "Ponto de Pressão ou Golpe no Nervo",
        category: ManeuverCategory::MartialArts,
        roll: "Dexterity + Martial Arts",
        roll_pt: "Destreza + Artes Marciais",
        damage: "Strength + 3 / B (Stun)",
        damage_pt: "Força + 3 / C (Atordoamento)",
        difficulty: "7",
        actions: 1,
        requirement: "Martial Arts 3 (any style)",
        requirement_pt: "Artes Marciais 3 (qualquer estilo)",
        description: "Targeting a vital location, the martial artist directs precision force against it. If the attacker scores at least three successes to hit his opponent, then the opponent must make a Stamina roll (difficulty 8) or else be stunned on the next turn. A botch on that roll stuns her for three turns instead.",
        description_pt: "Mirando feixes nervosos ou centros vitais precisos, o lutador canaliza um choque focalizado. Se obtiver ao menos 3 sucessos no teste de ataque, a vítima deve fazer um teste de Vigor (dificuldade 8) ou ficará atordoada durante o turno seguinte. Uma falha crítica atordoa o oponente por 3 turnos inteiros.",
    },
    CombatManeuver {
        id: "snake_step",
        name: "Snake Step",
        name_pt: "Passo da Serpente",
        category: ManeuverCategory::MartialArts,
        roll: "Dexterity + Martial Arts",
        roll_pt: "Destreza + Artes Marciais",
        damage: "N/A (+3 dice to dodge)",
        damage_pt: "N/A (+3 dados de esquiva)",
        difficulty: "hard 6 / soft 5",
        actions: 1,
        requirement: "Martial Arts 1 (any style), Athletics or Acrobatics 1",
        requirement_pt: "Artes Marciais 1 (qualquer estilo), Atletismo ou Acrobacia 1",
        description: "Shifting away from the blow, our martial artist deftly sidesteps a close or ranged attack. Naturally, he must be able to see it coming first. A successful roll acts as a dodge attempt with an additional three-dice bonus.",
        description_pt: "Deslizando o corpo com fluidez serpenteante, o artista marcial esquiva graciosamente de golpes corpo a corpo ou disparos balísticos (desde que perceba o ataque a tempo). Um sucesso atua como manobra defensiva de esquiva conferindo um bônus de +3 dados adicionais à parada.",
    },
    CombatManeuver {
        id: "snap_kick",
        name: "Snap Kick",
        name_pt: "Chute Rápido (Chicote)",
        category: ManeuverCategory::MartialArts,
        roll: "Dexterity + Martial Arts",
        roll_pt: "Destreza + Artes Marciais",
        damage: "Strength + 1 / B",
        damage_pt: "Força + 1 / C",
        difficulty: "5",
        actions: 1,
        requirement: "Martial Arts 1 (hard style)",
        requirement_pt: "Artes Marciais 1 (estilo duro)",
        description: "Focusing her energy on a simple yet effective kick, the martial artist directs her lower body strength into the blow.",
        description_pt: "Concentrando energia em um golpe frontal veloz, o lutador estala a canela e ponta do pé como um chicote, desferindo um chute limpo com grande rapidez.",
    },
    CombatManeuver {
        id: "spinning_kick",
        name: "Spinning Kick",
        name_pt: "Chute Giratório",
        category: ManeuverCategory::MartialArts,
        roll: "Dexterity + Martial Arts",
        roll_pt: "Destreza + Artes Marciais",
        damage: "Strength + 3 / B",
        damage_pt: "Força + 3 / C",
        difficulty: "6",
        actions: 1,
        requirement: "Martial Arts 2 (hard style), Athletics or Acrobatics 2",
        requirement_pt: "Artes Marciais 2 (estilo duro), Atletismo ou Acrobacia 2",
        description: "Our martial artist spins around and plants a solid kick into the object of his attention.",
        description_pt: "O praticante gira velozmente sobre a base e crava o calcanhar com ímpeto rotacional no alvo, descarregando grande energia de impacto.",
    },
    CombatManeuver {
        id: "throw",
        name: "Throw",
        name_pt: "Arremesso (Projeção)",
        category: ManeuverCategory::MartialArts,
        roll: "Dexterity + Martial Arts",
        roll_pt: "Destreza + Artes Marciais",
        damage: "Strength + movement / B",
        damage_pt: "Força + movimento / C",
        difficulty: "hard 7 / soft 6",
        actions: 1,
        requirement: "Martial Arts 2 (any style)",
        requirement_pt: "Artes Marciais 2 (qualquer estilo)",
        description: "Having grappled her opponent (or used a counter throw), the martial artist slams him into a convenient surface. The attacker needs a Dexterity + Martial Arts dice pool equal to, or higher than, her opponent’s Dexterity. With a successful roll, the martial artist can throw her opponent up to one yard for each success she scores on her attack roll.\n\nWhen he lands, he takes damage based on her strength. If he’d been charging her at the time he was thrown, the impact also inflicts an additional +1 die for every 10 feet he’d been traveling at the time (+10 dice maximum).\n\nIf the impact inflicts more than three health levels in damage (after soaking), the opponent must make a Stamina roll (difficulty 8) or else be stunned for one turn. Should the martial artist throw one opponent into another one, the flying enemy inflicts one die bashing damage for each point of Stamina he has, plus one additional die for momentum (+2 difficulty to the throw roll).",
        description_pt: "Tendo agarrado o adversário (ou empregado um contra-arremesso), a lutadora projeta o corpo dele contra o chão ou paredes. A atacante precisa ter parada de Destreza + Artes Marciais igual ou superior à Destreza do alvo. Em caso de sucesso, projeta o oponente a até 1 metro por sucesso obtido.\n\nAo aterrissar, ele sofre dano baseado na Força da praticante. Se ele estiver investindo em corrida no momento, o choque causa +1 dado extra para cada 3 metros percorridos (máx +10 dados). Se sofrer mais de 3 níveis de dano após absorção, deve passar em teste de Vigor (dif 8) ou fica atordoado por 1 turno.\n\nArremessar um inimigo contra outro: causa 1 dado de dano contundente por ponto de Vigor do corpo lançado mais bônus de impulso (adiciona +2 à dificuldade do teste de arremesso).",
    },
    CombatManeuver {
        id: "thunder_kick",
        name: "Thunder Kick",
        name_pt: "Chute do Trovão",
        category: ManeuverCategory::MartialArts,
        roll: "Dexterity + Martial Arts",
        roll_pt: "Destreza + Artes Marciais",
        damage: "Strength + 3 + successes / B",
        damage_pt: "Força + 3 + sucessos / C",
        difficulty: "7",
        actions: 1,
        requirement: "Martial Arts 3 (hard style), Athletics or Acrobatics 2 (1/5 turns)",
        requirement_pt: "Artes Marciais 3 (estilo duro), Atletismo ou Acrobacia 2 (1x a cada 5 turnos)",
        description: "A devastating flying kick. Hurling himself through the air, the martial artist focuses his chi and mass into a strike potent enough to end most fights immediately. In game terms, each success adds one additional die to the kick’s damage. A character cannot use the Thunder Kick more than once every five turns, however, as it demands intense focus and commitment to the blow.",
        description_pt: "Um salto acrobático lendário de impacto ensurdecedor. Projetando-se no ar, o artista marcial canaliza seu chi e todo o peso corporal em uma colisão devastadora feita para encerrar o combate no ato. Cada sucesso obtido no ataque adiciona um dado extra ao dano contundente. Não pode ser executado mais de uma vez a cada 5 turnos devido à colossal exigência de foco e fôlego.",
    },
    CombatManeuver {
        id: "vital_strike",
        name: "Vital Strike",
        name_pt: "Golpe Vital",
        category: ManeuverCategory::MartialArts,
        roll: "Dexterity + Martial Arts",
        roll_pt: "Destreza + Artes Marciais",
        damage: "Strength / L",
        damage_pt: "Força / L",
        difficulty: "7",
        actions: 1,
        requirement: "Martial Arts 2 (hard style)",
        requirement_pt: "Artes Marciais 2 (estilo duro)",
        description: "A sharp-handed blow to an organ or joint inflicts lethal injury.",
        description_pt: "Um golpe de lâmina de mão ou dedos cerrados em ponta aplicado diretamente em tendões, traqueia ou órgãos vulneráveis, causando ferimentos de natureza letal.",
    },
    CombatManeuver {
        id: "withering_grasp",
        name: "Withering Grasp",
        name_pt: "Aperto Decomponedor (Imobilização Dilacerante)",
        category: ManeuverCategory::MartialArts,
        roll: "Dexterity + Martial Arts",
        roll_pt: "Destreza + Artes Marciais",
        damage: "Strength / B (Disarm)",
        damage_pt: "Força / C (Desarme)",
        difficulty: "7",
        actions: 1,
        requirement: "Martial Arts 3 (soft style)",
        requirement_pt: "Artes Marciais 3 (estilo suave)",
        description: "Grabbing his foe in a painful hold, the martial artist inflicts damage and may disarm her as well. To get the weapon from an enemy’s hand, the martial artist must score at least three successes; with five successes, he can take it away from her and use it himself in a following turn.",
        description_pt: "Apanhando a mão ou membro do adversário em uma chave de torção dolorosíssima, o lutador causa dano e desestabiliza a posse de armas. Com 3 sucessos, arranca e derruba a arma da mão do inimigo no chão; com 5 sucessos, desarma o oponente tomando a arma diretamente para si para usá-la no turno seguinte.",
    },

    // ------------------------------------------------------------------------
    // Regras Especiais de Combate (Special Rules)
    // ------------------------------------------------------------------------
    CombatManeuver {
        id: "two_weapons",
        name: "Two Weapons (Two-Fisted Gunslinger)",
        name_pt: "Duas Armas (Empunhadura Dupla)",
        category: ManeuverCategory::SpecialRules,
        roll: "Dexterity + Firearms or Melee (divided pool)",
        roll_pt: "Destreza + Armas de Fogo ou Armas Brancas (parada dividida)",
        damage: "As per each weapon",
        damage_pt: "Conforme cada arma individual",
        difficulty: "Normal (main hand) / +1 (off hand)",
        actions: 1,
        requirement: "Two one-handed weapons",
        requirement_pt: "Empunhar duas armas de uma mão",
        description: "If you wanna get your John Woo on, the two-fisted gunslinger stunt is an old favorite. Outside the movies, though, it’s far more difficult than it looks. A shooter who employs two guns at once needs to divide her Dexterity + Firearms dice pool between both weapons and also add a +1 difficulty penalty to the gun in her off hand. That said, a skillful combatant can lay down some serious damage with a pair of large pistols and the will to use them.\n\nThe same mechanics apply to dual-wielding melee weapons (dividing Dexterity + Melee with +1 difficulty to the secondary hand).",
        description_pt: "Para quem deseja canalizar o estilo John Woo, atirar com duas armas simultâneas é um clássico. Fora dos cinemas, contudo, é muito mais difícil do que parece. Um atirador que empunha duas pistolas ao mesmo tempo precisa dividir sua parada de dados de Destreza + Armas de Fogo entre os dois disparos e ainda somar uma penalidade de +1 na dificuldade para o tiro com a mão inábil.\n\nA mesma regra se aplica ao combate corpo a corpo com duas armas brancas (divide Destreza + Armas Brancas com +1 de dificuldade na mão secundária).",
    },

    // ------------------------------------------------------------------------
    // Técnicas Especiais de Dô (Akashic Brotherhood / M20 pp. 423-426, 448-450)
    // ------------------------------------------------------------------------
    CombatManeuver {
        id: "arrow_cutting",
        name: "Arrow Cutting",
        name_pt: "Aparar Flechas",
        category: ManeuverCategory::Do,
        roll: "Dexterity + Do",
        roll_pt: "Destreza + Dô",
        damage: "As Weapon",
        damage_pt: "Conforme Arma",
        difficulty: "7 (deflect) / 9 (catch & throw)",
        actions: 1,
        requirement: "Do 2+, Akashic Tradition",
        requirement_pt: "Dô 2+, Tradição Akashiana",
        description: "With blinding speed, the Tao-shih catches arrows and other projectile weapons (no bullets), knocks them out of the air, and sometimes even throws them back at her attackers. At difficulty 7, the devotee can deflect an incoming missile of arrow speed or slower; at difficulty 9, she can catch it and throw it back with her next action.",
        description_pt: "Com velocidade relampejante, o Tao-shih apara flechas e outras armas de projétil (não balas de fogo), rebatendo-as no ar e podendo inclusive arremessá-las de volta contra os atacantes. Na dificuldade 7, deflete um projétil com velocidade de flecha ou inferior; na dificuldade 9, agarra o projétil no ar e o lança de volta com sua próxima ação.",
    },
    CombatManeuver {
        id: "hurricane_throw",
        name: "Hurricane Throw",
        name_pt: "Arremesso Furacão",
        category: ManeuverCategory::Do,
        roll: "Dexterity + Do",
        roll_pt: "Destreza + Dô",
        damage: "Strength + 3 + successes / B",
        damage_pt: "Força + 3 + sucessos / C",
        difficulty: "8",
        actions: 1,
        requirement: "Do 2+, Akashic Tradition",
        requirement_pt: "Dô 2+, Tradição Akashiana",
        description: "The remarkable power of Do allows a practitioner to catch or grab his opponent and then throw her with incredible force. Essentially, this is a typical martial arts throw with the damage and difficulty listed below; each success, however, adds one die to the Hurricane Throw’s damage pool. This damage, unlike that of other unarmed attacks, is not lethal… though it can be quite significant.",
        description_pt: "O extraordinário poder do Dô permite ao praticante agarrar o oponente e projetá-lo com força colossal. Essencialmente, trata-se de um arremesso marcial clássico com dificuldade 8; cada sucesso obtido na rolagem adiciona um dado à parada de dano do arremesso. Ao contrário de outros ataques desarmados de Dô, este dano é contundente, e não letal — embora seja devastador.",
    },
    CombatManeuver {
        id: "iron_shirt",
        name: "Iron Shirt",
        name_pt: "Camisa de Ferro",
        category: ManeuverCategory::Do,
        roll: "Adds Do Trait to soak roll",
        roll_pt: "Soma nível de Dô à rolagem de absorção",
        damage: "N/A (Soak Bonus)",
        damage_pt: "N/A (Bônus de Absorção)",
        difficulty: "N/A",
        actions: 0,
        requirement: "Do 2+, Akashic Tradition",
        requirement_pt: "Dô 2+, Tradição Akashiana",
        description: "Through intense conditioning and focused chi, a practitioner can withstand terrible blows. In game terms, he gains one bonus soak die for every dot he has in Do. Although this Iron Shirt cannot soak lethal damage (unless you’re using the Cinematic Damage option, p. 412), it can grant fantastic stamina to a practitioner of Do.\n\nSadly, this technique does not confer total protection from harm. The character will always take one health level of damage from a blow that exceeds her Stamina Trait. If Lucy Hark gets hit for five levels of damage and she has a Stamina of 2, then she’ll still take one health level from that attack, despite her Iron Shirt technique.",
        description_pt: "Através de condicionamento físico extremo e chi canalizado, o praticante suporta impactos terríveis. O personagem recebe um dado adicional de absorção para cada ponto em Dô. Embora a Camisa de Ferro absorva apenas dano contundente (a menos que use a opção de Dano Cinematográfico, p. 412), concede uma resistência monumental ao Tao-shih.\n\nEssa técnica não confere imunidade total: o personagem sempre sofre ao menos 1 nível de dano se o ataque infligir dano superior ao seu Vigor (ex: sofrer 5 níveis de dano com Vigor 2 sempre causará ao menos 1 nível de vitalidade, independentemente da absorção).",
    },
    CombatManeuver {
        id: "kiaijutsu",
        name: "Kiaijutsu (Iron Shout)",
        name_pt: "Kiaijutsu (Grito de Ferro)",
        category: ManeuverCategory::Do,
        roll: "Stamina, Manipulation or Charisma + Do",
        roll_pt: "Vigor, Manipulação ou Carisma + Dô",
        damage: "Special (Stamina bonus / Terror / Eloquence)",
        damage_pt: "Especial (Bônus Vigor / Terror / Eloquência)",
        difficulty: "7 / Willpower + 3 / 8",
        actions: 1,
        requirement: "Do 2+, Akashic Tradition (1/combat)",
        requirement_pt: "Dô 2+, Tradição Akashiana (1x por combate)",
        description: "Also known as the Iron Shout, kiaijutsu channels the practitioner’s chi through his voice, granting him phenomenal powers of intimidation and force. Once per combat, the Akashic may focus his inner energy into a terrifying kiai, which may have one of the following effects:\n\n• Stamina: Toughens against blows, giving a three-turn Stamina bonus of +1 dot for every success on Stamina + Do (difficulty 7).\n\n• Terror: Frightens enemies by rolling Manipulation + Do (difficulty target’s Willpower + 3). Each success adds +1 difficulty to target's next action (max +3). If successes exceed target’s Willpower, enemy is stunned or flees. Against weak-willed opponents (Willpower 4 or less), one enemy flees per success.\n\n• Eloquence: Channeling toward a softer voice, rolls Charisma + Do (difficulty 8); each success adds +1 success to next Expression, Leadership, Intimidation, or performance Art roll.\n\nMust declare at beginning of action, or split pool as second action.",
        description_pt: "Também conhecido como o Grito de Ferro, o kiaijutsu canaliza o chi através da voz com poder estarrecedor. Uma vez por combate, o akashiano pode disparar um kiai interior com um dos seguintes efeitos:\n\n• Vigor: Endurece o corpo contra traumas, concedendo bônus de +1 no Vigor por sucesso em Vigor + Dô (dificuldade 7) com duração de 3 turnos.\n\n• Terror: Aterroriza inimigos rolando Manipulação + Dô (dificuldade: Vontade do alvo + 3). Cada sucesso adiciona +1 na dificuldade da próxima ação do oponente (máx +3). Se os sucessos superarem a Vontade do alvo, ele fica paralisado de pavor ou foge. Contra oponentes de mente fraca (Vontade 4 ou menos), 1 inimigo foge por sucesso.\n\n• Eloquência: Canalizando o grito para modulação persuasiva, rola Carisma + Dô (dificuldade 8); cada sucesso adiciona 1 sucesso automático no próximo teste de Expressão, Liderança, Intimidação ou Arte de performance.\n\nDeve ser declarado no início do turno ou usando divisão de parada para segunda ação.",
    },
    CombatManeuver {
        id: "plum_flower_blossom",
        name: "Plum Flower Blossom",
        name_pt: "Desabrochar da Flor de Ameixeira",
        category: ManeuverCategory::Do,
        roll: "Dexterity + Do",
        roll_pt: "Destreza + Dô",
        damage: "Special (+2 damage dice if attack)",
        damage_pt: "Especial (+2 dados de dano se for ataque)",
        difficulty: "6 (or 7 if attack)",
        actions: 1,
        requirement: "Do 2+, Akashic Tradition",
        requirement_pt: "Dô 2+, Tradição Akashiana",
        description: "Through intense balance training on stumps, pillars, and poles, an Akashic learns to perform incredible feats of acrobatic prowess. By rolling Dexterity + Do (difficulty 6), a practitioner may either double her jumping distance or bounce from object to object for one turn, plus another turn for every two successes scored.\n\nIf one of those leaps gets used as an attack, the difficulty rises by +1 but adds two extra damage dice to that attack. Leaping and attacking are still considered two different actions, so it demands the usual divided dice pool. Especially if it’s enhanced by the Correspondence and/or Forces Spheres, the Plum Flower technique can be quite amazing.",
        description_pt: "Através de treinamento rigoroso de equilíbrio sobre tocos, pilares e postes estreitos, o akashiano realiza acrobacias inacreditáveis. Rolando Destreza + Dô (dificuldade 6), dobra sua distância de salto ou salta de objeto em objeto no ar durante 1 turno, mais 1 turno extra para cada dois sucessos.\n\nSe um desses saltos for usado para desferir um ataque, a dificuldade sobe em +1, mas adiciona +2 dados de dano ao ataque. Saltar e atacar contam como duas ações distintas (exigindo parada dividida). Especialmente potencializado por Correspondência e/ou Forças, o Desabrochar da Ameixeira atinge níveis lendários.",
    },
    CombatManeuver {
        id: "soft_fist",
        name: "Soft Fist (Jou Chuan / Redirection)",
        name_pt: "Punho Suave (Jou Chuan / Redirecionamento)",
        category: ManeuverCategory::Do,
        roll: "Dexterity + Do",
        roll_pt: "Destreza + Dô",
        damage: "Attacker's Strength + weapon + extra successes",
        damage_pt: "Força do atacante + arma + sucessos excedentes",
        difficulty: "7",
        actions: 1,
        requirement: "Do 2+, Akashic Tradition",
        requirement_pt: "Dô 2+, Tradição Akashiana",
        description: "Also known as Jou Chuan or the Redirection technique, the Soft Fist guides a hand-to-hand attack back against those who wish to harm the devotee. If the Akashic using this technique scores more successes than his attacker, he catches the blow and sends it into a nearby character – probably the one who attacked him, or possibly a different enemy.\n\nDamage-wise, Jou Chuan inflicts the attacker’s Strength + weapon, plus one die for every success scored by the Akashic beyond what he needed to catch the attack. If, for instance, Raging Eagle needs three successes to catch his opponent’s attack, and he gets six successes, then the redirected attack inflicts the opponent’s Strength + weapon + three more dice.",
        description_pt: "Também conhecido como Jou Chuan ou Técnica de Redirecionamento, o Punho Suave guia o ataque corpo a corpo do inimigo contra ele mesmo ou outro oponente próximo. Se o akashiano obtiver mais sucessos que o agressor, intercepta o golpe e desvia a força cinética de volta para o agressor ou contra outro inimigo adjacente.\n\nEm dano, o Jou Chuan inflige a Força do atacante + dano da arma dele, mais um dado extra para cada sucesso excedente obtido pelo akashiano além do necessário para interceptar o ataque.",
    },
    CombatManeuver {
        id: "ten_thousand_weapons",
        name: "Ten Thousand Weapons",
        name_pt: "Dez Mil Armas",
        category: ManeuverCategory::Do,
        roll: "Dexterity + Do",
        roll_pt: "Destreza + Dô",
        damage: "Do dice (B) / Lethal / +1 die (L)",
        damage_pt: "Dano = Dô (C) / Letal / +1 dado (L)",
        difficulty: "As weapon / 6",
        actions: 1,
        requirement: "Do 2+, Akashic Tradition",
        requirement_pt: "Dô 2+, Tradição Akashiana",
        description: "In the hands of an especially skillful Warring Fist, anything becomes a weapon. With this technique, the Tao-shih can use any object – a coin, a wallet, a newspaper, whatever – to inflict damage. If the object isn’t normally a weapon, it deals out one die of bashing damage for every dot in the character’s Do Trait; if it’s a weapon that normally inflicts bashing damage, it does lethal damage; and if it normally does lethal damage, it inflicts one extra die of damage when this character employs it.",
        description_pt: "Nas mãos de um Punho Guerreiro experiente, qualquer objeto torna-se uma arma fatal. O Tao-shih pode usar uma moeda, carteira, jornal enrolado ou garrafa para ferir. Se o objeto não for uma arma convencional, causa 1 dado de dano contundente para cada ponto em Dô; se for uma arma que normalmente causa dano contundente, passa a causar dano letal; e se for uma arma que já causa dano letal, adiciona +1 dado extra de dano letal.",
    },
    CombatManeuver {
        id: "typhoon_kick",
        name: "Typhoon Kick",
        name_pt: "Chute Tufão",
        category: ManeuverCategory::Do,
        roll: "Dexterity + Do",
        roll_pt: "Destreza + Dô",
        damage: "Strength + 5 + successes / B or L",
        damage_pt: "Força + 5 + sucessos / C ou L",
        difficulty: "8",
        actions: 1,
        requirement: "Do 2+, Akashic Tradition (1/5 turns)",
        requirement_pt: "Dô 2+, Tradição Akashiana (1x a cada 5 turnos)",
        description: "Perhaps the most devastating strike in the Akashic technique arsenal, the Typhoon Kick directs chi, momentum, and supreme focus into a blow that can shatter stone and kill most human beings. Like the martial arts maneuver Thunder Kick, this attack requires absolute concentration and may be done no more than once every five turns. The practitioner can choose to use either bashing or lethal damage with this kick.\n\nIf she directs it against a solid object (a car, wall, stone elemental, etc.), or a character who manages to soak all the damage, then she must also make a successful soak roll or else take half of the damage, rounded down, herself. (A successful soak roll means no damage.)",
        description_pt: "Provavelmente o golpe mais devastador do arsenal marcial akashiano, o Chute Tufão concentra chi, momento angular e foco absoluto em um impacto capaz de partir pedras e aniquilar oponentes. Exige concentração máxima e só pode ser executado 1 vez a cada 5 turnos. O praticante escolhe causar dano contundente ou letal.\n\nSe desferido contra um obstáculo maciço (carro, parede de concreto, elemental de pedra) ou contra um alvo que absorva todo o dano, o próprio lutador deve rolar absorção ou sofrer metade do dano pretendido (arredondado para baixo).",
    },
    CombatManeuver {
        id: "weapon_art",
        name: "Weapon Art",
        name_pt: "Arte das Armas",
        category: ManeuverCategory::Do,
        roll: "Dexterity + Do or Melee",
        roll_pt: "Destreza + Dô ou Armas Brancas",
        damage: "As Weapon (Lethal option)",
        damage_pt: "Conforme Arma (Opção Letal)",
        difficulty: "Normal - 1",
        actions: 1,
        requirement: "Do 2+, Melee 1+, Dex + Do >= Dex + Melee (no guns)",
        requirement_pt: "Dô 2+, Armas Brancas 1+, Destreza + Dô >= Destreza + Armas Brancas (sem armas de fogo)",
        description: "Applying the mastery of Do into the use of hand-to-hand weaponry, a devotee can use certain weapons with brilliant efficiency. In game terms, the character gets one familiar weapon for every dot he has in the Melee Trait; with those weapons only, he reduces the normal difficulty by -1. If the weapon normally does bashing damage, the Akashic may inflict lethal damage with it instead. He may also use the Arrow Cutting technique with those weapons as well, though he cannot use a weapon to catch projectiles.\n\nIn order to employ this technique, the devotee must have a Dexterity + Do dice pool that’s at least as high as his Dexterity + Melee pool, if not higher. This technique does not apply to guns, though it may be used with bows or thrown weapons.",
        description_pt: "Aplicando a maestria do Dô no manejo de armas brancas e tradicionais, o devoto atinge uma eficácia transcendente. O personagem escolhe uma arma familiar para cada ponto em Armas Brancas; exclusivamente com essas armas, reduz a dificuldade em -1. Se a arma causar dano contundente, pode optar por causar dano letal. Permite também empregar Aparar Flechas com essas armas (embora não possa agarrar projéteis usando a lâmina).\n\nExige que a parada Destreza + Dô seja igual ou superior a Destreza + Armas Brancas. Não se aplica a armas de fogo, mas é válido para arcos e armas de arremesso.",
    },
];

pub fn find_maneuver(query: &str) -> Option<&'static CombatManeuver> {
    let q = query.trim().to_lowercase();
    if q.is_empty() {
        return None;
    }

    // 1. Id match
    if let Some(m) = ALL_COMBAT_MANEUVERS.iter().find(|m| m.id.eq_ignore_ascii_case(&q)) {
        return Some(m);
    }

    // 2. Exact match name or name_pt
    if let Some(m) = ALL_COMBAT_MANEUVERS.iter().find(|m| {
        m.name.to_lowercase() == q || m.name_pt.to_lowercase() == q
    }) {
        return Some(m);
    }

    // 3. Substring match
    if let Some(m) = ALL_COMBAT_MANEUVERS.iter().find(|m| {
        m.name.to_lowercase().contains(&q) || m.name_pt.to_lowercase().contains(&q)
    }) {
        return Some(m);
    }

    // 4. Common aliases & variants
    match q.as_str() {
        "rasteira cauda de dragão" | "rasteira de dragão" | "rasteira do dragão" | "dragon sweep" => {
            ALL_COMBAT_MANEUVERS.iter().find(|m| m.id == "dragon_tail_sweep")
        }
        "chute trovão" | "chute do trovao" | "chute trovao" => {
            ALL_COMBAT_MANEUVERS.iter().find(|m| m.id == "thunder_kick")
        }
        "thunder punch" | "soco trovão" | "soco trovao" => {
            ALL_COMBAT_MANEUVERS.iter().find(|m| m.id == "punch")
        }
        "strike vital point" | "golpe em ponto vital" | "ponto vital" => {
            ALL_COMBAT_MANEUVERS.iter().find(|m| m.id == "vital_strike")
        }
        "roundhouse" | "roundhouse kick" | "chute circular" => {
            ALL_COMBAT_MANEUVERS.iter().find(|m| m.id == "spinning_kick")
        }
        "nerve strike" | "pressure point strike" | "pressure point" | "golpe no nervo" => {
            ALL_COMBAT_MANEUVERS.iter().find(|m| m.id == "nerve_strike")
        }
        "elbow strike" | "knee strike" | "golpe de cotovelo" | "joelhada" => {
            ALL_COMBAT_MANEUVERS.iter().find(|m| m.id == "elbow_knee_strike")
        }
        "hard strike" | "soft strike" | "golpe duro" | "golpe suave" => {
            ALL_COMBAT_MANEUVERS.iter().find(|m| m.id == "hard_soft_strike")
        }
        _ => None,
    }
}

pub fn get_maneuvers_by_category(cat: Option<ManeuverCategory>) -> Vec<&'static CombatManeuver> {
    match cat {
        Some(c) => ALL_COMBAT_MANEUVERS.iter().filter(|m| m.category == c).collect(),
        None => ALL_COMBAT_MANEUVERS.iter().collect(),
    }
}

