//! Catálogo Canônico de Armas Brancas / Melee (M20 pp. 450-451)

use super::models::{WeaponCategory, WeaponDefinition};

pub const HATCHET: WeaponDefinition = WeaponDefinition {
    id: "hatchet",
    name: "Hatchet",
    name_pt: "Machadinha",
    aliases: &["Hatchet", "Machadinha", "Pequeno Machado", "Hand Axe"],
    category: WeaponCategory::Axes,
    difficulty: 6,
    damage: "Strength +1/L",
    damage_pt: "Força +1/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "J",
    notes: &[],
    page_ref: "M20, p. 450",
    description: "A small, one-handed axe designed for chopping wood and close-quarters utility or combat.",
    description_pt: "Um pequeno machado de uma mão projetado para cortar madeira, utilidades em acampamentos ou combate corpo a corpo.",
};

pub const TOMAHAWK: WeaponDefinition = WeaponDefinition {
    id: "tomahawk",
    name: "Tomahawk",
    name_pt: "Tomahawk (Machado Tático)",
    aliases: &["Tomahawk", "Machadinha Indígena", "Tactical Tomahawk"],
    category: WeaponCategory::Axes,
    difficulty: 6,
    damage: "Strength +1/L",
    damage_pt: "Força +1/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "J",
    notes: &["#7"],
    page_ref: "M20, p. 450",
    description: "A lightweight, balanced axe traditionally crafted for throwing and vicious close-range skirmishing.",
    description_pt: "Um machado leve e equilibrado, forjado tradicionalmente para arremessos precisos e combate veloz a curta distância.",
};

pub const AXE: WeaponDefinition = WeaponDefinition {
    id: "axe",
    name: "Axe",
    name_pt: "Machado de Batalha",
    aliases: &["Axe", "Machado", "Battleaxe", "Machado Médio"],
    category: WeaponCategory::Axes,
    difficulty: 7,
    damage: "Strength +3/L",
    damage_pt: "Força +3/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "T",
    notes: &[],
    page_ref: "M20, p. 450",
    description: "A standard combat or woodsman axe with a heavy head capable of sundering armor and bone.",
    description_pt: "Um machado padrão de lenhador ou combate com lâmina pesada capaz de partir armaduras e ossos.",
};

pub const GREAT_AXE: WeaponDefinition = WeaponDefinition {
    id: "great_axe",
    name: "Great Axe",
    name_pt: "Machado Grande / Duas Mãos",
    aliases: &["Great Axe", "Machado de Duas Mãos", "Machado de Guerra", "Greataxe"],
    category: WeaponCategory::Axes,
    difficulty: 7,
    damage: "Strength +6/L",
    damage_pt: "Força +6/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "N",
    notes: &["#1"],
    page_ref: "M20, p. 450",
    description: "A massive, broad-bladed two-handed axe requiring immense muscular strength to cleave through foes.",
    description_pt: "Um machado colossal de lâmina larga e cabo longo exigindo grande poder muscular para desferir golpes devastadores.",
};

pub const POLEARM: WeaponDefinition = WeaponDefinition {
    id: "polearm",
    name: "Polearm",
    name_pt: "Arma de Haste / Alabarda",
    aliases: &["Polearm", "Alabarda", "Halberd", "Lança com Machado", "Glaive"],
    category: WeaponCategory::Axes,
    difficulty: 7,
    damage: "Strength +4/L",
    damage_pt: "Força +4/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "N",
    notes: &["#2"],
    page_ref: "M20, p. 450",
    description: "A combined axe and spear blade mounted on an eight-foot shaft, dominating range in melee combat.",
    description_pt: "Uma cabeça de machado combinada com ponta perfurante montada sobre uma haste longa, dominando o alcance corpo a corpo.",
};

// --- KNIVES & DAGGERS (FACAS & ADAGAS) ---
pub const STILETTO: WeaponDefinition = WeaponDefinition {
    id: "stiletto",
    name: "Stiletto",
    name_pt: "Estilete",
    aliases: &["Stiletto", "Estilete Fino", "Punhal Fino"],
    category: WeaponCategory::Knives,
    difficulty: 4,
    damage: "Strength +1/L",
    damage_pt: "Força +1/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "P",
    notes: &["#3"],
    page_ref: "M20, p. 450",
    description: "A slender needle-pointed dagger specifically forged for sliding between armor joints and ribs.",
    description_pt: "Uma adaga estreita com ponta de agulha feita para penetrar frestas de armaduras e cavidades vitais.",
};

pub const KNIFE: WeaponDefinition = WeaponDefinition {
    id: "knife",
    name: "Knife",
    name_pt: "Faca de Combate / Adaga",
    aliases: &["Knife", "Faca", "Adaga", "Dagger", "Bowie Knife"],
    category: WeaponCategory::Knives,
    difficulty: 5,
    damage: "Strength +1/L",
    damage_pt: "Força +1/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "P",
    notes: &["#3", "#7"],
    page_ref: "M20, p. 450",
    description: "A practical single- or double-edged blade ubiquitous in modern utility and street fights.",
    description_pt: "Uma lâmina prática de corte e perfuração, amplamente portada nas ruas e em kits de sobrevivência.",
};

pub const SAI: WeaponDefinition = WeaponDefinition {
    id: "sai",
    name: "Sai",
    name_pt: "Sai",
    aliases: &["Sai", "Tridente de Mão", "Okinawan Sai"],
    category: WeaponCategory::Knives,
    difficulty: 5,
    damage: "Strength +1/L",
    damage_pt: "Força +1/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "J",
    notes: &["#5", "#6"],
    page_ref: "M20, p. 450",
    description: "A pronged truncheon with twin curved guards, famous for trapping enemy blades and disarming strikes.",
    description_pt: "Uma arma tridente de ponta afiada e guarda curvada dupla, perfeita para prender lâminas inimigas e desarmar agressores.",
};

// --- SWORDS (ESPADAS) ---
pub const SHORT_SWORD: WeaponDefinition = WeaponDefinition {
    id: "short_sword",
    name: "Short Sword",
    name_pt: "Espada Curta (Gládio)",
    aliases: &["Short Sword", "Espada Curta", "Gládio", "Gladius", "Wakizashi"],
    category: WeaponCategory::Swords,
    difficulty: 5,
    damage: "Strength +2/L",
    damage_pt: "Força +2/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "J",
    notes: &["#3"],
    page_ref: "M20, p. 450",
    description: "A compact thrusting and slashing sword, agile in close corridors and shielded formations.",
    description_pt: "Uma espada ágil com comprimento moderado, excelente para investidas rápidas em corredores e espaços confinados.",
};

pub const SWORD: WeaponDefinition = WeaponDefinition {
    id: "sword",
    name: "Sword",
    name_pt: "Espada Longa / Sabre",
    aliases: &["Sword", "Espada", "Espada Longa", "Longsword", "Sabre", "Scimitar"],
    category: WeaponCategory::Swords,
    difficulty: 6,
    damage: "Strength +2/L",
    damage_pt: "Força +2/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "T",
    notes: &["#4"],
    page_ref: "M20, p. 450",
    description: "The classic one-handed martial sword, honed for slicing maneuvers and dueling finesse.",
    description_pt: "A clássica lâmina de combate de uma mão, balanceada para manobras de corte e esgrima refinada.",
};

pub const KATANA: WeaponDefinition = WeaponDefinition {
    id: "katana",
    name: "Katana",
    name_pt: "Katana",
    aliases: &["Katana", "Espada Samurai", "Nihonto"],
    category: WeaponCategory::Swords,
    difficulty: 6,
    damage: "Strength +3/L",
    damage_pt: "Força +3/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "T",
    notes: &["#4"],
    page_ref: "M20, p. 450",
    description: "A curved, single-edged Japanese steel blade celebrated for razor lethality and precise cutting arcs.",
    description_pt: "A consagrada lâmina curvada japonesa de fio único, lendária pela precisão cirúrgica e letalidade em arcos de corte.",
};

pub const GREAT_SWORD: WeaponDefinition = WeaponDefinition {
    id: "great_sword",
    name: "Great Sword",
    name_pt: "Espada de Duas Mãos (Montante)",
    aliases: &["Great Sword", "Montante", "Claymore", "Zweihander", "Espadão"],
    category: WeaponCategory::Swords,
    difficulty: 7,
    damage: "Strength +5/L",
    damage_pt: "Força +5/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "N",
    notes: &["#1"],
    page_ref: "M20, p. 450",
    description: "A towering two-handed battlefield sword capable of keeping multiple foes at bay.",
    description_pt: "Uma imponente espada de campo de batalha com quase dois metros de extensão, exigindo duas mãos para manobras de varredura.",
};

pub const HOOK_SWORD: WeaponDefinition = WeaponDefinition {
    id: "hook_sword",
    name: "Hook Sword(s)",
    name_pt: "Espadas Gancho (Shuang Gou)",
    aliases: &["Hook Sword", "Espadas Gancho", "Shuang Gou", "Tiger Hook"],
    category: WeaponCategory::Swords,
    difficulty: 7,
    damage: "Strength +2/L",
    damage_pt: "Força +2/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "T",
    notes: &["Used as pair", "#2", "#5", "#6"],
    page_ref: "M20, p. 450",
    description: "Twin martial blades tipped with hooking ends and crescent handguards for trapping, sweeping, and disarming.",
    description_pt: "Pares de espadas orientais com pontas curvadas em gancho e punhais crescentes, especializadas em rasteiras e desarmes.",
};

// --- CLUBBING WEAPONS (ARMAS CONTUNDENTES) ---
pub const RIOT_BATON: WeaponDefinition = WeaponDefinition {
    id: "riot_baton",
    name: "Riot Baton",
    name_pt: "Cassetete / Tonfa Policial",
    aliases: &["Riot Baton", "Tonfa", "Cassetete", "Bastão Policial", "Nightstick"],
    category: WeaponCategory::Clubbing,
    difficulty: 5,
    damage: "Strength +1/B",
    damage_pt: "Força +1/C",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "J",
    notes: &[],
    page_ref: "M20, p. 450",
    description: "A sturdy police-issue polycarbonate baton with side-handle grips for non-lethal crowd subdual.",
    description_pt: "Um bastão de policarbonato reforçado com pega lateral, padrão policial para controle de multidões e autodefesa.",
};

pub const BASEBALL_BAT: WeaponDefinition = WeaponDefinition {
    id: "baseball_bat",
    name: "Baseball Bat",
    name_pt: "Taco de Beisebol",
    aliases: &["Baseball Bat", "Taco", "Taco de Beisebol", "Bastão de Madeira"],
    category: WeaponCategory::Clubbing,
    difficulty: 6,
    damage: "Strength +2/B",
    damage_pt: "Força +2/C",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "T",
    notes: &[],
    page_ref: "M20, p. 450",
    description: "Ash wood or aluminum sports bat, providing excellent leverage and blunt kinetic force.",
    description_pt: "Taco esportivo de madeira nobre ou alumínio, oferecendo excelente alavancagem para golpes de concussão contundente.",
};

pub const CROWBAR: WeaponDefinition = WeaponDefinition {
    id: "crowbar",
    name: "Crowbar",
    name_pt: "Pé-de-Cabra",
    aliases: &["Crowbar", "Pé de Cabra", "Alavanca de Ferro"],
    category: WeaponCategory::Clubbing,
    difficulty: 6,
    damage: "Strength +2/B",
    damage_pt: "Força +2/C",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "T",
    notes: &[],
    page_ref: "M20, p. 450",
    description: "A heavy forged-steel utility pry bar that doubles as an agonizingly brutal bludgeon.",
    description_pt: "Uma barra de aço forjado com ponta chanfrada usada para forçar acessos e arrombamento, brutal como porrete.",
};

pub const STAFF: WeaponDefinition = WeaponDefinition {
    id: "staff",
    name: "Staff",
    name_pt: "Cajado / Bordão (Bo)",
    aliases: &["Staff", "Cajado", "Bordão", "Bo", "Quarterstaff"],
    category: WeaponCategory::Clubbing,
    difficulty: 6,
    damage: "Strength +2/B",
    damage_pt: "Força +2/C",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "N",
    notes: &["#2", "#6"],
    page_ref: "M20, p. 450",
    description: "A six-foot seasoned hardwood staff, classic weapon of martial monks, wanderers, and mages.",
    description_pt: "Um bastão cilíndrico de madeira densa com quase dois metros, arma clássica de monges guerreiros e magos peregrinos.",
};

pub const IRON_STAFF: WeaponDefinition = WeaponDefinition {
    id: "iron_staff",
    name: "Iron Staff",
    name_pt: "Bordão de Ferro (Tetsubo)",
    aliases: &["Iron Staff", "Bordão de Ferro", "Bastão de Aço", "Tetsubo"],
    category: WeaponCategory::Clubbing,
    difficulty: 7,
    damage: "Strength +4/B",
    damage_pt: "Força +4/C",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "N",
    notes: &["#1", "#2"],
    page_ref: "M20, p. 450",
    description: "A solid iron or steel-clad staff designed to crack shields, helmets, and vehicular frames.",
    description_pt: "Uma barra maciça de ferro ou madeira revestida em aço, capaz de esmagar armaduras pesadas e estruturas de carros.",
};

pub const MACE: WeaponDefinition = WeaponDefinition {
    id: "mace",
    name: "Mace",
    name_pt: "Maça de Armas",
    aliases: &["Mace", "Maça", "Flanged Mace", "Maça Medieval"],
    category: WeaponCategory::Clubbing,
    difficulty: 6,
    damage: "Strength +3/B",
    damage_pt: "Força +3/C",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "T",
    notes: &[],
    page_ref: "M20, p. 450",
    description: "Flanged iron head on a reinforced handle engineered to pulverize bones beneath plate armor.",
    description_pt: "Cabeça de ferro aletada sobre punho reforçado, criada nos campos medievais para estilhaçar ossos através de armaduras.",
};

pub const NUNCHAKU: WeaponDefinition = WeaponDefinition {
    id: "nunchaku",
    name: "Nunchaku",
    name_pt: "Nunchaku",
    aliases: &["Nunchaku", "Nunchuk", "Bastões Articulados"],
    category: WeaponCategory::Clubbing,
    difficulty: 7,
    damage: "Strength +2/B",
    damage_pt: "Força +2/C",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "J",
    notes: &["#5", "#7"],
    page_ref: "M20, p. 450",
    description: "Two hardwood sticks connected by a short chain or cord, multiplying rotational velocity.",
    description_pt: "Dois pequenos bastões unidos por corrente ou cordame, multiplicando a velocidade cinética em golpes rápidos e desarmes.",
};

pub const SPIKED_CLUB: WeaponDefinition = WeaponDefinition {
    id: "spiked_club",
    name: "Spiked Club",
    name_pt: "Clava com Cravos (Morgenstern)",
    aliases: &["Spiked Club", "Clava com Pregos", "Clava com Cravos", "Morningstar"],
    category: WeaponCategory::Clubbing,
    difficulty: 6,
    damage: "Strength +2/L",
    damage_pt: "Força +2/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "T",
    notes: &[],
    page_ref: "M20, p. 450",
    description: "Heavy club studded with metal spikes or nails, turning crushing blows into lethal lacerations.",
    description_pt: "Porrete pesado cravado de pregos ou puas metálicas, transformando o impacto contundente em lacerações letais.",
};

pub const HUGE_SPIKED_CLUB: WeaponDefinition = WeaponDefinition {
    id: "huge_spiked_club",
    name: "Huge Spiked Club",
    name_pt: "Grande Clava Cravada (Duas Mãos)",
    aliases: &["Huge Spiked Club", "Grande Clava", "Clava de Duas Mãos", "Kanabo"],
    category: WeaponCategory::Clubbing,
    difficulty: 7,
    damage: "Strength +5/L",
    damage_pt: "Força +5/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "N",
    notes: &["#1"],
    page_ref: "M20, p. 450",
    description: "A terrifyingly huge, spiked wooden trunk or kanabo, inflicting traumatic bone-shattering wounds.",
    description_pt: "Um tronco maciço coberto de espigões ou kanabo samurai, exigindo força descomunal para esmagar grupos inteiros.",
};

// --- FIST-EXTENSION WEAPONS (EXTENSÕES DE PUNHO) ---
pub const SAP: WeaponDefinition = WeaponDefinition {
    id: "sap",
    name: "Sap / Black-Jack",
    name_pt: "Cachaporra / Black-Jack (Sap)",
    aliases: &["Sap", "Black-Jack", "Cachaporra", "Porrete de Chumbo", "Slapjack"],
    category: WeaponCategory::FistExtension,
    difficulty: 5,
    damage: "Strength +1/B",
    damage_pt: "Força +1/C",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "P",
    notes: &[],
    page_ref: "M20, p. 450",
    description: "A palm-sized leather pouch loaded with powdered lead, favored for discreet, concussive ambushes.",
    description_pt: "Uma tira de couro cheia de chumbo maleável que cabe na palma da mão, excelente para nocautes discretos e emboscadas.",
};

pub const BRASS_KNUCKLES: WeaponDefinition = WeaponDefinition {
    id: "brass_knuckles",
    name: "Brass Knuckles",
    name_pt: "Soco-Inglês",
    aliases: &["Brass Knuckles", "Soco-Inglês", "Soco Inglês", "Knuckleduster"],
    category: WeaponCategory::FistExtension,
    difficulty: 6,
    damage: "Strength +1/B",
    damage_pt: "Força +1/C",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "P",
    notes: &[],
    page_ref: "M20, p. 450",
    description: "Cast metal guard molded to the fingers, focusing punching force into sharp fracturing impact points.",
    description_pt: "Armação de metal fundido ajustada aos dedos, concentrando a força do murro em pontos fraturantes de impacto.",
};

pub const SPIKED_GAUNTLET: WeaponDefinition = WeaponDefinition {
    id: "spiked_gauntlet",
    name: "Spiked Gauntlet",
    name_pt: "Manopla com Cravos",
    aliases: &["Spiked Gauntlet", "Manopla", "Luva com Espigões"],
    category: WeaponCategory::FistExtension,
    difficulty: 6,
    damage: "Strength +2/L",
    damage_pt: "Força +2/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "T",
    notes: &[],
    page_ref: "M20, p. 450",
    description: "An armored glove fortified with hardened steel knuckles and spikes for deadly bare-knuckle violence.",
    description_pt: "Uma luva de couro pesado e placas de aço com garras e pontas que tornam os golpes de punho letais e dilacerantes.",
};

pub const HAND_CLAWS_SMALL: WeaponDefinition = WeaponDefinition {
    id: "hand_claws_small",
    name: "Hand Claws (Small / Shuko)",
    name_pt: "Garras de Mão Pequenas (Shuko)",
    aliases: &["Hand Claws Small", "Shuko", "Garras Ninja", "Garras de Mão"],
    category: WeaponCategory::FistExtension,
    difficulty: 5,
    damage: "Strength +1/L",
    damage_pt: "Força +1/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "P",
    notes: &[],
    page_ref: "M20, p. 450",
    description: "Concealed metal palm claws used for wall scaling, parrying strikes, and raking flesh.",
    description_pt: "Pequenas garras de metal usadas na palma das mãos para escaladas, aparar golpes e desferir cortes rasgantes.",
};

pub const HAND_CLAWS_LARGE: WeaponDefinition = WeaponDefinition {
    id: "hand_claws_large",
    name: "Hand Claws (Large / Tekko-Kagi)",
    name_pt: "Garras de Mão Grandes (Tekko-Kagi)",
    aliases: &["Hand Claws Large", "Tekko-Kagi", "Garras Longas", "Bagh Nakh"],
    category: WeaponCategory::FistExtension,
    difficulty: 6,
    damage: "Strength +2/L",
    damage_pt: "Força +2/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "J",
    notes: &[],
    page_ref: "M20, p. 450",
    description: "Extended steel talons mounted on forearm bracers that butcher flesh and catch swords.",
    description_pt: "Garras de aço compridas montadas sobre o antebraço e nós dos dedos, rasgando carne com ferocidade primal.",
};

pub const KATAR: WeaponDefinition = WeaponDefinition {
    id: "katar",
    name: "Katar",
    name_pt: "Katar (Adaga de Empunhadura H)",
    aliases: &["Katar", "Adaga de Soco", "Push Dagger", "Adaga Indiana"],
    category: WeaponCategory::FistExtension,
    difficulty: 6,
    damage: "Strength +2/L",
    damage_pt: "Força +2/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "J",
    notes: &["#3"],
    page_ref: "M20, p. 450",
    description: "Indian push dagger with an H-shaped horizontal grip allowing full body weight behind punch-thrusts.",
    description_pt: "Adaga indiana com punho transversal em formato de 'H', descarregando todo o peso do corpo na estocada frontal.",
};

pub const WAR_FAN: WeaponDefinition = WeaponDefinition {
    id: "war_fan",
    name: "War Fan (Tessen)",
    name_pt: "Leque de Guerra (Tessen)",
    aliases: &["War Fan", "Tessen", "Leque de Aço", "Gunsen"],
    category: WeaponCategory::FistExtension,
    difficulty: 6,
    damage: "Strength +1/L",
    damage_pt: "Força +1/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "P",
    notes: &["#5"],
    page_ref: "M20, p. 450",
    description: "An elegant folding fan built with sharpened steel ribs, passing as high-society accessory until striking.",
    description_pt: "Leque dobrável japonês com varetas de aço afiado, disfarçado como objeto nobre de vestuário até o bote mortal.",
};

pub const WIND_AND_FIRE_WHEEL: WeaponDefinition = WeaponDefinition {
    id: "wind_and_fire_wheel",
    name: "Wind and Fire Wheel",
    name_pt: "Rodas de Vento e Fogo",
    aliases: &["Wind and Fire Wheel", "Rodas de Vento e Fogo", "Feng Huo Lun"],
    category: WeaponCategory::FistExtension,
    difficulty: 6,
    damage: "Strength +2/L",
    damage_pt: "Força +2/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "J",
    notes: &["#5"],
    page_ref: "M20, p. 450",
    description: "Crescent metal rings surrounded by stabbing points, excelling in parrying and close-quarters infighting.",
    description_pt: "Anéis metálicos chineses circundados por lâminas e chamas pontiagudas, desenhados para aprisionar armas e cortar.",
};

// --- IMPROVISED WEAPONS (ARMAS IMPROVISADAS) ---
pub const BROKEN_BOTTLE: WeaponDefinition = WeaponDefinition {
    id: "broken_bottle",
    name: "Broken Bottle",
    name_pt: "Garrafa Quebrada",
    aliases: &["Broken Bottle", "Garrafa Quebrada", "Gargalo Quebrado", "Vidro Quebrado"],
    category: WeaponCategory::Improvised,
    difficulty: 6,
    damage: "Strength +1/L",
    damage_pt: "Força +1/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "P",
    notes: &["#8"],
    page_ref: "M20, p. 451",
    description: "A jagged glass bottle neck improvised in barroom brawls, causing nasty lacerating puncture wounds.",
    description_pt: "Gargalo de vidro denteado improvisado em brigas de taverna ou becos, causando lacerações feias.",
};

pub const CHAIR: WeaponDefinition = WeaponDefinition {
    id: "chair",
    name: "Chair",
    name_pt: "Cadeira de Madeira",
    aliases: &["Chair", "Cadeira", "Banqueta"],
    category: WeaponCategory::Improvised,
    difficulty: 7,
    damage: "Strength +2/B",
    damage_pt: "Força +2/C",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "N",
    notes: &["#2", "#8"],
    page_ref: "M20, p. 451",
    description: "A common wooden dining chair or stool swung with two hands to push back and floor opponents.",
    description_pt: "Cadeira ou banqueta comum de madeira empunhada com ambas as mãos para repelir agressores e derrubá-los.",
};

pub const CHAINSAW: WeaponDefinition = WeaponDefinition {
    id: "chainsaw",
    name: "Chainsaw",
    name_pt: "Motosserra",
    aliases: &["Chainsaw", "Motosserra", "Serra Elétrica"],
    category: WeaponCategory::Improvised,
    difficulty: 8,
    damage: "Strength +7/L",
    damage_pt: "Força +7/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "N",
    notes: &["#9"],
    page_ref: "M20, p. 451",
    description: "Gasoline-powered logging saw with a spinning toothed chain, inflicting horrific, mangling carnage.",
    description_pt: "Serra mecânica de corte florestal com dentes giratórios de aço em alta rotação, infligindo carnificina horrível.",
};

pub const TABLE: WeaponDefinition = WeaponDefinition {
    id: "table",
    name: "Table",
    name_pt: "Mesa Pesada",
    aliases: &["Table", "Mesa", "Tampo de Mesa"],
    category: WeaponCategory::Improvised,
    difficulty: 8,
    damage: "Strength +4/B",
    damage_pt: "Força +4/C",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "N",
    notes: &["#1", "#8"],
    page_ref: "M20, p. 451",
    description: "Heavy furniture uprooted and heaved as an improvised bludgeoning shield or battering ram.",
    description_pt: "Móvel pesado de madeira maciça arrancado e arremessado como aríete improvisado para esmagar alvos.",
};

// --- WHIPS AND CHAINS (CHICOTES E CORRENTES) ---
pub const CHAIN: WeaponDefinition = WeaponDefinition {
    id: "chain",
    name: "Chain",
    name_pt: "Corrente de Aço",
    aliases: &["Chain", "Corrente", "Corrente de Aço", "Iron Chain"],
    category: WeaponCategory::WhipsAndChains,
    difficulty: 6,
    damage: "Strength +1/B",
    damage_pt: "Força +1/C",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "J",
    notes: &["#6", "#10"],
    page_ref: "M20, p. 451",
    description: "A three- to five-foot heavy steel link chain, delivering bone-cracking strikes and entangling limbs.",
    description_pt: "Três a cinco pés de elos pesados de aço, proporcionando chicotadas contundentes e laços de imobilização.",
};

pub const CHAIN_WHIP: WeaponDefinition = WeaponDefinition {
    id: "chain_whip",
    name: "Chain Whip",
    name_pt: "Chicote de Nove Elos (Jiujiebian)",
    aliases: &["Chain Whip", "Chicote de Aço", "Nine-Section Whip", "Jiujiebian"],
    category: WeaponCategory::WhipsAndChains,
    difficulty: 7,
    damage: "Strength +2/L",
    damage_pt: "Força +2/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "J",
    notes: &["#9", "#10"],
    page_ref: "M20, p. 451",
    description: "Articulated steel rod segments ending in a dart, demanding sublime acrobatics to avoid self-injury.",
    description_pt: "Segmentos articulados de hastes de aço finalizados por dardo perfurante, exigindo maestria para não ferir o próprio portador.",
};

pub const KUSARIGAMA: WeaponDefinition = WeaponDefinition {
    id: "kusarigama",
    name: "Kusarigama",
    name_pt: "Kusarigama (Foice com Corrente)",
    aliases: &["Kusarigama", "Foice com Corrente", "Kama Chain"],
    category: WeaponCategory::WhipsAndChains,
    difficulty: 7,
    damage: "Strength +2/L",
    damage_pt: "Força +2/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "T",
    notes: &["#2", "#6", "#10"],
    page_ref: "M20, p. 451",
    description: "Sickle attached to a weighted iron chain, entangling swords from afar before delivering the sickle coup de grâce.",
    description_pt: "Foice de mão acoplada a uma longa corrente de ferro com peso de chumbo, enredando lâminas à distância.",
};

pub const MANRIKI_GUSARI: WeaponDefinition = WeaponDefinition {
    id: "manriki_gusari",
    name: "Manriki-Gusari",
    name_pt: "Manriki-Gusari (Corrente com Pesos)",
    aliases: &["Manriki-Gusari", "Manriki", "Kusari", "Corrente com Pesos"],
    category: WeaponCategory::WhipsAndChains,
    difficulty: 6,
    damage: "Strength +1/B",
    damage_pt: "Força +1/C",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "P",
    notes: &["#5", "#6", "#10"],
    page_ref: "M20, p. 451",
    description: "Pocket-sized chain with weighted iron ends used for blocking blades, trapping wrists, and choking.",
    description_pt: "Corrente compacta de elos com pesos cônicos de ferro em cada extremidade, excelente para desarmes e estrangulamentos.",
};

pub const FLOGGER: WeaponDefinition = WeaponDefinition {
    id: "flogger",
    name: "Flogger",
    name_pt: "Chicote Multi-Tiras (Flogger)",
    aliases: &["Flogger", "Chicote de Tiras", "Açoite de Tiras"],
    category: WeaponCategory::WhipsAndChains,
    difficulty: 5,
    damage: "Strength/B",
    damage_pt: "Força/C",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "P",
    notes: &[],
    page_ref: "M20, p. 451",
    description: "Multi-tailed leather scourge that stings bare skin and leaves welts without breaking major bones.",
    description_pt: "Açoite com dezenas de tiras flexíveis de couro macio, desenhado para dor lancinante superficial e marcas.",
};

pub const BARBED_CAT: WeaponDefinition = WeaponDefinition {
    id: "barbed_cat",
    name: "Cat-o'-Nine-Tails (Barbed)",
    name_pt: "Gato de Nove Caudas Farpado",
    aliases: &["Cat-o'-Nine-Tails", "Gato de Nove Caudas", "Chicote Farpado"],
    category: WeaponCategory::WhipsAndChains,
    difficulty: 6,
    damage: "Strength +1/L",
    damage_pt: "Força +1/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "J",
    notes: &[],
    page_ref: "M20, p. 451",
    description: "Brutal nine-tailed scourge tipped with knotted metal barbs, ripping away ribbons of muscle with every strike.",
    description_pt: "Chicote com nó de nove cordas entrelaçadas encimadas por farpas afiadas de aço, estraçalhando músculos.",
};

pub const WHIP: WeaponDefinition = WeaponDefinition {
    id: "whip",
    name: "Whip",
    name_pt: "Chicote Padrão",
    aliases: &["Whip", "Chicote", "Chicote Trançado"],
    category: WeaponCategory::WhipsAndChains,
    difficulty: 6,
    damage: "Strength/L",
    damage_pt: "Força/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "J",
    notes: &["#10"],
    page_ref: "M20, p. 451",
    description: "A braided leather whip capable of cracking beyond the sound barrier, slicing open bare skin and tangling limbs.",
    description_pt: "Um chicote trançado de couro cru cujo estalo quebra a barreira do som, talhando a pele e enroscando membros distantes.",
};

pub const BULLWHIP: WeaponDefinition = WeaponDefinition {
    id: "bullwhip",
    name: "Bullwhip",
    name_pt: "Chicote de Couro (Bullwhip)",
    aliases: &["Bullwhip", "Chicote de Couro", "Chicote Pesado", "Chicote de Boiadeiro"],
    category: WeaponCategory::WhipsAndChains,
    difficulty: 7,
    damage: "Strength +1/L",
    damage_pt: "Força +1/L",
    range: "—",
    rate: "—",
    clip: "—",
    conceal: "J",
    notes: &["#10"],
    page_ref: "M20, p. 451",
    description: "A heavy, long-reach leather whip with an integrated stiff handle that delivers bone-deep lashes across significant distances.",
    description_pt: "Um chicote longo e denso com empunhadura rígida embutida, oferecendo alcance superior e impacto dilacerante profundo.",
};

pub const ALL_MELEE_WEAPONS: &[WeaponDefinition] = &[
    HATCHET, TOMAHAWK, AXE, GREAT_AXE, POLEARM,
    STILETTO, KNIFE, SHORT_SWORD, SWORD, KATANA, GREAT_SWORD, SAI, HOOK_SWORD,
    RIOT_BATON, BASEBALL_BAT, CROWBAR, STAFF, IRON_STAFF, MACE, NUNCHAKU, SPIKED_CLUB, HUGE_SPIKED_CLUB,
    SAP, BRASS_KNUCKLES, SPIKED_GAUNTLET, HAND_CLAWS_SMALL, HAND_CLAWS_LARGE, KATAR, WAR_FAN, WIND_AND_FIRE_WHEEL,
    BROKEN_BOTTLE, CHAIR, CHAINSAW, TABLE,
    CHAIN, CHAIN_WHIP, KUSARIGAMA, MANRIKI_GUSARI, FLOGGER, BARBED_CAT, WHIP, BULLWHIP,
];
