//! Catálogo Canônico de Armas de Fogo, Distância e Arremesso (M20 pp. 452-453)

use super::models::{WeaponCategory, WeaponDefinition};

pub const REVOLVER_LT: WeaponDefinition = WeaponDefinition {
    id: "revolver_lt",
    name: "Revolver, Lt. (SW M640 .38 Special)",
    name_pt: "Revólver Leve (SW M640 .38 Special)",
    aliases: &["SW M640", "Revolver Lt", "Revólver Leve", "Revolver Leve", "38 Special"],
    category: WeaponCategory::Pistols,
    difficulty: 6,
    damage: "4/L",
    damage_pt: "4/L",
    range: "12",
    rate: "3",
    clip: "6",
    conceal: "P",
    notes: &[],
    page_ref: "M20, p. 452",
    description: "A compact snub-nosed 5- or 6-shot .38 revolver, easily tucked away in a pocket or ankle holster.",
    description_pt: "Revólver compacto de cano curto calibre .38, facilmente ocultável em bolsos ou coldres de tornozelo.",
};

pub const REVOLVER_HVY: WeaponDefinition = WeaponDefinition {
    id: "revolver_hvy",
    name: "Revolver, Hvy. (Colt Anaconda .44 Magnum)",
    name_pt: "Revólver Pesado (Colt Anaconda .44 Magnum)",
    aliases: &["Colt Anaconda", "Revolver Hvy", "Revólver Pesado", "44 Magnum"],
    category: WeaponCategory::Pistols,
    difficulty: 6,
    damage: "6/L",
    damage_pt: "6/L",
    range: "35",
    rate: "2",
    clip: "6",
    conceal: "J",
    notes: &[],
    page_ref: "M20, p. 452",
    description: "A massive, roaring magnum revolver capable of cracking engine blocks and punching through doors.",
    description_pt: "Um revólver magnum maciço de alto calibre com poder de perfurar portas e parar veículos com recuo imponente.",
};

pub const PISTOL_LT: WeaponDefinition = WeaponDefinition {
    id: "pistol_lt",
    name: "Semi-Automatic Pistol, Lt. (Glock 17 9mm)",
    name_pt: "Pistola Semi-Automática Leve (Glock 17 9mm)",
    aliases: &["Glock 17", "Light Pistol", "Pistola Leve", "Semi-Automatic Pistol Lt", "9mm"],
    category: WeaponCategory::Pistols,
    difficulty: 6,
    damage: "4/L",
    damage_pt: "4/L",
    range: "20",
    rate: "4",
    clip: "17+1",
    conceal: "P",
    notes: &[],
    page_ref: "M20, p. 452",
    description: "Reliable, polymer-framed standard 9mm sidearm with high magazine capacity and smooth cycling.",
    description_pt: "Pistola de polímero padrão 9mm extremamente confiável, com grande capacidade de carregador e ciclo veloz.",
};

pub const PISTOL_HVY: WeaponDefinition = WeaponDefinition {
    id: "pistol_hvy",
    name: "Semi-Automatic Pistol, Hvy. (Desert Eagle .50 AE)",
    name_pt: "Pistola Semi-Automática Pesada (Desert Eagle .50 AE)",
    aliases: &["Desert Eagle", "Heavy Pistol", "Pistola Pesada", "Desert Eagle 50", "Semi-Automatic Pistol Hvy"],
    category: WeaponCategory::Pistols,
    difficulty: 6,
    damage: "5/L",
    damage_pt: "5/L",
    range: "30",
    rate: "3",
    clip: "7+1",
    conceal: "J",
    notes: &[],
    page_ref: "M20, p. 452",
    description: "A gas-operated hand cannon chambered in .50 Action Express, terrifying in sound and terminal impact.",
    description_pt: "Um canhão de mão a gás disparando projéteis .50 Action Express, apavorante no estampido e no poder de parada.",
};

// --- RIFLES & SUBMACHINE GUNS (FUZIS & SUBMETRALHADORAS) ---
pub const SMG_SMALL: WeaponDefinition = WeaponDefinition {
    id: "smg_small",
    name: "SMG, Small (Ingram Mac-10 9mm)",
    name_pt: "Submetralhadora Pequena (Mac-10 9mm)",
    aliases: &["Mac-10", "Mac 10", "Uzi", "Micro-Uzi", "SMG Small", "Submetralhadora Pequena"],
    category: WeaponCategory::RiflesAndSmgs,
    difficulty: 6,
    damage: "4/L",
    damage_pt: "4/L",
    range: "25",
    rate: "3",
    clip: "30+1",
    conceal: "J",
    notes: &["#1"],
    page_ref: "M20, p. 452",
    description: "Compact open-bolt submachine gun with high cyclic rate of fire, capable of emptying magazines in seconds.",
    description_pt: "Submetralhadora de ferrolho aberto ultracompacta, esvaziando pentes inteiros em rajadas devastadoras a curta distância.",
};

pub const SMG_LARGE: WeaponDefinition = WeaponDefinition {
    id: "smg_large",
    name: "SMG, Large (HK MP-5 9mm)",
    name_pt: "Submetralhadora Grande (HK MP-5 9mm)",
    aliases: &["HK MP5", "MP5", "SMG Large", "Submetralhadora Grande"],
    category: WeaponCategory::RiflesAndSmgs,
    difficulty: 6,
    damage: "4/L",
    damage_pt: "4/L",
    range: "50",
    rate: "3",
    clip: "30+1",
    conceal: "T",
    notes: &["#1"],
    page_ref: "M20, p. 452",
    description: "Tactical police and special forces roller-delayed blowback submachine gun, celebrated for accuracy.",
    description_pt: "A consagrada arma de forças especiais da SWAT e SAS, com recuo controlado em rajadas de precisão cirúrgica.",
};

pub const RIFLE_HUNTING: WeaponDefinition = WeaponDefinition {
    id: "rifle_hunting",
    name: "Rifle (Remington M-700 30.06)",
    name_pt: "Rifle de Precisão / Caça (Remington M-700 30.06)",
    aliases: &["Remington 700", "Rifle", "Fuzil de Caça", "Sniper Rifle"],
    category: WeaponCategory::RiflesAndSmgs,
    difficulty: 6,
    damage: "8/L",
    damage_pt: "8/L",
    range: "200",
    rate: "1",
    clip: "5+1",
    conceal: "N",
    notes: &[],
    page_ref: "M20, p. 452",
    description: "A bolt-action hunting and marksman rifle providing supreme accuracy across vast distances.",
    description_pt: "Fuzil de ferrolho para caça e atiradores de elite com precisão terminal em centenas de metros.",
};

pub const ASSAULT_RIFLE: WeaponDefinition = WeaponDefinition {
    id: "assault_rifle",
    name: "Assault Rifle (AK-47 7.62x39mm)",
    name_pt: "Fuzil de Assalto (AK-47 7.62x39mm)",
    aliases: &["AK-47", "AK47", "Assault Rifle", "Fuzil de Assalto", "M-16", "AR-15"],
    category: WeaponCategory::RiflesAndSmgs,
    difficulty: 6,
    damage: "7/L",
    damage_pt: "7/L",
    range: "150",
    rate: "3",
    clip: "42+1",
    conceal: "N",
    notes: &["#1"],
    page_ref: "M20, p. 452",
    description: "Rugged, gas-operated military assault rifle that operates flawlessly in mud, sand, and blizzards.",
    description_pt: "Fuzil militar de combate padrão com alta penetração balística de 7.62mm, lendário por sua confiabilidade extrema.",
};

// --- SHOTGUNS (ESPINGARDAS) ---
pub const SHOTGUN_SAWED_OFF: WeaponDefinition = WeaponDefinition {
    id: "shotgun_sawed_off",
    name: "Shotgun, Sawed Off (Winchester Model 24 12G)",
    name_pt: "Espingarda de Cano Serrado (Winchester 12)",
    aliases: &["Sawed Off Shotgun", "Cano Serrado", "Shotgun Sawed Off"],
    category: WeaponCategory::Shotguns,
    difficulty: 6,
    damage: "8/L",
    damage_pt: "8/L",
    range: "10",
    rate: "2",
    clip: "2",
    conceal: "J",
    notes: &[],
    page_ref: "M20, p. 452",
    description: "A double-barreled 12-gauge with cut-down barrels, creating a deadly cone of lead at point-blank range.",
    description_pt: "Espingarda de cano duplo serrada, gerando uma nuvem de chumbo impiedosa à queima-roupa e fácil de esconder em jaquetas.",
};

pub const SHOTGUN_PUMP: WeaponDefinition = WeaponDefinition {
    id: "shotgun_pump",
    name: "Shotgun (Ithaca M-37 12 Gauge)",
    name_pt: "Espingarda Pump-Action (Ithaca M-37 12G)",
    aliases: &["Shotgun", "Espingarda", "Ithaca 37", "Remington 870", "Pump Shotgun"],
    category: WeaponCategory::Shotguns,
    difficulty: 6,
    damage: "8/L",
    damage_pt: "8/L",
    range: "20",
    rate: "1",
    clip: "5+1",
    conceal: "T",
    notes: &[],
    page_ref: "M20, p. 452",
    description: "Classic manual pump-action 12-gauge shotgun, trusted for home defense and law enforcement.",
    description_pt: "Espingarda clássica de ação por bombeamento com cartuchos calibre 12 de alto poder destrutivo.",
};

pub const SHOTGUN_SEMI_AUTO: WeaponDefinition = WeaponDefinition {
    id: "shotgun_semi_auto",
    name: "Shotgun, Semi-Automatic (Benelli M4 12G)",
    name_pt: "Espingarda Semi-Automática (Benelli M4 12G)",
    aliases: &["Benelli M4", "Semi-Auto Shotgun", "Shotgun Semi-Automatic", "Benelli"],
    category: WeaponCategory::Shotguns,
    difficulty: 6,
    damage: "8/L",
    damage_pt: "8/L",
    range: "25",
    rate: "3",
    clip: "6+1",
    conceal: "T",
    notes: &[],
    page_ref: "M20, p. 452",
    description: "Combat gas-regulated semi-automatic shotgun providing rapid follow-up shots without pumping.",
    description_pt: "Espingarda tática semi-automática militar permitindo múltiplos disparos de calibre 12 sem necessidade de armação manual.",
};

pub const SHOTGUN_ASSAULT: WeaponDefinition = WeaponDefinition {
    id: "shotgun_assault",
    name: "Shotgun, Assault (MPS AA-12 12 Gauge)",
    name_pt: "Espingarda de Assalto (MPS AA-12 12G)",
    aliases: &["AA-12", "AA12", "MPS AA-12", "Shotgun Assault", "Espingarda de Assalto"],
    category: WeaponCategory::Shotguns,
    difficulty: 6,
    damage: "8/L",
    damage_pt: "8/L",
    range: "50",
    rate: "3",
    clip: "32+1",
    conceal: "N",
    notes: &["#1"],
    page_ref: "M20, p. 452",
    description: "Full-auto combat shotgun feeding from 32-round drum magazines, delivering terrifying area suppression.",
    description_pt: "Espingarda de combate totalmente automática alimentada por tambor de 32 tiros, varrendo salas inteiras em segundos.",
};

// --- TECHNOCRACY SIDEARMS (ARMAS DA TECNOCRACIA) ---
pub const BIGGS_X5_MODEL_R: WeaponDefinition = WeaponDefinition {
    id: "biggs_x5_model_r",
    name: "Biggs X-5 Model R Protector",
    name_pt: "Protetor Biggs X-5 Modelo R",
    aliases: &["Biggs X-5 Model R", "Biggs R", "Model R Protector"],
    category: WeaponCategory::TechnocracySidearms,
    difficulty: 6,
    damage: "5/L",
    damage_pt: "5/L",
    range: "40",
    rate: "4",
    clip: "12",
    conceal: "J",
    notes: &["#2", "#3"],
    page_ref: "M20, p. 452",
    description: "Technocratic composite cylinder sidearm with laser sight and rapid electronic chambering selector.",
    description_pt: "Arma curta da Tecnocracia em compósito impermeável a detectores de metal, com mira laser e seleção eletrônica de munição.",
};

pub const BIGGS_X5_MODEL_A: WeaponDefinition = WeaponDefinition {
    id: "biggs_x5_model_a",
    name: "Biggs X-5 Model A Protector",
    name_pt: "Protetor Biggs X-5 Modelo A",
    aliases: &["Biggs X-5 Model A", "Biggs A", "Model A Protector"],
    category: WeaponCategory::TechnocracySidearms,
    difficulty: 6,
    damage: "5/L",
    damage_pt: "5/L",
    range: "40",
    rate: "4",
    clip: "12+1",
    conceal: "J",
    notes: &["#1", "#2", "#3"],
    page_ref: "M20, p. 452",
    description: "Automatic-fire variant of the composite Biggs X-5 with burst fire capability and integral laser targeting.",
    description_pt: "Versão com capacidade de rajada do Biggs X-5 em compósito, com mira laser e câmara para disparos múltiplos.",
};

pub const BIGGS_MJOLLNER_MK4: WeaponDefinition = WeaponDefinition {
    id: "biggs_mjollner_mk4",
    name: "Biggs Mjollner Mk. IV",
    name_pt: "Biggs Mjollner Mk. IV (Canhão de Mão)",
    aliases: &["Mjollner", "Biggs Mjollner", "Mjollner Mk IV"],
    category: WeaponCategory::TechnocracySidearms,
    difficulty: 6,
    damage: "10/L",
    damage_pt: "10/L",
    range: "100",
    rate: "1",
    clip: "10",
    conceal: "T",
    notes: &["#2", "#4"],
    page_ref: "M20, p. 452",
    description: "Heavy hypertech particle pistol with catastrophic kinetic transfer, reserved strictly for Enlightened operatives.",
    description_pt: "Pistola de partículas pesadas hipertecnológica com impacto cinético avassalador, reservada a operativos Iluminados.",
};

pub const CASTLE_GRAVES_WW3: WeaponDefinition = WeaponDefinition {
    id: "castle_graves_ww3",
    name: "Castle-Graves WW-3",
    name_pt: "Castle-Graves WW-3 (Fuzil Tecnocrata)",
    aliases: &["Castle-Graves", "WW-3", "Castle Graves WW3"],
    category: WeaponCategory::TechnocracySidearms,
    difficulty: 6,
    damage: "8/L",
    damage_pt: "8/L",
    range: "200",
    rate: "3",
    clip: "50+1",
    conceal: "N",
    notes: &["#1", "#2"],
    page_ref: "M20, p. 452",
    description: "Hypertech squad combat rifle with 50-round high-density magazine and target-tracking optics.",
    description_pt: "Fuzil hipertecnológico de esquadrão com carregador de 50 projéteis e ótica com aquisição de alvos em tempo real.",
};

pub const BOLAN_MK13_SYSTEM: WeaponDefinition = WeaponDefinition {
    id: "bolan_mk13_system",
    name: "Bolan Mk. 13 Weapons System",
    name_pt: "Sistema de Armas Bolan Mk. 13",
    aliases: &["Bolan Mk 13", "Bolan Weapons System", "Bolan Mk. 13"],
    category: WeaponCategory::TechnocracySidearms,
    difficulty: 6,
    damage: "Special",
    damage_pt: "Especial",
    range: "Special",
    rate: "Special",
    clip: "Special",
    conceal: "N",
    notes: &["#1", "#2", "#5"],
    page_ref: "M20, p. 452",
    description: "Modular combat rig combining SMG, automatic shotgun, and underbarrel grenade launcher in one heavy frame.",
    description_pt: "Plataforma integrada combinando fuzil de assalto, espingarda automática e lança-granadas sob o mesmo cano reforçado.",
};

pub const HIT_MARK_CHAIN_GUN: WeaponDefinition = WeaponDefinition {
    id: "hit_mark_chain_gun",
    name: "HIT Mark Chain-Gun",
    name_pt: "Metralhadora Rotativa HIT Mark (Chain-Gun)",
    aliases: &["HIT Mark Chain-Gun", "Chain-Gun", "Chain Gun", "Metralhadora HIT Mark"],
    category: WeaponCategory::TechnocracySidearms,
    difficulty: 6,
    damage: "8/L",
    damage_pt: "8/L",
    range: "150",
    rate: "3",
    clip: "200",
    conceal: "N",
    notes: &["#1", "#2", "#11"],
    page_ref: "M20, p. 452",
    description: "Cyborg-mounted multi-barrel rotary cannon that shreds armor plating and biological targets in milliseconds.",
    description_pt: "Canhão rotativo multivias operado por ciborgues HIT Mark, cortando a armadura inimiga pela metade com saraivadas de alta velocidade.",
};

// --- BOWS AND CROSSBOWS (ARCOS E BESTAS) ---
pub const SHORT_BOW: WeaponDefinition = WeaponDefinition {
    id: "short_bow",
    name: "Short Bow",
    name_pt: "Arco Curto",
    aliases: &["Short Bow", "Arco Curto", "Arco Hípico"],
    category: WeaponCategory::Bows,
    difficulty: 6,
    damage: "4/L",
    damage_pt: "4/L",
    range: "60",
    rate: "1",
    clip: "1",
    conceal: "N",
    notes: &["#6"],
    page_ref: "M20, p. 452",
    description: "Lightweight flexible wooden bow agile on horseback or in dense foliage.",
    description_pt: "Arco ágil de madeira flexível com manuseio rápido a cavalo ou entre folhagens fechadas.",
};

pub const HUNTING_BOW: WeaponDefinition = WeaponDefinition {
    id: "hunting_bow",
    name: "Hunting Bow",
    name_pt: "Arco de Caça (Composto)",
    aliases: &["Hunting Bow", "Arco de Caça", "Compound Bow", "Arco Composto"],
    category: WeaponCategory::Bows,
    difficulty: 6,
    damage: "5/L",
    damage_pt: "5/L",
    range: "100",
    rate: "1",
    clip: "1",
    conceal: "N",
    notes: &["#6"],
    page_ref: "M20, p. 452",
    description: "Modern compound bow using pulleys and fiberglass limbs for maximum draw retention and penetration.",
    description_pt: "Arco composto moderno com roldanas excêntricas e hastes de fibra de vidro para tração e penetração superior.",
};

pub const LONG_BOW: WeaponDefinition = WeaponDefinition {
    id: "long_bow",
    name: "Long Bow",
    name_pt: "Arco Longo (Longbow)",
    aliases: &["Long Bow", "Arco Longo", "English Longbow"],
    category: WeaponCategory::Bows,
    difficulty: 6,
    damage: "5/L",
    damage_pt: "5/L",
    range: "120",
    rate: "1",
    clip: "1",
    conceal: "N",
    notes: &["#6"],
    page_ref: "M20, p. 452",
    description: "Traditional yew-wood bow of great height, sending heavy war shafts across hundreds of yards.",
    description_pt: "Arco histórico de teixo de grande envergadura, disparando flechas de guerra a distâncias impressionantes.",
};

pub const CROSSBOW_COMMANDO: WeaponDefinition = WeaponDefinition {
    id: "crossbow_commando",
    name: "Crossbow, Commando",
    name_pt: "Besta Tática Comando (Pistol Crossbow)",
    aliases: &["Crossbow Commando", "Besta Comando", "Pistol Crossbow", "Besta de Pistola"],
    category: WeaponCategory::Bows,
    difficulty: 6,
    damage: "3/L",
    damage_pt: "3/L",
    range: "20",
    rate: "1",
    clip: "1",
    conceal: "J",
    notes: &["#6", "#7"],
    page_ref: "M20, p. 452",
    description: "Compact tactical one-hand crossbow with folding limbs designed for covert close-range hits.",
    description_pt: "Besta de punho compacta com arco dobrável para assassinatos discretos a curta distância.",
};

pub const CROSSBOW: WeaponDefinition = WeaponDefinition {
    id: "crossbow",
    name: "Crossbow",
    name_pt: "Besta Padrão",
    aliases: &["Crossbow", "Besta", "Balestra"],
    category: WeaponCategory::Bows,
    difficulty: 6,
    damage: "5/L",
    damage_pt: "5/L",
    range: "90",
    rate: "1",
    clip: "1",
    conceal: "T",
    notes: &["#6"],
    page_ref: "M20, p. 452",
    description: "Mechanical stock crossbow that releases bolts with devastating kinetic punch without requiring high muscle strength.",
    description_pt: "Besta mecânica com coronha e gatilho disparando virotes com imenso impacto sem depender da Força do atirador.",
};

pub const CROSSBOW_HVY: WeaponDefinition = WeaponDefinition {
    id: "crossbow_hvy",
    name: "Crossbow, Hvy.",
    name_pt: "Besta Pesada (Arbaleste)",
    aliases: &["Crossbow Hvy", "Besta Pesada", "Arbaleste", "Arbalest"],
    category: WeaponCategory::Bows,
    difficulty: 6,
    damage: "6/L",
    damage_pt: "6/L",
    range: "100",
    rate: "1",
    clip: "1",
    conceal: "N",
    notes: &["#6"],
    page_ref: "M20, p. 452",
    description: "Heavy steel-limbed arbalest cocked with a crank or windlass, delivering armor-splitting bolts.",
    description_pt: "Arbaleste pesada com arco de aço armada por manivela mecânica, perfurando cotas de malha e blindagens.",
};

// --- NON-LETHAL AND PACIFICATION WEAPONS (NÃO-LETAIS) ---
pub const TASER: WeaponDefinition = WeaponDefinition {
    id: "taser",
    name: "Taser",
    name_pt: "Taser (Pistola de Choque)",
    aliases: &["Taser", "Pistola de Choque", "Stun Gun"],
    category: WeaponCategory::NonLethal,
    difficulty: 6,
    damage: "5/B",
    damage_pt: "5/C",
    range: "5",
    rate: "1",
    clip: "1",
    conceal: "P",
    notes: &["#8"],
    page_ref: "M20, p. 452",
    description: "Shoots twin dart electrodes delivering 50,000 volts of neuromuscular incapacitation.",
    description_pt: "Dispara dois dardos condutores descarregando 50.000 volts que paralisam os impulsos neuromusculares do alvo.",
};

pub const TEAR_GAS: WeaponDefinition = WeaponDefinition {
    id: "tear_gas",
    name: "Tear Gas",
    name_pt: "Gás Lacrimogêneo",
    aliases: &["Tear Gas", "Gás Lacrimogêneo", "Gas Lacrimogeneo", "CS Gas"],
    category: WeaponCategory::NonLethal,
    difficulty: 6,
    damage: "3/B",
    damage_pt: "3/C",
    range: "3",
    rate: "1",
    clip: "5",
    conceal: "P",
    notes: &["#8"],
    page_ref: "M20, p. 452",
    description: "Chemical irritant canister provoking blinding pain, choking, and severe dice pool penalties.",
    description_pt: "Composto químico lacrimogêneo provocando tosse asfixiante, cegueira temporária e perda severa de dados de ação.",
};

pub const PACIFICATION_SPRAY: WeaponDefinition = WeaponDefinition {
    id: "pacification_spray",
    name: "Pacification Spray",
    name_pt: "Spray de Pacificação Tecnocrática",
    aliases: &["Pacification Spray", "Spray de Pacificação", "Technocracy Spray"],
    category: WeaponCategory::NonLethal,
    difficulty: 6,
    damage: "5/B",
    damage_pt: "5/C",
    range: "3",
    rate: "1",
    clip: "5",
    conceal: "P",
    notes: &["#8"],
    page_ref: "M20, p. 452",
    description: "High-grade Technocratic chemical aerosol inducing immediate disorientation and docile stupor.",
    description_pt: "Aerossol neural de grau avançado desenvolvido pela Tecnocracia para induzir choque e desorientação instantânea.",
};

// --- HEAVY & MILITARY WEAPONS (LANÇA-FOGUETES & ARMAS PESADAS) ---
pub const MACHINE_GUN_30: WeaponDefinition = WeaponDefinition {
    id: "machine_gun_30",
    name: ".30 Caliber Machine Gun",
    name_pt: "Metralhadora Calibre .30",
    aliases: &["30 Caliber Machine Gun", "Metralhadora .30", "M1919 Browning", "M60"],
    category: WeaponCategory::HeavyAndMilitary,
    difficulty: 6,
    damage: "12/L",
    damage_pt: "12/L",
    range: "800",
    rate: "5",
    clip: "100",
    conceal: "N",
    notes: &["#1", "#9"],
    page_ref: "M20, p. 452",
    description: "Belt-fed medium machine gun delivering relentless sustained automatic fire across infantry battlefields.",
    description_pt: "Metralhadora militar média alimentada por fita de 100 tiros, despejando fogo de saturação contínuo.",
};

pub const MACHINE_GUN_50: WeaponDefinition = WeaponDefinition {
    id: "machine_gun_50",
    name: ".50 Caliber Machine Gun",
    name_pt: "Metralhadora Pesada Calibre .50",
    aliases: &["50 Caliber Machine Gun", "Metralhadora .50", "Browning M2", "Ponto 50"],
    category: WeaponCategory::HeavyAndMilitary,
    difficulty: 6,
    damage: "16/L",
    damage_pt: "16/L",
    range: "1000",
    rate: "5",
    clip: "200",
    conceal: "N",
    notes: &["#1", "#9", "#10"],
    page_ref: "M20, p. 452",
    description: "Immense vehicle-mounted heavy machine gun tearing through light armor, cover, and aircraft.",
    description_pt: "Canhão automático antiveicular de calibre .50 montado em blindados, rasgando paredes de concreto e viaturas.",
};

pub const CANNON_30MM: WeaponDefinition = WeaponDefinition {
    id: "cannon_30mm",
    name: "30 mm Cannon",
    name_pt: "Canhão Automático 30 mm",
    aliases: &["30 mm Cannon", "Canhão 30mm", "Autocannon 30mm", "30mm"],
    category: WeaponCategory::HeavyAndMilitary,
    difficulty: 6,
    damage: "15/L",
    damage_pt: "15/L",
    range: "1200",
    rate: "8",
    clip: "100",
    conceal: "N",
    notes: &["#1", "#9", "#11"],
    page_ref: "M20, p. 452",
    description: "Rotary autocannon mounted on armored fighting vehicles and gunships, devastating hardened bunkers.",
    description_pt: "Canhão giratório montado em aeronaves de ataque e tanques blindados, aniquilando fortificações inteiras.",
};

pub const GRENADE_LAUNCHER_M79: WeaponDefinition = WeaponDefinition {
    id: "grenade_launcher_m79",
    name: "M-79 Grenade Launcher",
    name_pt: "Lança-Granadas M-79",
    aliases: &["M-79", "M79", "Grenade Launcher M79", "Lança Granadas M79"],
    category: WeaponCategory::HeavyAndMilitary,
    difficulty: 6,
    damage: "Explosive (#12)",
    damage_pt: "Explosivo (#12)",
    range: "8",
    rate: "1",
    clip: "1",
    conceal: "N",
    notes: &["#9", "#12"],
    page_ref: "M20, p. 452",
    description: "Single-shot break-action 40mm grenade launcher lobbing explosive shells into enemy positions.",
    description_pt: "Lança-granadas monotiro basculante de 40mm, disparando ogivas de alto impacto explosivo e fragmentação.",
};

pub const GRENADE_LAUNCHER_M19: WeaponDefinition = WeaponDefinition {
    id: "grenade_launcher_m19",
    name: "M-19 Grenade Launcher",
    name_pt: "Lança-Granadas Automático M-19",
    aliases: &["M-19", "M19", "Mk 19", "Automatic Grenade Launcher"],
    category: WeaponCategory::HeavyAndMilitary,
    difficulty: 6,
    damage: "Explosive (#12)",
    damage_pt: "Explosivo (#12)",
    range: "2",
    rate: "1",
    clip: "1",
    conceal: "N",
    notes: &["#9", "#10", "#12"],
    page_ref: "M20, p. 452",
    description: "Belt-fed automatic grenade launcher delivering continuous high-explosive area barrages.",
    description_pt: "Lança-granadas automático montado em tripé ou veículos, saturando setores inteiros com munição de 40mm.",
};

pub const FLAMETHROWER: WeaponDefinition = WeaponDefinition {
    id: "flamethrower",
    name: "Flamethrower",
    name_pt: "Lança-Chamas",
    aliases: &["Flamethrower", "Lança-Chamas", "Lanca Chamas", "Lança Chamas"],
    category: WeaponCategory::HeavyAndMilitary,
    difficulty: 6,
    damage: "Napalm (#12)",
    damage_pt: "Napalm (#12)",
    range: "60",
    rate: "1",
    clip: "Special",
    conceal: "N",
    notes: &["#9", "#12"],
    page_ref: "M20, p. 452",
    description: "Projector tank system shooting streams of ignited thickened fuel that stick and consume everything.",
    description_pt: "Arma com tanques dorsais e projetor ejetando jatos viscosos de combustível inflamado em chamas contínuas.",
};

pub const ROCKET_LAUNCHER: WeaponDefinition = WeaponDefinition {
    id: "rocket_launcher",
    name: "Rocket Launcher (RPG / LAW)",
    name_pt: "Lança-Foguetes (RPG / LAW)",
    aliases: &["Rocket Launcher", "RPG", "LAW", "Bazooka", "Lança Foguetes"],
    category: WeaponCategory::HeavyAndMilitary,
    difficulty: 6,
    damage: "12-16/L (#12)",
    damage_pt: "12-16/L (#12)",
    range: "500+",
    rate: "1",
    clip: "1",
    conceal: "N",
    notes: &["#9", "#12"],
    page_ref: "M20, p. 452",
    description: "Shoulder-fired rocket weapon firing shaped charges designed to destroy battle tanks and bunkers.",
    description_pt: "Lança-rojão disparado sobre o ombro com ogiva de carga oca antitanque, pulverizando alvos e paredes.",
};

pub const ALL_RANGED_WEAPONS: &[WeaponDefinition] = &[
    REVOLVER_LT, REVOLVER_HVY, PISTOL_LT, PISTOL_HVY, RIFLE_HUNTING,
    SMG_SMALL, SMG_LARGE, ASSAULT_RIFLE, SHOTGUN_SAWED_OFF, SHOTGUN_PUMP, SHOTGUN_SEMI_AUTO, SHOTGUN_ASSAULT,
    BIGGS_X5_MODEL_R, BIGGS_X5_MODEL_A, BIGGS_MJOLLNER_MK4, CASTLE_GRAVES_WW3, BOLAN_MK13_SYSTEM, HIT_MARK_CHAIN_GUN,
    SHORT_BOW, HUNTING_BOW, LONG_BOW, CROSSBOW_COMMANDO, CROSSBOW, CROSSBOW_HVY,
    TASER, TEAR_GAS, PACIFICATION_SPRAY,
    MACHINE_GUN_30, MACHINE_GUN_50, CANNON_30MM, GRENADE_LAUNCHER_M79, GRENADE_LAUNCHER_M19, FLAMETHROWER, ROCKET_LAUNCHER,
];

// ============================================================================
// 3. THROWN WEAPONS (ARMAS DE ARREMESSO - M20, p. 452) - 6 ARMAS
// ============================================================================

pub const THROWN_KNIFE: WeaponDefinition = WeaponDefinition {
    id: "thrown_knife",
    name: "Knife (Thrown)",
    name_pt: "Faca de Arremesso",
    aliases: &["Knife (Thrown)", "Faca de Arremesso", "Adaga de Arremesso", "Throwing Knife"],
    category: WeaponCategory::ThrownWeapons,
    difficulty: 6,
    damage: "Strength/L",
    damage_pt: "Força/L",
    range: "Strength x 5",
    rate: "1",
    clip: "1",
    conceal: "P",
    notes: &["#7 (Melee)"],
    page_ref: "M20, p. 452",
    description: "Aerodynamically balanced blade weighted for spin and target penetration when cast by hand.",
    description_pt: "Lâmina com balanceamento aerodinâmico no cabo, equilibrada para rotação estável e penetração letal.",
};

pub const SHURIKEN: WeaponDefinition = WeaponDefinition {
    id: "shuriken",
    name: "Shuriken",
    name_pt: "Shuriken (Estrela Ninja)",
    aliases: &["Shuriken", "Estrela Ninja", "Ninja Star"],
    category: WeaponCategory::ThrownWeapons,
    difficulty: 7,
    damage: "3/L",
    damage_pt: "3/L",
    range: "Strength x 5",
    rate: "2",
    clip: "1",
    conceal: "P",
    notes: &[],
    page_ref: "M20, p. 452",
    description: "Flat multi-pointed steel throwing stars concealed in sleeves for rapid, distracting bleeding cuts.",
    description_pt: "Estrela metálica plana de múltiplas pontas afiadas usada em arremessos velozes e distração tática.",
};

pub const THROWN_SPEAR: WeaponDefinition = WeaponDefinition {
    id: "thrown_spear",
    name: "Spear (Thrown / Javelin)",
    name_pt: "Lança de Arremesso (Dardo / Zagaia)",
    aliases: &["Spear (Thrown)", "Lança de Arremesso", "Dardo", "Javelin", "Zagaia"],
    category: WeaponCategory::ThrownWeapons,
    difficulty: 6,
    damage: "Strength +1/L",
    damage_pt: "Força +1/L",
    range: "Strength x 4",
    rate: "1",
    clip: "1",
    conceal: "N",
    notes: &[],
    page_ref: "M20, p. 452",
    description: "A pointed shaft weighted towards the iron tip for maximum ballistic force over medium ranges.",
    description_pt: "Haste com ponta de aço balanceada para arremesso à distância com peso balístico de alto poder de perfuração.",
};

pub const STONE: WeaponDefinition = WeaponDefinition {
    id: "stone",
    name: "Stone",
    name_pt: "Pedra",
    aliases: &["Stone", "Pedra", "Pedregulho"],
    category: WeaponCategory::ThrownWeapons,
    difficulty: 5,
    damage: "Strength/B",
    damage_pt: "Força/C",
    range: "Strength x 6",
    rate: "1",
    clip: "1",
    conceal: "varies",
    notes: &[],
    page_ref: "M20, p. 452",
    description: "A fist-sized rock readily found on the street or countryside, hurled as a blunt missile.",
    description_pt: "Pedra do tamanho do punho encontrada com facilidade, arremessada como projétil contundente imediato.",
};

pub const STONE_LARGE: WeaponDefinition = WeaponDefinition {
    id: "stone_large",
    name: "Stone, Large",
    name_pt: "Pedra Grande / Paralelepípedo",
    aliases: &["Stone Large", "Pedra Grande", "Paralelepípedo", "Rocha"],
    category: WeaponCategory::ThrownWeapons,
    difficulty: 5,
    damage: "Strength +3/B",
    damage_pt: "Força +3/C",
    range: "Strength x 3",
    rate: "1",
    clip: "1",
    conceal: "N",
    notes: &[],
    page_ref: "M20, p. 452",
    description: "A heavy paving stone or boulder requiring two hands or brute force to crush an adversary.",
    description_pt: "Um paralelepípedo ou bloco pesado de alvenaria arremessado para esmagar com impacto demolidor.",
};

pub const THROWN_TOMAHAWK: WeaponDefinition = WeaponDefinition {
    id: "thrown_tomahawk",
    name: "Tomahawk (Thrown)",
    name_pt: "Tomahawk de Arremesso",
    aliases: &["Tomahawk (Thrown)", "Tomahawk de Arremesso", "Machadinha de Arremesso"],
    category: WeaponCategory::ThrownWeapons,
    difficulty: 6,
    damage: "Strength +1/L",
    damage_pt: "Força +1/L",
    range: "Strength x 4",
    rate: "1",
    clip: "1",
    conceal: "J",
    notes: &[],
    page_ref: "M20, p. 452",
    description: "Hand axe thrown with a spinning arc that embeds the heavy steel bit deeply into target targets.",
    description_pt: "Machadinha balanceada arremessada em arco giratório com a lâmina cravando com violência no alvo.",
};

pub const ALL_THROWN_WEAPONS: &[WeaponDefinition] = &[
    THROWN_KNIFE, SHURIKEN, THROWN_SPEAR, STONE, STONE_LARGE, THROWN_TOMAHAWK,
];

